-- AlterTable
ALTER TABLE "MediaAsset" ADD COLUMN     "focalX" DOUBLE PRECISION,
ADD COLUMN     "focalY" DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Provider" ADD COLUMN     "avatarFocalX" DOUBLE PRECISION,
ADD COLUMN     "avatarFocalY" DOUBLE PRECISION,
ADD COLUMN     "bannerFocalX" DOUBLE PRECISION,
ADD COLUMN     "bannerFocalY" DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "UserProfile" ADD COLUMN     "avatarFocalX" DOUBLE PRECISION,
ADD COLUMN     "avatarFocalY" DOUBLE PRECISION;
