/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/features/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        bg: "rgb(var(--bg) / <alpha-value>)",
        "bg-page": "rgb(var(--bg-page) / <alpha-value>)",
        "bg-card": "rgb(var(--bg-card) / <alpha-value>)",
        "bg-input": "rgb(var(--bg-input) / <alpha-value>)",
        "bg-input-focus": "rgb(var(--bg-input-focus) / <alpha-value>)",
        surface: "rgb(var(--surface) / <alpha-value>)",
        elevated: "rgb(var(--elevated) / <alpha-value>)",
        card: "rgb(var(--bg-card) / <alpha-value>)",
        background: "rgb(var(--bg-page) / <alpha-value>)",
        foreground: "rgb(var(--text-main) / <alpha-value>)",
        "text-main": "rgb(var(--text-main) / <alpha-value>)",
        "text-label": "rgb(var(--text-label) / <alpha-value>)",
        "text-sec": "rgb(var(--text-sec) / <alpha-value>)",
        "text-placeholder": "rgb(var(--text-placeholder) / <alpha-value>)",
        input: "rgb(var(--input) / <alpha-value>)",
        border: "rgb(var(--border) / <alpha-value>)",
        "border-subtle": "rgb(var(--border-subtle) / <alpha-value>)",
        "border-focus": "rgb(var(--border-focus) / <alpha-value>)",
        text: "rgb(var(--text) / <alpha-value>)",
        "text-muted": "rgb(var(--text-muted) / <alpha-value>)",
        muted: "rgb(var(--muted) / <alpha-value>)",
        primary: "rgb(var(--primary) / <alpha-value>)",
        "primary-hover": "rgb(var(--primary-hover) / <alpha-value>)",
        "primary-magenta": "rgb(var(--primary-magenta) / <alpha-value>)",
        "primary-glow": "rgb(var(--primary-glow) / <alpha-value>)",
        accent: "rgb(var(--accent) / <alpha-value>)",
        "accent-hover": "rgb(var(--accent-hover) / <alpha-value>)",
        "surface-hover": "rgb(var(--surface-hover) / <alpha-value>)",
        ring: "rgb(var(--ring) / <alpha-value>)",
      },
      boxShadow: {
        soft: "var(--shadow)",
        sm: "var(--shadow-sm)",
        lg: "var(--shadow-lg)",
        card: "var(--shadow-card)",
        hover: "var(--shadow-hover)",
        glow: "0 0 0 1px rgb(var(--primary-glow) / 0.26), 0 14px 28px rgb(var(--primary-glow) / 0.22)",
      },
    },
  },
  plugins: [],
};
