export const UI_TEXT = {
  common: {
    loading: "Загрузка…",
    cancel: "Отмена",
  },
  auth: {
    login: "Вход",
    logout: "Выход",
    menu: "Меню",
    logoutPending: "Выход...",
    loginPage: {
      heroTitle: "Найдите своего мастера за 2 минуты",
      heroSubtitle: "Присоединяйтесь к клиентам и мастерам BeautyHub",
      title: "Вход в BeautyHub",
      subtitle: "Введите номер телефона, чтобы войти или зарегистрироваться.",
      phoneLabel: "Телефон",
      phonePlaceholder: "+77001234567",
      codeLabel: "Код",
      codePlaceholder: "123456",
      invalidPhone: "Введите телефон в международном формате, например +77001234567",
      sendCodeFailed: "Не удалось отправить код",
      enterCode: "Введите код",
      invalidCode: "Неверный код",
      sendCode: "Получить код",
      sending: "Отправляем...",
      codeSentTo: "Код отправлен на",
      verifying: "Проверяем...",
      changePhone: "Изменить телефон",
      returnAfterLogin: "После входа вы вернётесь на:",
      or: "ИЛИ",
      noAccountHint: "Аккаунт создадим автоматически при первом входе",
      telegramSectionTitle: "Войти через Telegram",
    },
    telegram: {
      loginButton: "Войти через Telegram",
      botNotConfigured: "Telegram bot username не настроен.",
      loginFailed: "Не удалось войти через Telegram",
    },
  },
  nav: {
    catalog: "Каталог",
    myBookings: "Мои записи",
    profile: "Профиль",
    myCabinet: "Мой кабинет",
    bookingToMasters: "Запись к мастерам",
    notifications: "Уведомления",
  },
  feed: {
    title: "Витрина вдохновения",
    subtitle: "Найдите идею и запишитесь на результат",
    searchPlaceholder: "Поиск, например «Свадебный макияж»",
    categoryNails: "💅 Ногти",
    categoryHair: "💇‍♀️ Волосы",
    categoryBrowsLashes: "👁️ Брови/Ресницы",
    categoryMakeup: "💄 Мейк",
    categoryBody: "💆‍♀️ Тело",
    tagTrends: "Тренды 2024",
    tagNude: "Нюд",
    tagGradient: "Градиент",
    tagNearby: "Рядом со мной",
    categories: {
      nails: "💅 Ногти",
      hair: "💇‍♀️ Волосы",
      browsLashes: "👁️ Брови/Ресницы",
      makeup: "💄 Мейк",
      body: "💆‍♀️ Тело",
    },
    tags: {
      trends: "Тренды 2024",
      nude: "Нюд",
      gradient: "Градиент",
      nearby: "Рядом со мной",
    },
    bookNow: "Записаться",
    bookThisService: "Записаться на эту услугу",
    addToFavorites: "Добавить в избранное",
    removeFromFavorites: "Убрать из избранного",
    similarWorks: "Похожие работы",
    nearestSlots: "Ближайшие окна",
    total: "Итого",
    whatOnPhoto: "Что на фото",
    showMore: "Показать ещё",
    emptyFeed: "Пока нет работ",
    emptyTitle: "Пока нет работ",
    emptyDesc: "Добавьте первые работы в портфолио мастера.",
    retry: "Повторить",
    loading: "Загрузка ленты…",
    loadFailed: "Не удалось загрузить ленту",
    detailsFailed: "Не удалось загрузить детали работы",
    noSlots: "Нет данных по ближайшим окнам",
    byMaster: "Мастер",
    byStudio: "Студия",
  },
  catalog: {
    capsule: {
      servicePlaceholder: "Услуга",
      districtPlaceholder: "Район",
      datePlaceholder: "Дата",
      find: "Найти",
    },
    chips: {
      price: "Цена",
      availableToday: "Свободно сегодня",
      rating45plus: "⭐ 4.5+",
      studios: "Студии",
      privateMasters: "Частные мастера",
      priceMinPlaceholder: "Мин",
      priceMaxPlaceholder: "Макс",
      apply: "Применить",
      reset: "Сбросить",
    },
    resultsCount: "Результатов",
    viewList: "Список",
    viewMap: "На карте",
    priceFrom: "от",
    priceAllIncluded: "всё включено",
    priceOnRequest: "Цена по запросу",
    noSlots: "Нет мест",
    nextSlotLabel: "Ближайший слот",
    todaySlotsLabel: "Окна сегодня",
    reviewsLabel: "отзывов",
    newLabel: "New",
    mapPlaceholderTitle: "Карта будет здесь",
    mapPlaceholderDesc: "Подключим интерактивную карту в следующем шаге.",
    mapPointsTitle: "Точки на карте",
    carouselPrev: "Предыдущее фото",
    carouselNext: "Следующее фото",
    loadMore: "Показать ещё",
    loading: "Загружаем каталог...",
    loadFailed: "Не удалось загрузить каталог",
    emptyTitle: "Ничего не найдено",
    emptyDesc: "Попробуйте изменить фильтры или запрос.",
    retry: "Повторить",
  },
  master: {
    notifications: {
      title: "Центр уведомлений",
      subtitle: "Приглашения и события по вашему кабинету",
      timelineTitle: "Лента событий",
      timelineSoon: "Лента событий будет обновлена на следующем шаге.",
      filterAll: "Все",
      filterBookings: "Записи",
      filterSystem: "Система",
      bookingCreatedLabel: "Новая запись",
      bookingCancelledLabel: "Отмена записи",
      bookingRescheduledLabel: "Перенос записи",
      systemLabel: "Системное уведомление",
      newBadge: "Новое",
      publishHotWindow: "Опубликовать как «Горящее окно»",
      hotWindowUnavailable: "Публикация «горящего окна» пока недоступна",
      markAllRead: "Отметить всё прочитанным",
      actionFailed: "Не удалось выполнить действие",
      networkError: "Сеть недоступна или сервер не отвечает",
      accepting: "Принимаем...",
      declining: "Отклоняем...",
      accept: "Принять",
      decline: "Отклонить",
      viewStudioProfile: "Посмотреть профиль студии",
    },
    invites: {
      pinnedTitle: "Новые приглашения",
      emptyTitle: "Вас пока никуда не пригласили…",
      emptyDesc: "Заполните профиль, чтобы студии вас замечали",
      fillProfile: "Заполнить профиль",
      phoneRequired: "Укажите номер телефона в профиле, чтобы получать приглашения.",
    },
    platform: {
      title: "Новости платформы",
      soon: "Колонка новостей будет заполнена на следующем шаге.",
    },
  },
  admin: {
    media: {
      siteLogoTitle: "Логотип сайта",
      siteLogoDescription: "Используется в navbar рядом с BeautyHub.",
      loginHeroTitle: "Фото для страницы входа",
      loginHeroDescription: "Большое изображение в левой части страницы /login.",
      uploadImage: "Загрузить изображение",
      replaceImage: "Заменить изображение",
      removeImage: "Удалить изображение",
      emptyImage: "Изображение не загружено",
      uploadFailed: "Не удалось загрузить изображение",
      deleteFailed: "Не удалось удалить изображение",
      loadFailed: "Не удалось загрузить настройки изображения",
    },
  },
} as const;
