export const UI_TEXT = {
  common: {
    loading: "Загрузка…",
    cancel: "Отмена",
    close: "Закрыть",
    noLimit: "Без ограничений",
    notSpecified: "Не указано",
    noPhoto: "Нет фото",
    minutesShort: "мин",
    minutesShortLetter: "м",
    hoursShortLetter: "ч",
    currencyRub: "₽",
    requiredField: "Обязательное поле",
    namePlaceholder: "Имя",
    toggleTheme: "Переключить тему",
  },
  brand: {
    name: "МастерРядом",
  },
  meta: {
    title: "МастерРядом",
    description: "Запись к мастерам",
  },
  actions: {
    save: "Сохранить",
    cancel: "Отмена",
    close: "Закрыть",
    delete: "Удалить",
    add: "Добавить",
    replace: "Заменить",
    remove: "Удалить",
    select: "Выбрать",
    open: "Открыть",
    hide: "Скрыть",
    show: "Показать",
    confirm: "Подтвердить",
    decline: "Отклонить",
    openChat: "Открыть чат",
    update: "Обновить",
    later: "Позже",
    saveChanges: "Сохранить изменения",
    goTo: "Перейти",
  },
  status: {
    saving: "Сохранение...",
    savingInProgress: "Сохраняем...",
    saved: "Сохранено",
    loading: "Загрузка...",
    enabled: "Включено",
    disabled: "Выключено",
    deleting: "Удаляем...",
  },
  auth: {
    login: "Вход",
    logout: "Выход",
    menu: "Меню",
    logoutPending: "Выход...",
    loginPage: {
      heroTitle: "Найдите своего мастера за 2 минуты",
      heroSubtitle: "Присоединяйтесь к клиентам и мастерам МастерРядом",
      title: "Вход в МастерРядом",
      subtitle: "Введите номер телефона, чтобы войти или зарегистрироваться.",
      phoneLabel: "Телефон",
      phonePlaceholder: "+77001234567",
      phonePlaceholderMask: "+7 (___) ___-__-__",
      codeLabel: "Код",
      codePlaceholder: "123456",
      invalidPhone: "Введите телефон в международном формате, например +77001234567",
      sendCodeFailed: "Не удалось отправить код",
      enterCode: "Введите код",
      invalidCode: "Неверный код",
      sendCode: "Получить код",
      sending: "Отправляем...",
      codeSentTo: "Код отправлен на",
      verifying: "Проверяем...",
      changePhone: "Изменить телефон",
      returnAfterLogin: "После входа вы вернётесь на:",
      or: "ИЛИ",
      noAccountHint: "Аккаунт создадим автоматически при первом входе",
      telegramSectionTitle: "Войти через Telegram",
      vkSectionTitle: "Войти через VK",
      consentRequired: "Необходимо согласие с условиями и политикой конфиденциальности.",
    },
    telegram: {
      loginButton: "Войти через Telegram",
      botNotConfigured: "Telegram bot username не настроен.",
      loginFailed: "Не удалось войти через Telegram",
    },
    vk: {
      loginButton: "Войти через VK",
      loginFailed: "Не удалось войти через VK",
    },
  },
  nav: {
    catalog: "Каталог",
    myBookings: "Мои записи",
    profile: "Профиль",
    professionalRoles: "Профессиональные роли",
    settings: "Настройки",
    adminPanel: "🛡️ Админ-панель",
    masterWorkspace: "Мастер",
    studioWorkspace: "Студия",
    bookingToMasters: "Запись к мастерам",
    notifications: "Уведомления",
    userMenuAria: "Открыть меню профиля",
    mobileMenuAria: "Открыть меню навигации",
    mobileMenuTitle: "Навигация",
    openMasterWorkspace: "Открыть кабинет мастера",
    openStudioWorkspace: "Открыть кабинет студии",
    siteLogoAlt: "Логотип сайта",
    forModels: "Для моделей",
    home: "Главная",
    book: "Запись",
    bookings: "Записи",
    clients: "Клиенты",
    schedule: "Расписание",
    calendar: "Календарь",
    services: "Услуги",
    adminShort: "Админ",
    loginAction: "Войти",
  },
  footer: {
    aria: {
      nav: "Навигация футера",
    },
    cta: {
      title: "Вы мастер красоты?",
      subtitle: "Начните принимать клиентов онлайн уже сегодня",
      button: "Создать профиль бесплатно",
    },
    columns: {
      about: "О платформе",
      clients: "Для клиентов",
      masters: "Для мастеров",
      support: "Поддержка",
    },
    links: {
      about: "О нас",
      howItWorks: "Как это работает",
      blog: "Блог",
      partners: "Партнёрам",
      careers: "Вакансии",
      howToBook: "Как забронировать",
      popularServices: "Популярные услуги",
      mastersNearby: "Мастера рядом",
      offersForModels: "Предложения для моделей",
      giftCards: "Подарочные сертификаты",
      becomeMaster: "Стать мастером",
      pricing: "Тарифы",
      knowledgeBase: "База знаний",
      affiliateProgram: "Партнёрская программа",
      faq: "FAQ",
      contact: "Написать нам",
      telegramSupport: "Telegram поддержка",
      terms: "Пользовательское соглашение",
      privacy: "Политика конфиденциальности",
    },
    brandDescription:
      "Маркетплейс мастеров красоты. Находите лучших специалистов рядом и бронируйте услуги онлайн за пару минут.",
    legal: {
      copyright: "© {year} МастерРядом",
      entity: "ИП Иванов Иван Иванович, ИНН 1234567890",
    },
    socials: {
      vk: "VK",
      telegram: "Telegram",
    },
  },
  pwa: {
    install: {
      title: "Установить МастерРядом",
      iosHintPrefix: "Нажмите",
      iosHintSuffix: "и выберите «На экран Домой».",
      shareLabel: "Поделиться",
      nonIosHint: "Добавьте приложение на главный экран для быстрого доступа.",
      install: "Установить",
    },
    update: {
      title: "Доступно обновление приложения",
      update: "Обновить",
    },
  },
  network: {
    offline: "Нет подключения к интернету",
    reconnected: "Соединение восстановлено",
  },
  deletion: {
    confirmKeyword: "УДАЛИТЬ",
    masterTitle: "Удаление кабинета мастера",
    studioTitle: "Удаление кабинета студии",
    masterWarning:
      "Удаление кабинета мастера необратимо. Все услуги, расписание и портфолио будут удалены. История завершённых записей сохраняется в соответствии с законодательством.",
    studioWarning:
      "Все мастера студии получат уведомление о расформировании. Удаление невозможно если есть незавершённые записи.",
    confirmPrompt: "Для подтверждения введите «{keyword}»",
    activeBookingsWarning: "Сначала завершите или отмените все активные записи ({count} шт.)",
    accountTitle: "Удаление аккаунта",
    accountWarning: "Подтвердите, что вы понимаете последствия удаления аккаунта.",
    accountConfirmCheckbox: "Я понимаю, что это действие необратимо",
    accountPhonePrompt: "Введите номер телефона для подтверждения",
    accountDeleteForever: "Удалить мой аккаунт навсегда",
  },
  notifications: {
    toastTitle: "У вас новое уведомление",
    declineReason: "Отклонено",
  },
  billing: {
    featureGate: {
      ctaLabel: "Посмотреть тарифы",
      loading: "Загрузка компонента...",
      title: "Функция недоступна",
      description: "Доступно на тарифе {plan}.",
    },
  },
  cabinetHub: {
    title: "Как вы хотите работать сегодня?",
    subtitle: "Выберите ваше пространство в МастерРядом.",
    clientTitle: "Клиент",
    clientDescription: "Личный профиль, ваши записи и уведомления.",
    masterTitle: "Мастер",
    masterDescription: "Мой день, график и управление услугами.",
    studioTitle: "Студия",
    studioDescription: "Команда, услуги, календарь и аналитика студии.",
    open: "Открыть",
  },
  cabinetRoles: {
    studio: {
      title: "У меня студия",
      description: "Управляйте командой мастеров, филиалами и общим расписанием",
      upsellTitle: "Расширяйтесь до студии",
      upsellDescription: "Добавьте команду мастеров и управляйте расписанием в одном месте",
      openCabinet: "Открыть кабинет",
      deleteRole: "Удалить роль студии",
      logoFallback: "Лого",
      label: "Студия",
      statusPublished: "Опубликована",
      statusDraft: "Черновик",
    },
  },
  cabinetRolesPage: {
    title: "Профессиональные роли",
    subtitle: "Управляйте своим бизнесом или работой мастера",
    masterProfileTitle: "Профиль мастера",
    studioTitle: "Студия",
    openCabinet: "Открыть кабинет",
    masterPublished: "Профиль опубликован",
    masterDraft: "Профиль не опубликован",
    studioPublished: "Опубликована",
    studioDraft: "Черновик",
    mastersCount: "Мастеров: {count}",
    ratingTemplate: "★ {rating} ({count})",
  },
  notificationsCenter: {
    title: "Уведомления",
    subtitle: "Единый центр приглашений и системных событий.",
    invitesTitle: "Приглашения в студии",
    timelineTitle: "Лента событий",
    phoneRequired: "Добавьте номер телефона в профиль, чтобы получать приглашения.",
    emptyTimeline: "По выбранному фильтру пока нет событий.",
    noActiveInvites: "Нет активных приглашений.",
    openAction: "Открыть",
    filters: {
      all: "Все",
      master: "Мастер",
      studio: "Студия",
      system: "Система",
      invites: "Приглашения",
    },
    channels: {
      master: "Мастер",
      studio: "Студия",
      system: "Система",
    },
    invites: {
      titlePrefix: "Админ студии",
      titleSuffix: "приглашает вас стать мастером",
      accept: "Принять",
      reject: "Отклонить",
      accepting: "Принимаем...",
      rejecting: "Отклоняем...",
      studioProfile: "Профиль студии",
      actionFailed: "Не удалось выполнить действие",
      networkError: "Сеть недоступна или сервер не отвечает",
    },
  },
  feed: {
    aiSearchPlaceholder: "✨ Придумай образ: \"Свадебный макияж для зеленых глаз...\"",
    title: "Витрина вдохновения",
    subtitle: "Найдите идею и запишитесь на результат",
    searchPlaceholder: "Поиск, например «Свадебный макияж»",
    categoryNails: "💅 Ногти",
    categoryHair: "💇‍♀️ Волосы",
    categoryBrowsLashes: "👁️ Брови/Ресницы",
    categoryMakeup: "💄 Мейк",
    categoryBody: "💆‍♀️ Тело",
    tagTrends: "Тренды 2024",
    tagNude: "Нюд",
    tagGradient: "Градиент",
    tagNearby: "Рядом со мной",
    categories: {
      nails: "💅 Ногти",
      hair: "💇‍♀️ Волосы",
      browsLashes: "👁️ Брови/Ресницы",
      makeup: "💄 Мейк",
      body: "💆‍♀️ Тело",
    },
    tags: {
      trends: "Тренды 2024",
      nude: "Нюд",
      gradient: "Градиент",
      nearby: "Рядом со мной",
    },
    bookNow: "Записаться",
    bookThisService: "Записаться на эту услугу",
    addToFavorites: "Добавить в избранное",
    removeFromFavorites: "Убрать из избранного",
    similarWorks: "Похожие работы",
    nearestSlots: "Ближайшие окна",
    total: "Итого",
    whatOnPhoto: "Что на фото",
    showMore: "Показать ещё",
    emptyFeed: "Пока нет работ",
    emptyTitle: "Пока нет работ",
    emptyDesc: "Добавьте первые работы в портфолио мастера.",
    retry: "Повторить",
    loading: "Загрузка ленты…",
    loadFailed: "Не удалось загрузить ленту",
    detailsFailed: "Не удалось загрузить детали работы",
    noSlots: "Нет данных по ближайшим окнам",
    byMaster: "Мастер",
    byStudio: "Студия",
  },
  home: {
    filters: {
      categoriesTitle: "Что ищем?",
      tagsTitle: "Какой стиль?",
    },
    loading: "Загрузка ленты…",
    loadFailed: "Не удалось загрузить ленту",
    empty: "Пока нет работ",
    detailsFailed: "Не удалось загрузить работу",
    bookService: "Записаться на услугу",
    goToMaster: "К мастеру",
  },
  catalog: {
    capsule: {
      servicePlaceholder: "Услуга",
      districtPlaceholder: "Район",
      datePlaceholder: "Дата",
      find: "Найти",
    },
    timeSearch: {
      title: "Дата и время",
      morning: "Утро",
      day: "День",
      evening: "Вечер",
      custom: "Свой диапазон",
      from: "С",
      to: "По",
      freeInTime: "Свободно в выбранное время",
      selectServiceFirst: "Сначала выберите услугу",
      selectDateFirst: "Сначала выберите дату",
      emptyTitle: "Нет свободных окон",
      emptyDesc: "Попробуйте другой диапазон времени или дату.",
      loadFailed: "Не удалось подобрать свободные окна",
      noServices: "Ничего не найдено",
    },
    chips: {
      price: "Цена",
      availableToday: "Свободно сегодня",
      rating45plus: "⭐ 4.5+",
        hot: "Горящее",
      studios: "Студии",
      privateMasters: "Частные мастера",
      priceMinPlaceholder: "Мин",
      priceMaxPlaceholder: "Макс",
      apply: "Применить",
      reset: "Сбросить",
    },
    resultsCount: "Результатов",
    viewList: "Список",
    viewMap: "На карте",
    priceFrom: "от",
    priceAllIncluded: "всё включено",
    priceOnRequest: "Цена по запросу",
    noSlots: "Нет мест",
    nextSlotLabel: "Ближайший слот",
    todaySlotsLabel: "Окна сегодня",
    reviewsLabel: "отзывов",
    newLabel: "New",
    mapPlaceholderTitle: "Карта будет здесь",
    mapPlaceholderDesc: "Подключим интерактивную карту в следующем шаге.",
    mapPointsTitle: "Точки на карте",
    carouselPrev: "Предыдущее фото",
    carouselNext: "Следующее фото",
    loadMore: "Показать ещё",
    loading: "Загружаем каталог...",
    loadFailed: "Не удалось загрузить каталог",
    emptyTitle: "Ничего не найдено",
    emptyDesc: "Попробуйте изменить фильтры или запрос.",
    retry: "Повторить",
  },
  master: {
    notifications: {
      title: "Центр уведомлений",
      subtitle: "Приглашения и события по вашему кабинету",
      timelineTitle: "Лента событий",
      timelineSoon: "Лента событий будет обновлена на следующем шаге.",
      filterAll: "Все",
      filterBookings: "Записи",
      filterSystem: "Система",
      bookingCreatedLabel: "Новая запись",
      bookingCancelledLabel: "Отмена записи",
      bookingRescheduledLabel: "Перенос записи",
      systemLabel: "Системное уведомление",
      newBadge: "Новое",
      publishHotWindow: "Опубликовать как «Горящее окно»",
      hotWindowUnavailable: "Публикация «горящего окна» пока недоступна",
      markAllRead: "Отметить всё прочитанным",
      actionFailed: "Не удалось выполнить действие",
      networkError: "Сеть недоступна или сервер не отвечает",
      accepting: "Принимаем...",
      declining: "Отклоняем...",
      accept: "Принять",
      decline: "Отклонить",
      viewStudioProfile: "Посмотреть профиль студии",
    },
    invites: {
      pinnedTitle: "Новые приглашения",
      emptyTitle: "Вас пока никуда не пригласили…",
      emptyDesc: "Заполните профиль, чтобы студии вас замечали",
      fillProfile: "Заполнить профиль",
      phoneRequired: "Укажите номер телефона в профиле, чтобы получать приглашения.",
    },
    platform: {
      title: "Новости платформы",
      soon: "Колонка новостей будет заполнена на следующем шаге.",
    },
    dashboard: {
      silentModeEnabled: "Режим тишины включён",
      bookingQuestionsTitle: "Вопросы клиента",
      referencePhotoAlt: "Фото-референс",
      answerPrefix: "•",
      errors: {
        loadDay: "Не удалось загрузить данные дня",
        loadSlots: "Не удалось загрузить свободные слоты",
        commentRequired: "Комментарий обязателен",
        updateStatus: "Не удалось обновить статус",
        createBooking: "Не удалось создать запись",
        createImage: "Не удалось создать изображение",
        saveStories: "Не удалось сохранить stories",
      },
      prompts: {
        rejectReason: "Причина отклонения",
      },
      labels: {
        noSlots: "Свободных слотов нет",
        dayTitle: "Мой день",
        daySubtitle: "Текущие записи и быстрые действия.",
        newBookings: "Новые",
        addBooking: "Добавить запись",
        addBookingDisabled: "Для студийного мастера пока недоступно",
        manualBookingButton: "Записать клиента вручную",
        todayOff: "Сегодня выходной",
        change: "Изменить",
        workingHoursToday: "Рабочее время сегодня: {start}–{end} • буфер {buffer} {minutes}",
        workingHoursNotSet: "Рабочее время не настроено",
        setup: "Настроить",
        silenceBadge: "🤫 Тишина",
        chat: "Чат",
        emptyBookingsTitle: "Пока нет записей",
        emptyBookingsDesc: "Проверьте график и настройте услуги.",
        balanceTitle: "Мой баланс (месяц)",
        balanceToggleAria: "Скрыть или показать баланс",
        nextSlotsTitle: "Ближайшие свободные слоты",
        refresh: "Обновить",
        refreshSlotsAria: "Обновить слоты",
        publishStories: "Опубликовать в Stories",
        slotsLoading: "Загрузка слотов...",
        notificationsTitle: "Уведомления (новые отзывы)",
        noReviews: "Пока отзывов нет.",
        slotsOnDate: "Окна на {date}",
        savedCardsTitle: "Сохраненные карточки",
      },
      stories: {
        brand: "МастерРядом",
        slotsTitle: "Свободные слоты · {date}",
        cardTitle: "Карточка {index}/{total}",
        saveToMedia: "Сохранить в медиа",
        download: "Скачать",
        previewTitle: "Предпросмотр Stories",
        cardAlt: "Карточка Stories",
      },
      manualBooking: {
        title: "Ручная запись",
        chooseService: "Выберите услугу",
        clientNamePlaceholder: "Имя клиента",
        phonePlaceholder: "Телефон",
        commentPlaceholder: "Комментарий",
        create: "Создать",
      },
      status: {
        confirmed: "Подтверждено",
        rejected: "Отклонено",
      },
      actions: {
        confirm: "Подтвердить",
        reject: "Отклонить",
        confirmMove: "Подтвердить перенос",
        rejectMove: "Отклонить перенос",
        requestMove: "Запросить перенос",
      },
    },
    profile: {
      headerTitle: "Профиль",
      headerSubtitle: "О себе, услугах и портфолио.",
      tabs: {
        main: "Основное",
        services: "Услуги и прайс",
        portfolio: "Портфолио",
        settings: "Настройки",
      },
      errors: {
        saveAddress: "Не удалось сохранить адрес. Попробуйте ещё раз.",
        loadProfile: "Не удалось загрузить профиль",
        loadBookingConfig: "Не удалось загрузить настройки записи.",
        deleteCabinet: "Не удалось удалить кабинет мастера.",
        updateSettings: "Не удалось обновить настройки",
        updateReminders: "Не удалось обновить напоминания",
        invalidCancellationHours: "Укажите значение от 0 до 168.",
        updateCancellationDeadline: "Не удалось обновить срок отмены",
        saveServices: "Не удалось сохранить услуги",
        displayNameRequired: "Укажите имя",
        addServiceTitleRequired: "Укажите название",
        addServicePriceRequired: "Укажите цену",
        addServiceDurationRequired: "Выберите длительность",
        priceTooLow: "Введите цену больше 0.",
        loadAvatar: "Не удалось загрузить аватар",
        deleteAvatar: "Не удалось удалить аватар",
        portfolioLimitReached: "Достигнут лимит портфолио. Удалите фото или обновите тариф.",
        uploadPhoto: "Не удалось загрузить фото",
        savePhotoDescription: "Не удалось сохранить описание фото",
        removePhoto: "Не удалось удалить фото из портфолио",
        replacePhoto: "Не удалось заменить фото",
        saveFailed: "Не удалось сохранить",
        apiErrorPrefix: "Ошибка:",
      },
      autosave: {
        saving: "Сохраняем...",
        savedAuto: "Сохранено автоматически",
      },
      onlinePayments: {
        proRequired: "Онлайн-оплата доступна на PRO и выше.",
        disabledByAdmin: "Функция временно отключена администрацией",
      },
      preview: {
        nameFallback: "Имя мастера",
        taglineFallback: "Добавьте короткий слоган",
        addressFallback: "Адрес пока не указан",
        bioFallback: "Добавьте описание, чтобы клиенты лучше узнали о вас.",
        addressLabel: "Адрес",
        reviewsLabel: "отзывов",
        published: "Профиль опубликован",
        unpublished: "Не опубликован",
        openAsClient: "Посмотреть как клиент",
        title: "Предпросмотр витрины",
      },
      loading: "Загрузка профиля...",
      invite: {
        title: "Приглашение в студию",
        description: "Примите или отклоните приглашение, чтобы начать работать в студии.",
      },
      sections: {
        profileShowcaseTitle: "Профиль и витрина",
        profileShowcaseDesc: "То, что видят клиенты в поиске и на витрине.",
        settingsTitle: "Настройки",
        settingsDesc: "Автоматизация и внешние каналы уведомлений.",
        servicesTitle: "Услуги и прайс",
        servicesDesc: "Управляйте стоимостью, длительностью и доступностью услуг.",
        portfolioTitle: "Портфолио",
        portfolioDesc: "Добавляйте работы и связывайте их с услугами.",
      },
      publication: {
        title: "Публикация профиля",
        desc: "Без публикации профиль не отображается в поиске и витрине.",
        publishAction: "Опубликовать профиль",
      },
      automation: {
        title: "Автоматизация",
        desc: "Настройки подтверждения записей.",
        autoConfirmTitle: "Автоподтверждение записи",
        autoConfirmDesc: "Если включено, новые записи будут подтверждаться автоматически.",
      },
      reminders: {
        title: "Напоминания",
        desc: "Отправлять клиенту и мастеру напоминания о записи.",
        label: "Напоминания о записи",
        hint: "Можно отключить, если не нужны уведомления за 24 часа и 2 часа.",
      },
      cancellation: {
        title: "Политика отмены",
        desc:
          "Клиент может отменить запись не позднее указанного срока. Пустое значение — без ограничений, 0 — отмена запрещена.",
        label: "Срок отмены (часы)",
        placeholder: "Например, 24",
        currentValue: "Текущее значение:",
        hoursShort: "ч.",
      },
      hotSlots: {
        title: "Горячие слоты",
        desc: "Подсветите свободные окна и получите больше записей.",
      },
      deleteCabinet: {
        title: "Удаление кабинета мастера",
        descMain:
          "Удаление кабинета мастера необратимо. Все услуги, расписание и портфолио будут удалены.",
        descLegal:
          "История завершённых записей сохраняется в обезличенном виде согласно требованиям законодательства.",
        action: "Удалить",
      },
      services: {
        newServiceTitle: "Новая услуга",
        hide: "Скрыть",
        globalCategoryLabel: "Глобальная категория",
        selectCategory: "Выберите категорию",
        selectCategoryHint: "Выберите категорию, чтобы услуга отображалась на сайте.",
        serviceTitleLabel: "Название услуги",
        serviceTitlePlaceholder: "Название",
        priceLabel: "Цена",
        durationLabel: "Длительность",
        durationUnit: "мин",
        addService: "Добавить услугу",
        selectStudioService: "Выберите услугу из каталога студии",
        add: "Добавить",
        columnTitle: "Название услуги",
        columnPrice: "Цена",
        columnDuration: "Длительность",
        columnEnabled: "Вкл.",
        priceManagedHint: "Цена управляется студией, доступен только тайминг.",
        onlinePaymentsLabel: "Онлайн-оплата",
        addServiceCta: "+ Добавить услугу",
      },
      bookingConfig: {
        title: "Настройки записи",
        open: "Настройки записи",
        loading: "Загружаем настройки записи...",
        referencePhotoRequiredLabel: "Нужен фото-референс для записи.",
        questionsTitle: "Вопросы для клиента",
        addQuestion: "+ Добавить вопрос",
        empty: "Вопросов пока нет.",
        questionLabel: "Вопрос",
        questionPlaceholder: "Введите вопрос",
        moveUp: "↑",
        moveDown: "↓",
        remove: "Удалить",
        required: "Обязательный",
      },
      portfolio: {
        limitReached: "Лимит достигнут.",
        plans: "Тарифы",
        dropTitle: "Перетащите фото сюда",
        dropSubtitle: "или нажмите, чтобы выбрать файл",
        uploadingSuffix: "— загружаем...",
        draftLabel: "Черновик загрузки",
        draftAlt: "Черновик фото",
        addDescription: "Добавить описание",
        photoUnavailable: "Фото недоступно",
        photoAlt: "Фото из портфолио",
        replace: "Заменить",
        remove: "Удалить",
        linkedServices: "Привязано к услугам",
      },
      portfolioMeta: {
        modalTitle: "Предпросмотр витрины",
        photoDescriptionTitle: "Описание фото",
        captionPlaceholder: "Подпись (необязательно)",
        serviceHint: "Какая это услуга? (необязательно)",
      },
      status: {
        savedChanges: "✓ Изменения сохранены",
      },
      form: {
        nameLabel: "Имя",
        namePlaceholder: "Имя",
        taglineLabel: "Тэглайн",
        taglinePlaceholder: "Например, свадебный макияж",
        addressLabel: "Адрес",
        addressPlaceholder: "Адрес приёма",
        bioLabel: "Описание",
        bioPlaceholder: "О себе",
        selectAddressAria: "Выбрать адрес",
        replaceAvatarAction: "Заменить фото",
        removeAvatarAction: "Удалить фото",
        replaceAvatarAria: "Заменить аватар",
        removeAvatarAria: "Удалить аватар",
      },
    },
    clients: {
      title: "Клиенты",
      subtitle: "База клиентов по вашим записям",
    },
    reviews: {
      title: "Отзывы",
      subtitle: "Оценки и комментарии клиентов, отсортированные прямо в кабинете.",
    },
  },
  admin: {
    media: {
      siteLogoTitle: "Логотип сайта",
      siteLogoDescription: "Используется в navbar рядом с МастерРядом.",
      loginHeroTitle: "Фото для страницы входа",
      loginHeroDescription: "Большое изображение в левой части страницы /login.",
      uploadImage: "Загрузить изображение",
      replaceImage: "Заменить изображение",
      removeImage: "Удалить изображение",
      emptyImage: "Изображение не загружено",
      uploadFailed: "Не удалось загрузить изображение",
      deleteFailed: "Не удалось удалить изображение",
      loadFailed: "Не удалось загрузить настройки изображения",
    },
  },
  media: {
    avatar: {
      noAvatar: "Нет фото",
      alt: "Фото профиля",
      upload: "Загрузить фото",
      replace: "Изменить фото",
      remove: "Удалить фото",
      loadFailed: "Не удалось загрузить фото",
      uploadFailed: "Не удалось загрузить фото",
      deleteFailed: "Не удалось удалить фото",
    },
  },
  clientCabinet: {
    shell: {
      title: "Кабинет клиента",
      profileSubtitle: "Личные данные и настройки.",
      bookingsSubtitle: "Ваши предстоящие и прошлые записи.",
    },
    settings: {
      title: "Настройки",
      subtitle: "Общее управление профилем и данными.",
    },
    common: {
      profile: "Профиль",
      myBookings: "Мои записи",
      save: "Сохранить",
      phone: "Телефон",
      error: "Ошибка",
    },
    telegram: {
      title: "Уведомления в Telegram",
      connected: "Подключено",
      notConnected: "Не подключено",
      enabled: "Уведомления включены",
      disabled: "Уведомления выключены",
      hint: "Если бот перестал писать — откройте чат с ботом и нажмите Start.",
      connectButton: "Подключить",
      loadFailed: "Не удалось загрузить статус Telegram",
      linkFailed: "Не удалось получить ссылку Telegram",
      settingsFailed: "Не удалось обновить настройки",
      unknownError: "Неизвестная ошибка",
    },
    vk: {
      title: "Уведомления в VK",
      connected: "Подключено",
      notConnected: "Не подключено",
      enabled: "Уведомления включены",
      disabled: "Уведомления выключены",
      hint: "Если уведомления не приходят, переподключите VK.",
      connectButton: "Подключить",
      disconnectButton: "Отключить VK",
      loadFailed: "Не удалось загрузить статус VK",
      linkFailed: "Не удалось подключить VK",
      settingsFailed: "Не удалось обновить настройки",
      unknownError: "Неизвестная ошибка",
    },
    booking: {
      pending: "Ожидает",
      confirmed: "Подтверждено",
      cancelled: "Отменено",
      chooseDate: "Выберите дату",
      chooseTime: "Выберите время",
      noSlots: "Нет доступных слотов",
      loadSlotsFailed: "Не удалось загрузить слоты",
      submitFailed: "Не удалось отправить запись",
      chooseCorrectSlot: "Выберите корректный слот",
      morning: "Утро",
      day: "День",
      evening: "Вечер",
      moveBooking: "Перенести запись",
      moveBookingHint: "Выберите новую дату и слот.",
      moveConfirm: "Подтвердить перенос",
      moving: "Переносим...",
    },
    bookingsPanel: {
      loading: "Загружаем записи",
      empty: "Записей пока нет.",
      apiErrorPrefix: "Ошибка API:",
      unknownError: "Неизвестная ошибка",
      failedToLoad: "Не удалось загрузить записи",
      failedToCancel: "Не удалось отменить запись",
      reschedule: "Перенести",
      cancelBooking: "Отменить запись",
      leaveReview: "Оставить отзыв",
    },
    profile: {
      subtitle: "Личные данные и контактная информация",
      saveFailed: "Не удалось сохранить",
      networkError: "Сеть недоступна или сервер не отвечает",
      saved: "Сохранено",
      createMasterFailed: "Не удалось создать профиль мастера",
      masterCreated: "Профиль мастера создан",
      createStudioFailed: "Не удалось создать студию",
      studioCreated: "Студия создана",
      description: "О себе, услугах и портфолио",
      professionalRolesTitle: "Мои профессиональные роли",
      rolesAddedCanAddMore:
        "Вы уже добавили профессиональные роли. Можно добавить еще.",
      stillClientAddRole:
        "Вы пока клиент. Добавьте роль мастера или студии.",
      alreadyMaster: "Вы уже мастер",
      becomeMaster: "Стать мастером",
      creatingMaster: "Создаем профиль мастера...",
      alreadyStudioOwner: "Вы уже владелец студии",
      createStudio: "Создать студию",
      creatingStudio: "Создаем студию...",
      lastName: "Фамилия",
      lastNamePlaceholder: "Иванов",
      firstName: "Имя",
      firstNamePlaceholder: "Иван",
      middleName: "Отчество",
      middleNamePlaceholder: "Иванович",
      displayName: "Отображаемое имя",
      displayNamePlaceholder: "Как вас показывать в интерфейсе",
      email: "Почта",
      birthDate: "Дата рождения",
      address: "Адрес",
      addressPlaceholder: "Город, улица, дом...",
      mapHint:
        "Позже добавим кнопку \"Показать на карте\" и будем сохранять координаты.",
      rolesLabel: "Роли:",
      saving: "Сохранение...",
      profileSectionTitle: "Личные данные",
      profileSectionSubtitle: "Основная информация, которая отображается в вашем профиле.",
      integrationsTitle: "Подключенные аккаунты",
      integrationsSubtitle: "Управляйте внешними каналами уведомлений.",
      securityTitle: "Безопасность",
      securitySubtitle: "Контроль доступа и действия с аккаунтом.",
      securityHint: "Проверяйте подключенные каналы и номер телефона для входа.",
      phonePlaceholder: "+7XXXXXXXXXX",
      emailPlaceholder: "mail@example.com",
    },
  },
  publicProfile: {
    page: {
      loading: "Загружаем профиль мастера...",
      redirecting: "Открываем страницу студии...",
      loadFailedTitle: "Не удалось открыть профиль",
      notFound: "Профиль не найден",
      categoriesTitle: "Категории",
      studioBookingTitle: "Запись через студию",
      studioBookingDescription: "Этот мастер принимает записи через студийный календарь.",
      studioBookingCta: "Открыть запись в студии",
      unknownError: "Неизвестная ошибка",
    },
    hero: {
      share: "Поделиться",
      favorite: "В избранное",
      address: "Адрес",
      novice: "⭐ Новичок",
      shareSuccess: "Ссылка скопирована",
      shareFailed: "Не удалось поделиться",
    },
    services: {
      title: "Услуги",
      add: "+ Добавить",
      remove: "Удалить",
      priceOnRequest: "Цена по запросу",
    },
    portfolio: {
      title: "Портфолио",
      empty: "Пока нет работ",
      viewError: "Не удалось загрузить работу",
      untitledWork: "Работа мастера",
    },
    reviews: {
      title: "Отзывы",
      all: "Все отзывы",
      leaveReview: "Оставить отзыв",
      noReviews: "Пока нет отзывов",
      loadFailed: "Не удалось загрузить отзывы",
    },
    booking: {
      title: "Запись",
      emptyTitle: "Выберите услуги слева, чтобы записаться",
      emptyDesc: "Добавьте хотя бы одну услугу, и мы покажем итог и ближайшие слоты.",
      chooseTime: "Выбрать время",
      backToCart: "Назад к корзине",
      continueToConfirm: "Продолжить",
      confirm: "Подтвердить запись",
      comment: "Комментарий",
      commentPlaceholder: "Например: буду на 5 минут раньше",
      bookingOnPhone: "Запись на номер",
      authRequiredTitle: "Чтобы завершить запись, войдите по номеру телефона",
      authRequiredHint: "Телефон понадобится для подтверждения и связи по записи.",
      phoneLabel: "Телефон",
      phonePlaceholder: "+77001234567",
      loginAndContinue: "Войти и продолжить",
      success: "Запись успешно создана",
      submitFailed: "Не удалось создать запись. Попробуйте ещё раз.",
      bookingConfigLoading: "Загружаем настройки записи...",
      bookingConfigTitle: "Вопросы для клиента",
      referencePhotoLabel: "Фото-референс",
      referencePhotoUploading: "Загружаем фото...",
      referencePhotoAlt: "Фото-референс",
      bookingAnswerPlaceholder: "Ваш ответ",
      bookingConfigLoadFailed: "Не удалось загрузить требования записи.",
      referencePhotoRequired: "Нужен фото-референс для записи.",
      requiredQuestions: "Ответьте на обязательные вопросы.",
      silentModeAria: "Хочу помолчать",
      silentModeTitle: "Хочу помолчать 🤫",
      silentModeDesc: "Мастер поздоровается, уточнит детали и дальше будет работать без разговоров.",
      clientFallbackName: "Клиент",
      total: "ИТОГО",
      duration: "ВРЕМЯ",
    },
    slots: {
      loadingSlots: "Загружаем слоты...",
      noSlots: "На ближайшие дни всё занято.",
      refresh: "Обновить",
      showMoreWeek: "Показать ещё неделю",
      allBusy: "Всё занято",
      nextWeek: "Следующая неделя",
      prevWeek: "Предыдущая неделя",
      chooseDay: "Выберите день",
      chooseSlot: "Выберите время",
      noSlotsForDay: "На выбранный день свободных окон нет.",
      loadFailed: "Не удалось загрузить свободные окна. Попробуйте ещё раз.",
      slotTaken: "Окошко уже заняли, выберите другое.",
    },
  },
  studioCabinet: {
    layout: {
      studioFallbackName: "Студия",
      publicUsernameHint: "Задайте публичный username, чтобы получить ссылку",
    },
    teamTabs: {
      all: "Все мастера",
      workingToday: "Работают сегодня",
    },
    teamPage: {
      title: "Команда студии",
      subtitle: "Управляйте мастерами и расписанием смен.",
      statusFree: "🟢 Свободен",
      shiftTemplate: "Смена {start}–{end}",
      bookingsInfoTemplate: "Записей: {count} • Следующее окно {time}",
      emptyActiveShifts: "Сегодня нет активных смен.",
    },
    teamAdd: {
      title: "Добавить мастера",
      subtitle: "Форма добавления будет доступна в следующем шаге.",
      info: "Пока можно перейти в Команду и управлять существующими мастерами.",
      back: "Вернуться в Команду",
    },
    teamCard: {
      viewSchedule: "Посмотреть расписание",
    },
    settings: {
      sidebarTitle: "Настройки",
      profile: "Профиль студии",
      services: "Услуги и прайс",
      portfolio: "Портфолио",
    },
    nav: {
      home: "Главная",
      calendar: "Календарь",
      team: "Команда",
      clients: "Клиенты",
      analytics: "Аналитика",
      finance: "Финансы",
      billing: "Подписка",
      settingsAria: "Настройки",
    },
    dashboard: {
      title: "Главная",
      subtitle: "Ключевые показатели студии на сегодня.",
      emptyHint: "Данные появятся после первых записей",
      cards: {
        bookingsToday: "Записи сегодня",
        mastersOnShift: "Мастера в смене",
        newClients: "Новые клиенты",
        reviews: "Отзывы",
      },
      bookingsAmountPrefix: "На {amount}",
      mastersWorking: "Работают сегодня",
      newClientsWindow: "За последние 24 ч",
      reviewsWindow: "За последние 7 дней",
      reviewsValue: "{count} новых",
      mastersCountTemplate: "{working} из {total}",
      plural: {
        booking: {
          one: "запись",
          few: "записи",
          many: "записей",
        },
        client: {
          one: "клиент",
          few: "клиента",
          many: "клиентов",
        },
      },
    },
    calendar: {
      title: "Календарь",
      subtitle: "Записи и блоки студии в одном месте.",
      day: "День",
      week: "Неделя",
      month: "Месяц",
      searchPlaceholder: "Поиск клиента, телефона или услуги",
      allMasters: "Все мастера",
      allCategories: "Все категории",
      allServices: "Все услуги",
      allStatuses: "Все статусы",
      loading: "Загрузка календаря...",
      noMasters: "Нет мастеров",
      noMastersHint: "Сначала добавьте мастеров в команду.",
      goToTeam: "К команде",
      blocksLabel: "Блоки",
      noItemsForDay: "На этот день событий нет.",
      dayDetails: "Детали дня",
      timeNotSet: "Время не указано",
      loadFailed: "Не удалось загрузить календарь",
      apiErrorPrefix: "Ошибка API",
      weekdays: {
        mon: "Пн",
        tue: "Вт",
        wed: "Ср",
        thu: "Чт",
        fri: "Пт",
        sat: "Сб",
        sun: "Вс",
      },
    },
    clientsPage: {
      title: "Клиенты",
      subtitle: "База клиентов студии",
    },
    financePage: {
      title: "Финансы",
      subtitle: "Отчёты и показатели студии",
    },
    profile: {
      loading: "Загрузка профиля студии...",
      sectionTitle: "Профиль студии",
      portfolioTitle: "Портфолио",
      profileSaved: "Профиль сохранен",
      bannerSaved: "Баннер сохранен",
      bannerUploaded: "Баннер загружен",
      loadFailed: "Не удалось загрузить профиль студии",
      saveFailed: "Не удалось сохранить профиль студии",
      saveBannerFailed: "Не удалось сохранить баннер",
      uploadBannerFailed: "Не удалось загрузить баннер",
      apiErrorPrefix: "Ошибка API",
      nameLabel: "Название",
      descriptionLabel: "Описание",
      addressLabel: "Адрес",
      phoneLabel: "Телефон",
      emailLabel: "Email",
      telegramLabel: "Telegram",
      instagramLabel: "Instagram",
      vkLabel: "VK",
      namePlaceholder: "Название студии",
      taglinePlaceholder: "Слоган",
      addressPlaceholder: "Город, улица, дом",
      districtPlaceholder: "Район",
      contactNamePlaceholder: "Контактное лицо",
      contactPhonePlaceholder: "Контактный телефон",
      contactEmailPlaceholder: "Контактный email",
      phonePlaceholder: "+7 700 000 00 00",
      emailPlaceholder: "studio@email.com",
      telegramPlaceholder: "@studio",
      instagramPlaceholder: "@studio",
      vkPlaceholder: "vk.com/studio",
      categoriesPlaceholder: "Категории (через запятую)",
      descriptionPlaceholder: "Расскажите о студии",
      published: "Опубликовано",
      saveProfile: "Сохранить профиль",
      saving: "Сохраняем...",
      selectAddressAria: "Выбрать адрес {address}",
      avatarTitle: "Аватар",
      avatarHint: "Главное фото студии для каталога и профиля.",
      bannerTitle: "Баннер",
      bannerHint: "Широкая обложка для публичной страницы.",
      noBanner: "Баннер не выбран",
      bannerPlaceholder: "Обложка студии",
      uploadBanner: "Загрузить баннер",
      clearBanner: "Убрать баннер",
      changeBanner: "Изменить обложку",
      focalPoint: "Точка фокуса",
      studioBannerAlt: "Баннер студии",
      useAsBannerAria: "Использовать как баннер",
    },
    routes: {
      servicesTitle: "Услуги",
      servicesSubtitle: "Прайс, категории и назначение мастеров.",
      teamTitle: "Команда",
      teamSubtitle: "Добавляйте мастеров и отслеживайте их статусы.",
      clientsTitle: "Клиенты",
      clientsSubtitle: "Список клиентов из записей студии.",
      financeTitle: "Финансы",
      financeSubtitle: "Выручка и посещения по данным бронирований.",
    },
    services: {
      loading: "Загрузка услуг...",
      summary: "Категории: {categories} / Услуги: {services}",
      createCategory: "Создать категорию",
      addService: "Добавить услугу",
      noServicesTitle: "Пока нет услуг",
      noServicesDescription: "Создайте первую категорию и услугу, чтобы начать принимать записи.",
      selectMaster: "Выберите мастера",
      assignMaster: "Назначить",
      durationMin: "мин",
      currency: "₽",
      visibleInSearch: "Виден в поиске",
      visibleInSearchHint: "Если включено, услуга отображается в каталоге и поиске.",
      createCategoryTitle: "Новая категория",
      categoryTitlePlaceholder: "Название категории",
      createServiceTitle: "Новая услуга",
      selectCategory: "Выберите категорию",
      serviceTitlePlaceholder: "Название услуги",
      pricePlaceholder: "Цена",
      durationPlaceholder: "Длительность (мин)",
      cancel: "Отмена",
      save: "Сохранить",
      creating: "Сохраняем...",
      loadFailed: "Не удалось загрузить услуги",
      assignFailed: "Не удалось назначить мастера",
      createCategoryFailed: "Не удалось создать категорию",
      createServiceFailed: "Не удалось создать услугу",
      apiErrorPrefix: "Ошибка API",
    },
    team: {
      loading: "Загрузка команды...",
      mastersCount: "Мастеров: {count}",
      addMaster: "Добавить мастера",
      noMastersTitle: "Пока нет мастеров",
      noMastersDescription: "Добавьте первого мастера, чтобы начать заполнять расписание.",
      pending: "Ожидает подтверждения",
      active: "Активен",
      addMasterTitle: "Новый мастер",
      masterNamePlaceholder: "Имя мастера",
      phonePlaceholder: "Телефон: +7XXXXXXXXXX или 8XXXXXXXXXX",
      titlePlaceholder: "Должность",
      cancel: "Отмена",
      save: "Сохранить",
      creating: "Сохраняем...",
      requiredError: "Имя, телефон и должность обязательны. Формат телефона: +7XXXXXXXXXX или 8XXXXXXXXXX.",
      loadFailed: "Не удалось загрузить мастеров",
      createFailed: "Не удалось добавить мастера",
      apiErrorPrefix: "Ошибка API",
    },
    clients: {
      loading: "Загрузка клиентов...",
      empty: "Пока нет клиентов. Список формируется из записей.",
        loadFailed: "Не удалось загрузить клиентов",
        apiErrorPrefix: "Ошибка API",
        moneySuffix: "₽",
      columns: {
        client: "Клиент",
        phone: "Телефон",
        lastBooking: "Последняя запись",
        service: "Услуга",
        visits: "Посещения",
        amount: "Сумма",
      },
    },
    finance: {
      from: "С",
      to: "По",
      groupBy: "Группировка",
      summary: {
        today: "Сегодня",
        last7Days: "Последние 7 дней",
        last30Days: "Последние 30 дней",
      },
      summaryLoading: "Загрузка сводки...",
      summaryLoadFailed: "Не удалось загрузить сводку по финансам",
      recentTitle: "Последние записи",
      recentEmpty: "Пока нет записей за выбранный период.",
      recentColumns: {
        client: "Клиент",
        master: "Мастер",
        date: "Дата",
        amount: "Сумма",
      },
      loading: "Загрузка финансовой аналитики...",
      loadFailed: "Не удалось загрузить финансовую аналитику",
      apiErrorPrefix: "Ошибка API",
      groupMasters: "Мастера",
      groupCategories: "Категории",
      groupServices: "Услуги",
      columnEntity: "Срез",
      columnVisits: "Посещения",
      columnSum: "Сумма",
      noRecords: "За выбранный период записей нет.",
      total: "Итого",
      moneySuffix: "₽",
    },
  },
  publicStudio: {
    heroBook: "Записаться онлайн",
    teamTitle: "Мастера студии",
    teamSubtitle: "Выберите мастера и посмотрите его работы",
    servicesTitle: "Услуги",
    servicesSubtitle: "Выберите услугу и добавьте её в запись",
    reviewsTitle: "Отзывы",
    reviewsSubtitle: "Последние отзывы клиентов",
    chooseService: "Выберите услугу",
    chooseMaster: "Выберите мастера",
    chooseDate: "Выберите дату",
    anyMaster: "Любой мастер",
    total: "Итого",
    book: "Записаться",
    openBookingFlow: "Открыть запись",
    galleryFallback: "Фотографии студии",
    noMasters: "Пока нет доступных мастеров",
    gradeTop: "Топ",
    gradePro: "Pro",
    gradeNew: "New",
    noPortfolio: "Портфолио появится скоро",
    openMaster: "Открыть профиль",
    loadingStudio: "Загружаем студию…",
    loadingProfile: "Загружаем страницу студии...",
    loadFailedTitle: "Не удалось открыть страницу студии",
    notFound: "Студия не найдена",
    photosTitle: "Фотографии студии",
    photosSubtitle: "Интерьер, команда и атмосфера",
    leaveReview: "Оставить отзыв",
    noReviews: "Пока нет отзывов",
    typeStudio: "Студия",
    availableToday: "Свободно сегодня",
    noCategories: "Без категорий",
    studioOnlyProfileError: "Профиль доступен только для студии",
    from: "от",
    fallbackValue: "—",
    loadingMasters: "Подбираем мастеров…",
    loadingSlots: "Подбираем свободные окна…",
    noSlots: "На выбранную дату свободных окон нет.",
    noMastersWithService: "По выбранной услуге пока нет доступных мастеров.",
    selectServiceFirst: "Сначала выберите услугу",
    selectMasterFirst: "Сначала выберите мастера",
    selectSlotFirst: "Выберите удобное время",
    selectedDate: "Дата",
    selectedTime: "Время",
    bookingError: "Не удалось создать запись. Попробуйте ещё раз.",
    bookingSuccess: "Запись создана",
    authRequiredTitle: "Чтобы завершить запись, войдите в аккаунт",
    authRequiredText: "Авторизация нужна только на финальном подтверждении записи.",
    login: "Войти",
    addService: "＋",
    servicePriceOnRequest: "Цена по запросу",
    allServices: "Все услуги",
    noServices: "Услуги пока не добавлены",
    goToBooking: "К записи",
    sectionPhotos: "Фотографии студии",
    sectionPhotosSubtitle: "Интерьер, команда и атмосфера",
    sectionReviews: "Отзывы",
    sectionReviewsSubtitle: "Последние отзывы клиентов",
    reviewLeave: "Оставить отзыв",
    reviewEmpty: "Пока нет отзывов",
    reviewsCountLabel: "отзывов",
  },
  pages: {
    models: {
      title: "Предложения для моделей | МастерРядом",
      description:
        "Бесплатные и льготные процедуры для моделей от мастеров красоты. Стрижки, окрашивание, маникюр и другие услуги.",
      brand: "МастерРядом",
      heading: "Предложения для моделей",
      lead:
        "Подберите актуальные офферы от мастеров красоты и откликнитесь на подходящий слот.",
      cityLabel: "Город",
      cityPlaceholder: "Введите город",
      categoryLabel: "Категория",
      categoryAll: "Все категории",
      submit: "Показать",
      empty:
        "Пока нет активных предложений. Попробуйте выбрать другой город или категорию.",
      cityFallback: "Город не указан",
      categoryFallback: "Категория не указана",
      priceFree: "Бесплатно",
      applyAction: "Откликнуться →",
      paginationPrev: "Назад",
      paginationNext: "Вперёд",
    },
    about: {
      title: "О платформе — МастерРядом",
      description:
        "МастерРядом — маркетплейс мастеров красоты. Узнайте, как мы помогаем клиентам находить специалистов, а мастерам — управлять записями и развивать бизнес.",
      heroBadge: "О платформе",
      heroTitleMain: "Красота — без лишних",
      heroTitleHighlight: "сложностей",
      heroDescription:
        "МастерРядом — это маркетплейс, который соединяет клиентов с мастерами красоты. Мы решаем простую, но болезненную проблему: найти хорошего специалиста и записаться к нему — до сих пор та ещё задача.",
      problemTitle: "Какую проблему мы решаем",
      problemClientTitle: "Для клиентов",
      problemClientText:
        "Поиск мастера — это часами листать Instagram, писать в директ, ждать ответа, уточнять цену, узнавать свободные даты. Часть мастеров не отвечает вообще.",
      problemMasterTitle: "Для мастеров",
      problemMasterText:
        "Управление записями вручную — через мессенджеры, заметки и память — отнимает время, которое можно потратить на работу. Пропущенные записи, накладки, потерянные клиенты.",
      problemSummary:
        "МастерРядом закрывает оба конца: клиент видит реальное расписание и бронирует онлайн, мастер получает уведомление и ведёт всю базу в одном месте.",
      stats: [
        { value: "1 000+", label: "мастеров и студий" },
        { value: "50 000+", label: "бронирований" },
        { value: "20+", label: "городов" },
        { value: "4.9", label: "средний рейтинг" },
      ],
      valuesTitle: "Наши принципы",
      values: [
        {
          icon: "🎯",
          title: "Прозрачность",
          desc: "Реальные отзывы, честные цены и актуальное расписание без звонков и ожидания.",
        },
        {
          icon: "⚡",
          title: "Скорость",
          desc: "Запись за пару касаний. Без мессенджеров, без «напишите в директ».",
        },
        {
          icon: "🤝",
          title: "Партнёрство",
          desc: "Мы зарабатываем только тогда, когда зарабатывают мастера. Наш рост — общий.",
        },
        {
          icon: "🔒",
          title: "Надёжность",
          desc: "Данные клиентов и платежи защищены. Расписание всегда под рукой.",
        },
      ],
      ctaTitle: "Присоединяйтесь",
      ctaText: "Вы клиент — найдите мастера рядом. Вы мастер — попробуйте бесплатно.",
      ctaFindMaster: "Найти мастера",
      ctaBecomeMaster: "Стать мастером",
    },
    support: {
      title: "Поддержка — МастерРядом",
      description:
        "Создайте обращение в поддержку МастерРядом: сообщите об ошибке или предложите улучшение.",
      heroBadge: "Поддержка",
      heroTitle: "Напишите нам",
      heroSubtitle: "Нашли ошибку или есть идея? Расскажите — разберёмся и ответим.",
      faqTitle: "FAQ",
      faqDescription: "Ответы на частые вопросы",
      telegramTitle: "Telegram",
      telegramDescription: "Быстрый ответ в чате",
      formTitle: "Новое обращение",
      form: {
        errorTitleRequired: "Укажите заголовок обращения.",
        errorDescriptionRequired: "Опишите проблему подробнее (минимум 20 символов).",
        errorTooManyRequests: "Слишком часто. Попробуйте через несколько минут.",
        errorSendFailed: "Не удалось отправить обращение. Попробуйте позже.",
        errorSendNetwork:
          "Не удалось отправить обращение. Проверьте соединение и попробуйте снова.",
        successTitle: "Обращение отправлено",
        successDescription:
          "Мы получили ваше сообщение и ответим в ближайшее время. Контакт для ответа — из вашего профиля.",
        successAction: "Создать новое обращение",
        typeLabel: "Тип обращения",
        typeBugLabel: "🐛 Сообщить об ошибке",
        typeBugDesc: "Что-то работает не так",
        typeSuggestionLabel: "💡 Предложение",
        typeSuggestionDesc: "Идея по улучшению",
        titleLabel: "Заголовок",
        titlePlaceholderBug: "Например: не могу подтвердить запись",
        titlePlaceholderSuggestion: "Например: добавить фильтр по времени",
        descriptionLabel: "Описание",
        descriptionPlaceholderBug:
          "Опишите что происходит, на каком шаге возникает ошибка, какое устройство и браузер используете.",
        descriptionPlaceholderSuggestion:
          "Опишите идею подробно: зачем это нужно, как должно работать, кому поможет.",
        attachmentLabel: "Вложение",
        attachmentOptional: "(необязательно)",
        attachmentFileLabel: "📎 {fileName}",
        attachmentReplace: "Нажмите чтобы заменить",
        attachmentEmptyTitle: "Скриншот или запись экрана",
        attachmentEmptySubtitle: "PNG, JPG, GIF, MP4 — до 10 МБ",
        attachmentNote: "Файл пока не отправляется — передадим только имя.",
        privacyNote:
          "📌 При отправке обращения мы получим ваши контактные данные из профиля (имя и email или Telegram). Они используются только для ответа на ваш запрос.",
        responseNote: "Ответ придет по email.",
        submitSending: "Отправляем…",
        submit: "Отправить обращение",
      },
    },
    faq: {
      title: "Часто задаваемые вопросы — МастерРядом",
      description:
        "Ответы на самые популярные вопросы о МастерРядом: для клиентов, мастеров и студий.",
      heroBadge: "FAQ",
      heroTitle: "Часто задаваемые вопросы",
      heroSubtitlePrefix: "Не нашли ответ?",
      heroSubtitleLink: "Напишите нам",
      groups: [
        {
          group: "Для клиентов",
          items: [
            {
              q: "Нужно ли регистрироваться чтобы записаться?",
              a: "Нет. Чтобы записаться к мастеру, достаточно указать имя и номер телефона. Регистрация через Telegram или VK делает процесс удобнее — данные подставляются автоматически, а история записей сохраняется в личном кабинете.",
            },
            {
              q: "Как отменить или перенести запись?",
              a: "Откройте раздел «Мои записи» в личном кабинете. Там доступны кнопки отмены и переноса для каждой активной записи. Старайтесь отменять заблаговременно — мастер успеет освободить слот.",
            },
            {
              q: "Безопасно ли указывать номер телефона?",
              a: "Да. Ваш номер телефона передаётся только конкретному мастеру, к которому вы записались. Мы не передаём контактные данные третьим лицам и не используем их для рекламных рассылок.",
            },
            {
              q: "Что такое горячие слоты?",
              a: "Горячие слоты — срочные свободные окошки у мастеров, которые публикуются со скидкой (10–30%). Появляются в специальной ленте «Горячие предложения». Отлично подходят если хотите записаться быстро или сэкономить.",
            },
          ],
        },
        {
          group: "Для мастеров",
          items: [
            {
              q: "Сколько стоит размещение на МастерРядом?",
              a: "Базовый тариф FREE — бесплатно навсегда. Он включает профиль в каталоге, онлайн-запись, расписание и портфолио до 15 фотографий. Карта не нужна. PRO и Premium дают карту, горячие слоты, аналитику и приоритет в каталоге — от 990 ₽/мес.",
            },
            {
              q: "Как быстро появлюсь в каталоге после регистрации?",
              a: "Сразу после заполнения профиля и нажатия кнопки «Опубликовать». Процесс занимает несколько минут. Модерация не требуется — вы управляете публикацией самостоятельно.",
            },
            {
              q: "Могу ли я принимать оплату через МастерРядом?",
              a: "Да — на тарифе PRO и выше доступна онлайн-оплата через ЮKassa. Поддерживаются карты и СБП. Вы можете включать оплату отдельно для каждой услуги. Средства поступают на ваш счёт за вычетом комиссии платёжной системы.",
            },
            {
              q: "Что такое модельные офферы?",
              a: "Инструмент для поиска моделей на практику или пополнение портфолио. Вы публикуете оффер: описание, дата, цена (обычно сниженная). Желающие откликаются — вы выбираете подходящую кандидатуру и подтверждаете встречу.",
            },
            {
              q: "Можно ли подключить МастерРядом если я работаю в студии?",
              a: "Да. Работа в студии — отдельный режим. Владелец студии приглашает мастеров по номеру телефона. У каждого мастера свой кабинет, у владельца — общий календарь и финансовая отчётность.",
            },
          ],
        },
        {
          group: "Общие вопросы",
          items: [
            {
              q: "В каких городах работает МастерРядом?",
              a: "МастерРядом работает по всей России. Мастера могут указать любой город — клиенты ищут специалистов в своём городе или районе через фильтры каталога и карту.",
            },
          ],
        },
      ],
      contactTitle: "Остались вопросы?",
      contactSubtitle: "Напишите в поддержку — обычно отвечаем в течение нескольких часов.",
      contactPrimary: "Написать в поддержку",
      contactTelegram: "Telegram",
    },
    howItWorks: {
      title: "Как это работает — МастерРядом",
      description:
        "Узнайте как устроен МастерРядом: роли в системе, онлайн-запись, расписание, горячие слоты и другие возможности платформы.",
      heroBadge: "Как это работает",
      heroTitleMain: "Просто. Быстро.",
      heroTitleHighlight: "Без лишнего.",
      heroSubtitle: "В МастерРядом две роли — клиент и мастер. Вот как всё устроено для каждого.",
      clientTitle: "Для клиента",
      clientCta: "Найти мастера →",
      masterTitle: "Для мастера",
      masterCta: "Зарегистрироваться как мастер →",
      featuresTitle: "Ключевые возможности",
      studioTitle: "У вас студия?",
      studioText:
        "МастерРядом поддерживает полноценный режим студии: несколько мастеров, общий календарь, финансовая отчётность, роли (владелец, администратор, мастер). Мастера работают в своём кабинете, вы видите полную картину.",
      studioCta: "Подробнее о студиях →",
      clientSteps: [
        {
          step: "01",
          title: "Найдите мастера",
          desc: "Ищите по услуге, категории или локации. Смотрите портфолио, читайте отзывы, проверяйте рейтинг.",
        },
        {
          step: "02",
          title: "Выберите время",
          desc: "Видите актуальное расписание в реальном времени. Никаких звонков — просто выберите удобный слот.",
        },
        {
          step: "03",
          title: "Подтвердите запись",
          desc: "Укажите имя и номер телефона. Мастер подтверждает запись — вы получаете уведомление.",
        },
        {
          step: "04",
          title: "Приходите и оставьте отзыв",
          desc: "После визита оцените мастера. Ваш отзыв помогает другим клиентам с выбором.",
        },
      ],
      masterSteps: [
        {
          step: "01",
          title: "Создайте профиль",
          desc: "Заполните информацию о себе, добавьте услуги с ценами и длительностью, загрузите портфолио.",
        },
        {
          step: "02",
          title: "Настройте расписание",
          desc: "Укажите рабочие часы по дням недели, добавьте перерывы и выходные. Поддерживается цикличный режим 2/2.",
        },
        {
          step: "03",
          title: "Принимайте записи",
          desc: "Клиенты бронируют онлайн — вы получаете уведомление в Telegram или пуш. Подтверждайте одним нажатием.",
        },
        {
          step: "04",
          title: "Развивайтесь",
          desc: "Собирайте отзывы, управляйте базой клиентов, запускайте горячие слоты для заполнения окошек.",
        },
      ],
      features: [
        {
          icon: "🔥",
          title: "Горячие слоты",
          desc: "Мастер публикует срочные свободные окошки со скидкой. Клиент видит их в отдельной ленте и может записаться за несколько часов до визита. Помогает заполнить расписание без звонков.",
          badge: "Premium",
        },
        {
          icon: "🏢",
          title: "Студии и команды",
          desc: "Владелец студии добавляет мастеров, распределяет услуги, видит общий календарь и финансовую сводку. Мастера могут запрашивать изменения в своём расписании — владелец одобряет.",
          badge: "Для студий",
        },
        {
          icon: "📸",
          title: "Лента вдохновения",
          desc: "Главная страница МастерРядом — это живой поток работ мастеров. Клиент видит красивое фото, нажимает «Записаться» — и сразу попадает в форму бронирования.",
          badge: "Для всех",
        },
        {
          icon: "🎭",
          title: "Модельные офферы",
          desc: "Мастер публикует объявление: нужна модель для практики или пополнения портфолио по сниженной цене. Модели откликаются, мастер выбирает.",
          badge: "Для мастеров",
        },
      ],
    },
    howToBook: {
      title: "Как забронировать — МастерРядом",
      description:
        "Подробное руководство по записи к мастеру на МастерРядом. Поиск, выбор времени, подтверждение и всё что нужно знать клиенту.",
      heroBadge: "Для клиентов",
      heroTitle: "Как забронировать запись",
      heroSubtitle: "От поиска мастера до подтверждения — за пару минут и без звонков.",
      steps: [
        {
          num: "1",
          title: "Найдите нужного специалиста",
          body: [
            "Откройте каталог и используйте фильтры: выберите услугу (маникюр, стрижка, брови, ресницы и др.), укажите удобный район или смотрите на карте.",
            "На карточке мастера — рейтинг, количество отзывов и ближайшее свободное время. Кликните на карточку чтобы увидеть портфолио, полный прайс и все доступные слоты.",
          ],
          tip: "Совет: смотрите на лайв-ленту работ на главной — там можно сразу найти нужный стиль и записаться прямо с фото.",
        },
        {
          num: "2",
          title: "Выберите услугу и время",
          body: [
            "На странице мастера нажмите «Записаться». Выберите нужную услугу из прайса — система сразу покажет только те слоты, куда укладывается длительность услуги.",
            "Доступное время обновляется в реальном времени. Видите зелёный слот — он точно свободен прямо сейчас.",
          ],
          tip: null,
        },
        {
          num: "3",
          title: "Укажите контактные данные",
          body: [
            "Введите имя и номер телефона. Если вы авторизованы через Telegram или VK — данные подставятся автоматически.",
            "Можно добавить комментарий мастеру: пожелания, уточнения или вопрос.",
          ],
          tip: null,
        },
        {
          num: "4",
          title: "Ожидайте подтверждения",
          body: [
            "После отправки заявки мастер получает уведомление и подтверждает запись. Обычно это занимает несколько минут.",
            "Вы получите уведомление в приложении или в Telegram-боте МастерРядом. Если у мастера включено авто-подтверждение — запись подтвердится мгновенно.",
          ],
          tip: "Совет: подключите Telegram-уведомления в настройках — так не пропустите ни одно подтверждение или изменение.",
        },
        {
          num: "5",
          title: "Приходите на приём",
          body: [
            "За день до визита придёт напоминание. Если нужно перенести или отменить — сделайте это заранее через раздел «Мои записи».",
          ],
          tip: null,
        },
        {
          num: "6",
          title: "Оставьте отзыв",
          body: [
            "После визита вы сможете оценить мастера и написать отзыв. Это помогает другим клиентам сделать выбор, а хорошие мастера получают больше записей.",
          ],
          tip: null,
        },
      ],
      hotSlotsTitle: "Горячие слоты",
      hotSlotsBadge: "Со скидкой",
      hotSlotsDescription: [
        "Горячие слоты — это срочные свободные окошки, которые мастера публикуют со скидкой.",
        "Например, у мастера отменилась запись на завтра — он публикует слот со скидкой 20%, и вы видите его в ленте «Горячие слоты».",
        "Идеально если хотите записаться быстро или сэкономить.",
      ],
      hotSlotsCta: "Смотреть горячие слоты →",
      faqTitle: "Частые вопросы",
      faqItems: [
        [
          "Могу ли я записаться без регистрации?",
          "Да. Достаточно указать имя и телефон. Регистрация через Telegram или VK делает процесс более удобным — данные подставляются автоматически.",
        ],
        [
          "Как отменить или перенести запись?",
          "Откройте раздел «Мои записи» в личном кабинете. Кнопка отмены или переноса доступна там.",
        ],
        [
          "Что если мастер не подтвердил запись?",
          "Обычно подтверждение приходит в течение нескольких минут. Если долго нет ответа — напишите мастеру напрямую через контакты на его странице.",
        ],
        [
          "Безопасно ли указывать телефон?",
          "Номер телефона передаётся только мастеру которому вы записались. Мы не передаём контакты третьим лицам.",
        ],
      ],
      faqCta: "Все вопросы и ответы →",
      ctaFindMaster: "Найти мастера →",
    },
    offline: {
      title: "Нет подключения к интернету",
      subtitle: "Похоже, вы офлайн. Проверьте соединение и попробуйте снова.",
      reload: "Обновить страницу",
      back: "Назад",
    },
    forbidden: {
      title: "Нет доступа",
      subtitle: "У вашей учетной записи нет прав для этой страницы.",
    },
    blog: {
      title: "Блог — МастерРядом",
      description:
        "Анонсы новых функций, обновления платформы и полезные материалы для мастеров и клиентов.",
      heroBadge: "Блог",
      heroTitle: "Новости и обновления",
      heroSubtitle: "Анонсы функций, гиды для мастеров и всё важное о платформе.",
      comingSoonTitle: "Блог скоро запустится",
      comingSoonSubtitle: "Пока готовим материалы — вот анонсы того, что выйдет первым.",
      comingSoonPosts: [
        {
          tag: "Анонс",
          title: "Горячие слоты: заполняйте расписание за часы до приёма",
          desc: "Публикуйте срочные окошки со скидкой — клиенты видят их в отдельной ленте и записываются мгновенно.",
          date: "Скоро",
        },
        {
          tag: "Обновление",
          title: "Онлайн-оплата записей через ЮKassa",
          desc: "Принимайте предоплату прямо в МастерРядом. Поддержка СБП, карт и автоплатежей.",
          date: "Скоро",
        },
        {
          tag: "Функция",
          title: "Импорт клиентской базы из YClients",
          desc: "Переходите на МастерРядом без потери данных — перенесите клиентов и историю визитов в один клик.",
          date: "Скоро",
        },
        {
          tag: "Гид",
          title: "Как настроить расписание: полный разбор",
          desc: "Недельный режим, цикличное расписание, шаблоны смен, исключения и блокировки времени.",
          date: "Скоро",
        },
      ],
    },
    becomeMaster: {
      title: "Стать мастером — МастерРядом",
      description:
        "Зарегистрируйтесь как мастер на МастерРядом. Онлайн-запись, управление расписанием, клиентская база и продвижение в каталоге.",
      heroBadge: "Для мастеров",
      heroTitleMain: "Ваш бизнес —",
      heroTitleHighlight: "без лишней суеты",
      heroSubtitle:
        "МастерРядом берёт на себя запись и напоминания. Вы занимаетесь тем, что умеете лучше всего.",
      ctaPrimary: "Зарегистрироваться бесплатно",
      ctaSecondary: "Смотреть тарифы",
      heroNote: "Бесплатный тариф навсегда. Карта не нужна.",
      advantagesTitle: "Что вы получаете",
      advantages: [
        {
          icon: "📅",
          title: "Онлайн-запись без звонков",
          desc: "Клиенты бронируют сами — вы получаете уведомление и подтверждаете одним нажатием. Никаких переписок в директе.",
        },
        {
          icon: "🗓️",
          title: "Умное расписание",
          desc: "Настройте рабочие часы, перерывы, выходные и буфер между записями. Поддерживается цикличный режим 2/2 и 3/3.",
        },
        {
          icon: "📸",
          title: "Портфолио в ленте",
          desc: "Ваши работы появляются на главной странице МастерРядом. Клиент видит фото — нажимает «Записаться» — попадает к вам.",
        },
        {
          icon: "⭐",
          title: "Отзывы и рейтинг",
          desc: "После каждого визита клиент может оставить отзыв. Рейтинг влияет на позицию в каталоге.",
        },
        {
          icon: "🔔",
          title: "Уведомления в Telegram",
          desc: "Подключите бота — и новые записи, отмены и сообщения приходят прямо в мессенджер.",
        },
        {
          icon: "👥",
          title: "База клиентов",
          desc: "Все кто записывался к вам — в одном месте. История визитов, контакты, заметки.",
        },
      ],
      startTitle: "Как начать",
      startSteps: [
        {
          step: "1",
          title: "Зарегистрируйтесь",
          desc: "Войдите через Telegram или VK. Выберите роль «Мастер» или «Студия».",
        },
        {
          step: "2",
          title: "Заполните профиль",
          desc: "Добавьте имя, описание, категории услуг, фото профиля и загрузите первые работы в портфолио.",
        },
        {
          step: "3",
          title: "Настройте прайс",
          desc: "Создайте услуги с названием, ценой и длительностью. Можно добавить несколько категорий.",
        },
        {
          step: "4",
          title: "Откройте расписание",
          desc: "Укажите рабочие часы. Как только опубликуете профиль — появитесь в каталоге и клиенты смогут записываться.",
        },
      ],
      pricingTitle: "Тарифы",
      pricingText:
        "Базовые функции — бесплатно навсегда. PRO и Premium открывают карту, горячие слоты, аналитику и приоритет в каталоге.",
      pricingCta: "Сравнить тарифы →",
      studioTitle: "Работаете в студии?",
      studioText:
        "МастерРядом поддерживает режим студии: несколько мастеров, общий календарь, разграничение ролей (владелец, администратор, мастер), финансовая отчётность по каждому специалисту. Мастера работают в своём кабинете, вы видите полную картину.",
      studioCta: "Подробнее в базе знаний →",
    },
    pricing: {
      title: "Тарифы — МастерРядом",
      description:
        "Тарифные планы МастерРядом для мастеров и студий. Бесплатный тариф навсегда, PRO и Premium для роста.",
      heroBadge: "Тарифы",
      heroTitleMain: "Прозрачные цены,",
      heroTitleHighlight: "никаких сюрпризов",
      heroSubtitle: "Бесплатный тариф навсегда. Переходите на PRO или Premium когда будете готовы.",
      masterTitle: "Для соло-мастеров",
      studioTitle: "Для студий",
      faqTitle: "Вопросы о тарифах",
      faqItems: [
        [
          "Нужна ли карта для бесплатного тарифа?",
          "Нет. Регистрация и использование бесплатного тарифа не требуют привязки карты.",
        ],
        [
          "Могу ли я поменять тариф в любой момент?",
          "Да. Переход на более высокий тариф — мгновенный. При понижении тариф действует до конца оплаченного периода.",
        ],
        [
          "Как работает онлайн-оплата записей?",
          "Оплата клиентами доступна с тарифа PRO. Используется ЮKassa — поддерживает карты и СБП. Вы можете включать оплату отдельно для каждой услуги.",
        ],
        [
          "Есть ли скидка при оплате на год?",
          "Готовим годовые тарифы со скидкой — следите за обновлениями в нашем Telegram-канале.",
        ],
      ],
      plans: {
        master: [
          {
            code: "free",
            name: "FREE",
            price: "0 ₽",
            period: "навсегда",
            desc: "Базовые инструменты для старта. Без ограничений по времени.",
            features: [
              "Профиль в каталоге",
              "Онлайн-запись клиентов",
              "Все виды расписания (недельное, цикличное, шаблоны)",
              "Портфолио до 15 фотографий",
              "Прайс-лист услуг",
              "Отзывы и ответы на них",
              "Список клиентов (без истории визитов)",
              "Уведомления в приложении + PWA push",
              "Вход через Telegram / VK",
            ],
            cta: "Начать бесплатно",
            ctaHref: "/login",
          },
          {
            code: "pro",
            name: "PRO",
            price: "990 ₽",
            period: "в месяц",
            badge: "Популярный",
            badgeColor: "from-primary to-primary-magenta",
            desc: "Полный инструментарий для активного мастера.",
            features: [
              "Всё из FREE",
              "Отображение на карте",
              "Приоритет в каталоге",
              "Портфолио без ограничений",
              "Онлайн-оплата записей (вкл/выкл по услугам)",
              "Уведомления в Telegram и SMS",
              "История визитов клиентов",
              "Заметки о клиентах",
              "Финансовая касса (при подключении оплаты)",
            ],
            cta: "Попробовать PRO",
            ctaHref: "/login",
            highlight: true,
          },
          {
            code: "premium",
            name: "PREMIUM",
            price: "1 990 ₽",
            period: "в месяц",
            desc: "Максимальные возможности для роста и продвижения.",
            features: [
              "Всё из PRO",
              "Горячие слоты со скидкой",
              "Badge и выделение в каталоге",
              "Аналитика с графиками",
              "Импорт клиентской базы из YClients",
            ],
            cta: "Попробовать Premium",
            ctaHref: "/login",
          },
        ],
        studio: [
          {
            code: "studio_free",
            name: "FREE",
            price: "0 ₽",
            period: "навсегда",
            desc: "До 2 мастеров. Попробуйте без риска.",
            features: [
              "Профиль студии в каталоге",
              "До 2 мастеров",
              "Онлайн-запись",
              "Все виды расписания",
              "Портфолио студии до 15 фото + 10 фото/мастер",
              "Отзывы",
              "Список клиентов (без истории)",
              "Роли: владелец, администратор, мастер",
              "Уведомления в приложении + PWA push",
            ],
            cta: "Начать бесплатно",
            ctaHref: "/login",
          },
          {
            code: "studio_pro",
            name: "PRO",
            price: "2 490 ₽",
            period: "в месяц",
            badge: "Популярный",
            badgeColor: "from-primary to-primary-magenta",
            desc: "До 7 мастеров. Полный контроль над студией.",
            features: [
              "Всё из FREE",
              "До 7 мастеров",
              "Отображение на карте",
              "Приоритет в каталоге",
              "Портфолио без ограничений",
              "Общий календарь всех мастеров",
              "Финансовая отчётность по студии и мастерам",
              "Онлайн-оплата записей",
              "Уведомления в Telegram и SMS",
              "История визитов и заметки о клиентах",
            ],
            cta: "Попробовать PRO",
            ctaHref: "/login",
            highlight: true,
          },
          {
            code: "studio_premium",
            name: "PREMIUM",
            price: "4 990 ₽",
            period: "в месяц",
            desc: "Безлимит мастеров. Аналитика и максимум возможностей.",
            features: [
              "Всё из PRO",
              "Неограниченное количество мастеров",
              "Горячие слоты",
              "Badge и выделение в каталоге",
              "Аналитика с графиками",
              "Импорт клиентской базы из YClients",
            ],
            cta: "Попробовать Premium",
            ctaHref: "/login",
          },
        ],
      },
    },
    partners: {
      title: "Партнёрам — МастерРядом",
      description:
        "Сотрудничество с МастерРядом: интеграции, партнёрская программа, совместные проекты. Контакты для связи.",
      heroBadge: "Партнёрам",
      heroTitleMain: "Давайте сделаем",
      heroTitleHighlight: "что-то вместе",
      heroSubtitle:
        "МастерРядом открыт к сотрудничеству. Если видите точку пересечения — напишите, разберёмся.",
      types: [
        {
          icon: "🔗",
          title: "Технические интеграции",
          desc: "Если у вас есть CRM, POS-система, сервис SMS-уведомлений или другой инструмент для beauty-индустрии — давайте обсудим интеграцию.",
        },
        {
          icon: "📢",
          title: "Маркетинг и коллаборации",
          desc: "Совместные акции, кросс-промо, размещение у партнёров. Подходит для брендов косметики, образовательных платформ, медиа.",
        },
        {
          icon: "🏫",
          title: "Школы и курсы",
          desc: "Обучаете мастеров? Предлагаем специальные условия для студентов и преподавателей — регистрация на платформе и первые месяцы по льготной ставке.",
        },
        {
          icon: "🏢",
          title: "Корпоративным клиентам",
          desc: "Компании, которые хотят организовать beauty-услуги для сотрудников — напишите нам, обсудим корпоративные условия.",
        },
      ],
      contactTitle: "Напишите нам",
      contactSubtitle:
        "Расскажите коротко о себе и идее — ответим в течение рабочего дня. Предпочтительный способ связи: Telegram.",
      emailLabel: "Email",
      telegramLabel: "Telegram",
      footerNote:
        "Рассматриваем все обращения. Спам и нерелевантные предложения просим не присылать.",
    },
    giftCards: {
      title: "Подарочные сертификаты — МастерРядом",
      description: "Подарочные сертификаты на услуги красоты. Скоро на МастерРядом.",
      heading: "Подарочные сертификаты",
      heroText:
        "Скоро вы сможете дарить сертификаты на любые услуги у мастеров МастерРядом. Именинница сама выберет мастера и запишется в удобное время.",
      plannedTitle: "Что планируется:",
      plannedItems: [
        "Сертификаты на фиксированную сумму",
        "Электронная доставка на email или через мессенджер",
        "Именной дизайн с текстом от вас",
        "Срок действия — 12 месяцев",
        "Принимается у любого мастера на платформе",
      ],
      footerText: "Хотите узнать первыми о запуске?",
      footerCta: "Подпишитесь на Telegram-канал →",
    },
    careers: {
      title: "Вакансии — МастерРядом",
      description: "Открытые вакансии в МастерРядом. Строим лучший маркетплейс для мастеров красоты.",
      heroBadge: "Вакансии",
      heroTitle: "Строим вместе",
      heroSubtitle:
        "МастерРядом — небольшая команда, которая делает большой продукт. Нам важны люди, которые думают о пользователях и умеют работать в условиях неопределённости.",
      emptyTitle: "Открытых вакансий пока нет",
      emptySubtitle:
        "Но мы всегда рады талантливым людям. Если вы чувствуете, что можете быть полезны — напишите нам напрямую с рассказом о себе.",
      emptyCta: "Написать в команду →",
      cultureTitle: "Как мы работаем",
      cultureItems: [
        [
          "🌍",
          "Удалённо",
          "Работаем из любой точки мира. Асинхронная коммуникация по умолчанию.",
        ],
        [
          "🚀",
          "Быстрые итерации",
          "Маленькие задачи, короткие циклы. Видите результат своей работы каждую неделю.",
        ],
        [
          "💬",
          "Открытость",
          "Решения обсуждаются в команде. Ваше мнение имеет значение независимо от должности.",
        ],
        [
          "📈",
          "Рост вместе с продуктом",
          "Ранняя команда — это опционы, история и влияние на продукт.",
        ],
      ],
    },
    helpMasters: {
      title: "База знаний для мастеров — МастерРядом",
      description:
        "Подробное руководство по работе с кабинетом мастера МастерРядом: профиль, расписание, запись, клиенты, финансы и студия.",
      heroBadge: "База знаний",
      heroTitle: "Кабинет мастера: полное руководство",
      heroSubtitle: "Всё что нужно знать для работы с МастерРядом.",
      quickNavTitle: "Быстрая навигация",
      footerTitle: "Не нашли ответ?",
      footerSubtitle: "Напишите нам — разберёмся вместе.",
      footerSupport: "Поддержка",
      footerFaq: "FAQ",
      sections: [
        {
          id: "profile",
          icon: "👤",
          title: "Профиль и настройки",
          items: [
            {
              q: "Как заполнить профиль",
              a: "Перейдите в Кабинет → Профиль. Заполните имя, теглайн (короткое описание), категории услуг, город и контактную информацию. Добавьте фото аватара — профили с фото получают значительно больше записей.",
            },
            {
              q: "Публикация профиля",
              a: "Профиль появляется в каталоге только после публикации. Нажмите «Опубликовать» в настройках профиля. До публикации вас не видят клиенты, но вы можете тестировать запись.",
            },
            {
              q: "Красивый URL (username)",
              a: "В настройках профиля можно задать короткий username: МастерРядом.ru/u/ваше-имя. Менять его можно раз в 30 дней.",
            },
            {
              q: "Подключение Telegram",
              a: "Перейдите в Настройки → Уведомления → Telegram. Нажмите «Подключить» и запустите нашего бота. После подключения все новые записи, отмены и изменения будут приходить в Telegram.",
            },
          ],
        },
        {
          id: "services",
          icon: "💅",
          title: "Услуги и прайс",
          items: [
            {
              q: "Как добавить услугу",
              a: "Кабинет → Услуги → «Добавить услугу». Укажите название, длительность (в минутах) и цену. Можно добавить описание и прикрепить к категории. Услуги сортируются drag-and-drop.",
            },
            {
              q: "Категории услуг",
              a: "Группируйте услуги по категориям: маникюр, педикюр, брови и т.д. Это помогает клиентам ориентироваться в прайсе. Категории создаются в настройках услуг.",
            },
            {
              q: "Включение / отключение услуги",
              a: "Услугу можно временно отключить — она скроется из публичного профиля, но сохранится с историей бронирований. Удалять услугу не нужно.",
            },
          ],
        },
        {
          id: "schedule",
          icon: "🗓️",
          title: "Расписание",
          items: [
            {
              q: "Недельное расписание",
              a: "Базовый режим: укажите рабочее время для каждого дня недели. Клиенты видят слоты только в указанные часы. Нерабочие дни остаются закрытыми автоматически.",
            },
            {
              q: "Цикличное расписание",
              a: "Если работаете по схеме 2/2, 3/3 или другому циклу — настройте его в разделе «Правила расписания». Укажите начало цикла, рабочие и выходные дни.",
            },
            {
              q: "Шаблоны рабочего дня",
              a: "Создайте шаблоны для разных типов дней: обычный день, укороченный, с длинным обедом. Применяйте шаблон к конкретным датам через раздел «Исключения».",
            },
            {
              q: "Исключения и выходные",
              a: "В разделе «Расписание» можно пометить любую дату как выходной или задать нестандартные часы. Это перекрывает базовое расписание только для выбранной даты.",
            },
            {
              q: "Блокировка времени",
              a: "Заблокируйте конкретный промежуток внутри рабочего дня: обед, встреча, перерыв. Слоты в этот период станут недоступными для бронирования.",
            },
            {
              q: "Буфер между записями",
              a: "В настройках можно задать буфер (в минутах) который автоматически добавляется после каждой записи. Удобно для уборки рабочего места или подготовки.",
            },
            {
              q: "Авто-подтверждение",
              a: "Включите авто-подтверждение в настройках — записи будут подтверждаться мгновенно без вашего участия. Полезно для популярных мастеров с высоким спросом.",
            },
          ],
        },
        {
          id: "bookings",
          icon: "📋",
          title: "Управление записями",
          items: [
            {
              q: "Где смотреть записи",
              a: "Кабинет → Дашборд показывает записи на сегодня и ближайшие дни. Все записи с фильтрами — в разделе «Записи».",
            },
            {
              q: "Подтверждение и отклонение",
              a: "Новая запись приходит со статусом «Ожидает». Нажмите «Подтвердить» или «Отклонить». При отклонении можно указать причину — клиент её увидит.",
            },
            {
              q: "Перенос записи",
              a: "Вы или клиент можете предложить другое время. Система отправит уведомление второй стороне для согласования.",
            },
            {
              q: "Ручное создание записи",
              a: "Создайте запись вручную для клиента, который обратился не через сайт. Кабинет → Дашборд → «Добавить запись».",
            },
            {
              q: "Тихий режим",
              a: "При создании или подтверждении записи можно включить «Тихий режим» — уведомления клиенту не будут отправлены. Используйте с умом.",
            },
          ],
        },
        {
          id: "portfolio",
          icon: "📸",
          title: "Портфолио",
          items: [
            {
              q: "Загрузка фотографий",
              a: "Кабинет → Профиль → Портфолио. Загрузите работы в формате JPG или PNG. На бесплатном тарифе — до 15 фото, на PRO и Premium — без ограничений.",
            },
            {
              q: "Появление в ленте",
              a: "Ваши работы автоматически попадают в ленту вдохновения на главной странице. Клиент видит фото, нажимает «Записаться» — и попадает к вам.",
            },
            {
              q: "Привязка к услуге",
              a: "При загрузке можно указать какая услуга на фото. Это помогает клиентам понять что именно вы делаете.",
            },
          ],
        },
        {
          id: "clients",
          icon: "👥",
          title: "Клиентская база",
          items: [
            {
              q: "Список клиентов",
              a: "Кабинет → Клиенты. Все кто записывался к вам — в одном списке с контактами. На бесплатном тарифе — без истории визитов, на PRO+ история доступна.",
            },
            {
              q: "Заметки о клиентах",
              a: "На тарифе PRO и выше можно добавлять личные заметки к каждому клиенту: аллергии, предпочтения, особенности. Заметки видите только вы.",
            },
            {
              q: "Импорт из YClients",
              a: "На Premium тарифе доступен одноразовый импорт клиентской базы из YClients. Для этого потребуется API-ключ YClients и ID вашей компании.",
            },
          ],
        },
        {
          id: "promotion",
          icon: "🔥",
          title: "Продвижение",
          items: [
            {
              q: "Горячие слоты",
              a: "Доступны на Premium тарифе. Публикуйте срочные свободные окошки со скидкой (10%, 20%, 30% или фиксированная сумма). Слоты появляются в специальной ленте — клиенты записываются быстро.",
            },
            {
              q: "Модельные офферы",
              a: "Ищете модель для практики или пополнения портфолио? Создайте оффер с описанием, датой и ценой. Желающие откликаются — вы выбираете подходящую кандидатуру.",
            },
            {
              q: "Приоритет в каталоге",
              a: "На PRO тарифе ваша карточка появляется выше в результатах поиска. На Premium — дополнительно выделяется визуально с badge в каталоге.",
            },
          ],
        },
        {
          id: "studio",
          icon: "🏢",
          title: "Работа в студии",
          items: [
            {
              q: "Мастер в студии",
              a: "Если вы работаете в студии — владелец приглашает вас по номеру телефона. После принятия приглашения у вас появляется кабинет мастера внутри студии.",
            },
            {
              q: "Запрос изменения расписания",
              a: "Мастер может подать заявку на изменение своего расписания. Владелец или администратор студии одобряет или отклоняет запрос.",
            },
            {
              q: "Роли в студии",
              a: "Владелец, Администратор, Мастер и Финансист. Администратор может управлять записями и командой. Финансист видит отчётность. Мастер — только свой кабинет.",
            },
            {
              q: "Общий календарь",
              a: "Доступен владельцу и администраторам студии на PRO+ тарифе. Показывает записи всех мастеров в одном виде с переключением между днём, неделей и месяцем.",
            },
          ],
        },
      ],
    },
    privacy: {
      title: "Политика конфиденциальности — МастерРядом",
      description:
        "Политика конфиденциальности МастерРядом: какие данные собираем, как используем и как защищаем.",
      metaLine: "Версия документа: {version} · Дата обновления: {updatedAt}",
      heading: "Политика конфиденциальности",
      intro:
        "Настоящая Политика описывает, какие персональные данные мы собираем, как их используем и какие права есть у пользователей сервиса МастерРядом.",
      todoTitle: "TODO: заполнить реквизиты",
      todoSubtitle: "Перед запуском в прод замените плейсхолдеры на реальные данные оператора.",
      legalEntityNamePlaceholder: "[Укажи свои данные: ИП Иванов Иван Иванович]",
      innPlaceholder: "[укажи ИНН]",
      ogrnPlaceholder: "[укажи ОГРН]",
      legalAddressPlaceholder: "[укажи юридический адрес]",
      innLabel: "ИНН",
      ogrnLabel: "ОГРН/ОГРНИП",
      legalAddressLabel: "Юридический адрес",
      contactsLabel: "Контакты",
      sections: {
        generalTitle: "1. Общие положения",
        generalText:
          "Оператор обрабатывает персональные данные в соответствии с законодательством РФ и настоящей Политикой. Используя сервис МастерРядом, пользователь подтверждает согласие с условиями обработки данных.",
        dataTitle: "2. Какие данные мы собираем",
        dataItems: [
          "Контактные данные: телефон, электронная почта.",
          "Данные профиля: имя, фото, предпочтения, история записей.",
          "Технические данные: IP-адрес, cookies, пользовательский агент, логи действий.",
        ],
        purposesTitle: "3. Цели обработки",
        purposesItems: [
          "Регистрация и авторизация пользователей.",
          "Организация и управление бронированиями услуг.",
          "Поддержка, уведомления и улучшение качества сервиса.",
          "Выполнение требований законодательства.",
        ],
        legalBasisTitle: "4. Правовые основания",
        legalBasisText:
          "Основанием обработки является согласие пользователя, заключение и исполнение договора на оказание услуг, а также требования законодательства.",
        securityTitle: "5. Хранение и защита данных",
        securityText:
          "Мы применяем технические и организационные меры безопасности для защиты данных от несанкционированного доступа, изменения, раскрытия или уничтожения.",
        sharingTitle: "6. Передача третьим лицам",
        sharingText:
          "Данные могут передаваться партнерам и подрядчикам (например, платежным провайдерам, сервисам уведомлений) только в объеме, необходимом для оказания услуг, и при соблюдении конфиденциальности.",
        rightsTitle: "7. Права пользователя",
        rightsItems: [
          "Получать информацию об обработке своих данных.",
          "Требовать уточнения, блокирования или удаления данных.",
          "Отозвать согласие на обработку данных.",
        ],
        contactsTitle: "8. Контакты",
        contactsPrivacy:
          "По вопросам обработки персональных данных пишите на {privacy} или {legal}.",
        contactsSupport: "Техническая поддержка: {support}.",
      },
    },
    terms: {
      title: "Пользовательское соглашение — МастерРядом",
      description:
        "Пользовательское соглашение МастерРядом: правила использования сервиса, оплаты и ответственности.",
      metaLine: "Версия документа: {version} · Дата обновления: {updatedAt}",
      heading: "Пользовательское соглашение",
      intro:
        "Настоящее Соглашение регулирует использование платформы МастерРядом и порядок оказания услуг между пользователями, провайдерами и оператором сервиса.",
      todoTitle: "TODO: заполнить реквизиты",
      todoSubtitle: "Перед запуском в прод замените плейсхолдеры на реальные данные оператора.",
      legalEntityNamePlaceholder: "[Укажи свои данные: ИП Иванов Иван Иванович]",
      innPlaceholder: "[укажи ИНН]",
      ogrnPlaceholder: "[укажи ОГРН]",
      legalAddressPlaceholder: "[укажи юридический адрес]",
      contactsLabel: "Контакты",
      innLabel: "ИНН",
      ogrnLabel: "ОГРН/ОГРНИП",
      legalAddressLabel: "Юридический адрес",
      pricingPlaceholders: {
        listedPrice: "X₽/мес",
        promotedPrice: "Y₽/мес",
        commission: "Z%",
        minPayout: "W₽",
      },
      sections: {
        termsTitle: "1. Термины и определения",
        termsText:
          "Платформа — сайт и сервисы МастерРядом. Пользователь — физическое лицо, использующее сервис. Провайдер — мастер или студия, размещающие услуги и принимающие записи.",
        accessTitle: "2. Регистрация и доступ",
        accessText:
          "Доступ к функционалу сервиса предоставляется после подтверждения номера телефона. Пользователь обязуется предоставлять достоверные данные и соблюдать правила сервиса.",
        bookingsTitle: "3. Бронирования и услуги",
        bookingsItems: [
          "Пользователь выбирает услугу и свободный слот, подтверждает бронирование.",
          "Провайдер подтверждает запись и оказывает услугу в согласованное время.",
          "Сервис не является стороной договора между пользователем и провайдером.",
        ],
        paymentsTitle: "4. Оплата и возвраты",
        paymentsText:
          "Оплата может осуществляться онлайн через доступные платежные методы. Возвраты и отмены регулируются политиками провайдера и условиями платформы.",
        liabilityTitle: "5. Ответственность",
        liabilityText:
          "Оператор сервиса не несет ответственности за качество услуг, оказываемых провайдерами, однако стремится обеспечивать надежность платформы и поддержку пользователей.",
        ipTitle: "6. Интеллектуальная собственность",
        ipText:
          "Все материалы и функциональность сервиса принадлежат оператору или используются по лицензии. Запрещено копирование и использование без разрешения.",
        terminationTitle: "7. Прекращение доступа",
        terminationText:
          "Оператор вправе ограничить доступ при нарушении условий соглашения, а пользователь может прекратить использование сервиса в любой момент.",
        pricingTitle: "8. Тарифы и комиссии",
        pricingSubtitle: "8.1. Тарифные планы для Провайдеров",
        pricingItems: [
          "Listed: {listedPrice} — базовый тариф для размещения услуг.",
          "Promoted: {promotedPrice} — расширенное продвижение в каталоге.",
          "Комиссия с онлайн-платежей: {commission}.",
          "Минимальная сумма вывода: {minPayout}.",
        ],
        pricingNote:
          "Значения тарифов указаны как плейсхолдеры и должны быть обновлены перед запуском.",
        contactsTitle: "9. Контакты",
        contactsText:
          "Юридические вопросы: {legal}. Техническая поддержка: {support}.",
      },
    },
    publicProfile: {
      notFoundTitle: "Профиль не найден | МастерРядом",
      studioDescriptionFallback:
        "Запись онлайн в студию {name}. Услуги, цены, отзывы и свободные окна.",
      masterDescriptionFallback:
        "Запись онлайн к мастеру {name}. Услуги, цены, отзывы и свободные окна.",
      titleTemplate: "{name} — запись онлайн | МастерРядом",
      debugReasons: {
        unpublished: "найден, но профиль не опубликован",
        aliasUnpublished: "найден алиас, но профиль не опубликован",
        invalid: "некорректный username",
        notFound: "username не найден",
        redirectAlias: "редирект по алиасу на",
      },
    },
    publicClient: {
      title: "Профиль клиента | МастерРядом",
      unavailable: "Публичный профиль клиента недоступен.",
    },
    publicBooking: {
      notFoundTitle: "Запись онлайн | МастерРядом",
      studioDescriptionFallback:
        "Запись онлайн в студию {name}. Выберите услуги и свободное время.",
      masterDescriptionFallback:
        "Запись онлайн к мастеру {name}. Выберите услуги и свободное время.",
      titleTemplate: "{name} — запись онлайн | МастерРядом",
    },
    modelOffer: {
      notFoundTitle: "Предложение не найдено | МастерРядом",
      notFoundDescription: "Предложение для моделей недоступно или было закрыто.",
      titleTemplate: "{service} для моделей | МастерРядом",
      descriptionTemplate: "Предложение от мастера {name}: {date} {start}-{end}.",
      backToOffers: "← Все предложения",
      masterLabel: "Мастер",
      masterProfileCta: "Перейти в профиль мастера",
      dateTimeLabel: "Дата и время",
      durationLabel: "Длительность",
      priceLabel: "Стоимость",
      requirementsTitle: "Требования",
      requirementsEmpty: "Нет дополнительных требований.",
      applyTitle: "Отклик на предложение",
      applySubtitle:
        "Загрузите 1–3 фото и коротко расскажите о себе. Мастер увидит вашу заявку в кабинете.",
    },
  },
  chat: {
    errors: {
      unavailable: "Чат недоступен",
      loadFailed: "Не удалось загрузить чат",
      sendFailed: "Не удалось отправить сообщение",
    },
    labels: {
      you: "Вы",
    },
    actions: {
      retry: "Повторить",
      send: "Отправить",
    },
    states: {
      closedAfterVisit: "Чат закрыт для отправки (после визита). История доступна 24 часа.",
      closed: "Чат закрыт. История доступна.",
      empty: "Сообщений пока нет.",
    },
    placeholder: "Напишите сообщение",
  },
} as const;


