export const actions = {
  save: "Сохранить",
  cancel: "Отмена",
  close: "Закрыть",
  delete: "Удалить",
  add: "Добавить",
  replace: "Заменить",
  remove: "Удалить",
  select: "Выбрать",
  open: "Открыть",
  hide: "Скрыть",
  show: "Показать",
  confirm: "Подтвердить",
  decline: "Отклонить",
  openChat: "Открыть чат",
  update: "Обновить",
  later: "Позже",
  goTo: "Перейти",
} as const;
