export const adminPanel = {
  title: "МастерРядом",
  caption: "Админ-панель",
  sectionCaption: "Админ-панель",
  nav: {
    dashboard: "Дашборд",
    catalog: "Каталог",
    cities: "Города",
    users: "Пользователи",
    billing: "Финансы и тарифы",
    reviews: "Отзывы",
    settings: "Настройки системы",
  },
  breadcrumb: {
    root: "Админка",
  },
  page: {
    dashboard: {
      title: "Дашборд",
      sublabel: "ключевые метрики и события",
    },
    catalog: {
      title: "Каталог",
      sublabel: "категории, теги, услуги",
    },
    cities: {
      title: "Города",
      sublabel: "управление списком городов",
    },
    users: {
      title: "Пользователи",
      sublabel: "клиенты, мастера, студии",
    },
    billing: {
      title: "Финансы и тарифы",
      sublabel: "планы, платежи, подписки",
    },
    reviews: {
      title: "Отзывы",
      sublabel: "модерация и жалобы",
    },
    settings: {
      title: "Настройки системы",
      sublabel: "конфигурация платформы",
    },
  },
  role: {
    superadmin: "SUPERADMIN",
    admin: "ADMIN",
  },
  mobile: {
    openMenu: "Открыть меню",
    closeMenu: "Закрыть меню",
  },
  aria: {
    sidebar: "Главная навигация админ-панели",
    breadcrumb: "Хлебные крошки",
  },
  dashboard: {
    kpi: {
      registrations7d: "Новых регистраций · 7д",
      bookings1d: "Записей за сутки",
      activeSubs: "Активных подписок",
      revenueMonth: "Выручка платформы · мес",
      deltaUnavailable: "—",
      deltaUp: "↑",
      deltaDown: "↓",
      deltaTooltipPositive: "vs прошлый период",
      deltaTooltipNegative: "vs прошлый период",
    },
    charts: {
      registrationsTitle: "Регистрации за 7 дней",
      registrationsDeltaSuffix: "vs прошлая неделя",
      bookingsTitle: "Записи за 7 дней",
      bookingsDeltaSuffix: "к прошлой неделе",
      todayLabel: "сегодня",
      tooltipRegistrations: "Регистраций",
      tooltipBookings: "Записей",
      ariaLabelRegistrations: "Бар-чарт регистраций по дням за 7 дней",
      ariaLabelBookings: "Линейный график записей по дням за 7 дней",
    },
    feed: {
      title: "История событий",
      // PERF-27: интервал в подписи приходит из POLL_MS компонента — при 30 с
      // прежний «LIVE» вводил бы в заблуждение, подпись говорит ровно то, что
      // происходит: периодическое автообновление.
      liveBadge: (seconds: number) => `обновление каждые ${seconds} с`,
      empty: "Пока нет событий",
      eventTypes: {
        booking: "Запись",
        bookingCancel: "Отмена записи",
        registrationMaster: "Регистрация · мастер",
        registrationClient: "Регистрация · клиент",
        subscription: "Подписка",
        complaint: "Жалоба на отзыв",
      },
      perMonthSuffix: "/мес",
      cancelPrefix: "−",
      complaintOpenLabel: "Открыто",
    },
    health: {
      title: "Состояние системы",
      stats: {
        apiUptime: "API uptime",
        p95: "Время ответа p95",
        queuePending: "Очередь задач",
        queueDead: "Мёртвые задачи",
        complaintsOpen: "Жалобы без модерации",
        smsBalance: "SMS-баланс",
        worker: "Воркер очереди",
      },
      queuePendingSuffix: "ждёт",
      queuePendingHint:
        "Задачи в очереди Redis, включая отложенные напоминания с временем запуска в будущем",
      smsNotConfigured: "Не настроен",
      metricUnavailable: "—",
      metricUnavailableHint: "Метрика появится после подключения мониторинга",
      noDataYetHint: "Данных ещё нет: появятся через минуту после старта приложения",
      uptimeValue: (percent: string) => `${percent} % · 24 ч`,
      uptimeHint: (upMinutes: string, observedMinutes: string) =>
        `Минут с отметкой приложения: ${upMinutes} из ${observedMinutes} за последние 24 ч`,
      p95Value: (ms: string) => `≤ ${ms} мс`,
      p95ValueAbove: (ms: string) => `> ${ms} мс`,
      p95NoTraffic: "Нет запросов",
      p95Hint: (windowMinutes: number, requests: string, errors5xx: string) =>
        `За ${windowMinutes} мин: запросов ${requests}, ошибок 5xx ${errors5xx}. Оценка по гистограмме, пробы /api/health не учитываются`,
      workerAlive: (ago: string) => `Работает · отметка ${ago}`,
      workerStale: (ago: string) => `Нет связи · отметка ${ago}`,
      workerUnknown: "Нет отметки",
      workerHint: "Воркер отмечается каждые 30 с; порог — 2 мин без отметки",
      workerRedisUnavailableHint: "Redis недоступен — состояние воркера неизвестно",
      queueRedisUnavailableHint: "Redis недоступен — очередь не прочитана",
      agoSeconds: (n: number) => `${n} с назад`,
      agoMinutes: (n: number) => `${n} мин назад`,
      agoHours: (n: number) => `${n} ч назад`,
    },
    errors: {
      loadKpis: "Не удалось загрузить метрики. Попробуйте ещё раз.",
      loadCharts: "Не удалось загрузить графики. Попробуйте ещё раз.",
      loadEvents: "Не удалось загрузить события. Попробуйте ещё раз.",
      loadHealth: "Не удалось загрузить статус системы. Попробуйте ещё раз.",
    },
  },
  catalog: {
    header: {
      captionRoot: "Каталог",
      captionTotal: "категорий",
      captionPending: "на модерации",
    },
    addButton: "Добавить категорию",
    filters: {
      statusAria: "Статус категорий",
      status: {
        all: "Все",
        pending: "Модерация",
        approved: "Опубликовано",
        rejected: "Отклонено",
      },
      parentAll: "Все родители",
      parentRoot: "Корневые",
      searchPlaceholder: "Поиск по названию",
      parentLabel: "Родитель",
    },
    columns: {
      category: "Категория",
      parent: "Родительская",
      status: "Статус",
      services: "Услуг",
      providers: "Провайдеров",
      actions: "Действия",
    },
    status: {
      pending: "Ждёт модерации",
      approved: "Опубликовано",
      rejected: "Отклонено",
    },
    rowActions: {
      approve: "Подтвердить",
      reject: "Отклонить",
      edit: "Редактировать",
    },
    rejectDialog: {
      title: "Отклонить категорию",
      description: "Причина будет видна только администраторам.",
      reasonLabel: "Причина отклонения",
      reasonPlaceholder: "Например: дубликат существующей категории",
      cancel: "Отмена",
      confirm: "Отклонить",
      errorMinLength: "Минимум 3 символа",
      errorMaxLength: "Максимум 500 символов",
    },
    createDialog: {
      titleNew: "Новая категория",
      titleEdit: "Редактирование категории",
      nameLabel: "Название",
      namePlaceholder: "Например: Татуаж бровей",
      parentLabel: "Родительская категория",
      parentPlaceholder: "Без родителя",
      cancel: "Отмена",
      saveCreate: "Создать",
      saveEdit: "Сохранить",
      errorNameRequired: "Введите название категории.",
    },
    rootParent: "—",
    empty: {
      title: "Ничего не нашли",
      hint: "Попробуйте изменить фильтры или поиск.",
    },
    proposedBy: "Предложил",
    toasts: {
      created: "Категория создана",
      updated: "Изменения сохранены",
      approved: "Категория опубликована",
      rejected: "Категория отклонена",
      errorGeneric: "Не удалось выполнить действие. Попробуйте ещё раз.",
    },
  },
  cities: {
    header: {
      captionRoot: "Города",
      countsTotal: "всего",
      countsDups: "дублей",
    },
    findDuplicates: "Найти дубли",
    addCity: "Добавить город",
    providersWithoutCity: {
      title: "Провайдеры без города",
      hintSingle: "1 провайдер требует geocoding",
      hintPlural: "{count} провайдеров требуют geocoding",
    },
    filters: {
      statusAria: "Статус городов",
      status: {
        all: "Все",
        visible: "Видимые",
        hidden: "Скрытые",
        dup: "Дубли",
      },
      searchPlaceholder: "Город или регион",
    },
    columns: {
      city: "Город",
      masters: "Мастеров",
      studios: "Студий",
      visible: "Видим",
      actions: "Действия",
    },
    rowActions: {
      merge: "Слить с оригиналом",
      edit: "Редактировать",
      delete: "Удалить",
      toggleVisible: "Переключить видимость",
    },
    autoCreated: {
      tooltip: "Создан автоматически из адреса мастера",
    },
    duplicateMarker: {
      label: "Дубль",
    },
    empty: {
      title: "Ничего не нашли",
      hint: "Попробуйте изменить фильтры или поиск",
    },
    detail: {
      empty: {
        title: "Выберите город",
        hint: "Чтобы редактировать или объединить с другим",
      },
      caption: "Город",
      fields: {
        name: "Название",
        nameGenitive: "Родительный падеж",
        nameGenitiveHint: "Для «в Москве». Если пусто — используется именительный",
        latitude: "Широта",
        longitude: "Долгота",
        timezone: "Часовой пояс",
        sortOrder: "Порядок",
        sortOrderHint: "Меньше — выше в списке",
        isActive: "Видимый в каталоге",
        isActiveHint: "Иначе город скрыт от клиентов",
        autoCreated: "Проверен админом",
        autoCreatedHint:
          "Включите, если город проверен вручную. Иначе он будет помечен иконкой авто-создания.",
      },
      duplicate: {
        title: "Найден дубль",
        description:
          "Этот город — дубль «{canonicalName}». Слияние перенесёт всех мастеров и студий в оригинал, а этот город удалит.",
        mergeButton: "Слить с оригиналом",
      },
      actions: {
        save: "Сохранить",
        delete: "Удалить",
        close: "Закрыть",
      },
    },
    createDialog: {
      title: "Новый город",
      nameLabel: "Название",
      namePlaceholder: "Например: Калуга",
      slugLabel: "Slug",
      slugHint: "Авто-генерация из названия. Латиница, цифры, дефисы",
      slugEditMode: "Изменить вручную",
      nameGenitiveLabel: "Родительный падеж",
      latitudeLabel: "Широта",
      longitudeLabel: "Долгота",
      timezoneLabel: "Часовой пояс",
      sortOrderLabel: "Порядок",
      isActiveLabel: "Сразу видим",
      cancel: "Отмена",
      save: "Создать",
      errorName: "Укажите название",
      errorCoords: "Координаты должны быть числами",
    },
    mergeDialog: {
      title: "Объединить города",
      step1Title: "Выберите целевой город",
      step1Hint: "Все мастера и студии из «{source}» перейдут в выбранный город",
      targetLabel: "Целевой город",
      targetPlaceholder: "— Выберите —",
      step2Title: "Подтвердите объединение",
      step2Body:
        "{mastersCount} мастеров и {studiosCount} студий из «{source}» будут перенесены в «{target}». Город «{source}» будет удалён. Это действие нельзя отменить.",
      cancel: "Отмена",
      back: "Назад",
      next: "Далее",
      confirm: "Объединить",
    },
    deleteDialog: {
      title: "Удалить город",
      bodyEmpty: "Город «{name}» будет удалён. Это действие нельзя отменить.",
      bodyBlocked:
        "Нельзя удалить «{name}»: к городу привязано {count} провайдеров. Сначала смерджите его с другим или переназначьте провайдеров.",
      cancel: "Отмена",
      delete: "Удалить",
    },
    duplicateGroupsModal: {
      title: "Найденные дубли",
      reasonNormalize: "Одинаковое название после нормализации",
      reasonGeo: "Координаты ближе 5 км",
      canonicalBadge: "Каноничный",
      mergeIntoCanonical: "Слить с каноничным",
      empty: "Дублей не найдено",
    },
    toasts: {
      created: "Город добавлен",
      updated: "Изменения сохранены",
      deleted: "Город удалён",
      merged: "Города объединены",
      visibilityToggled: "Видимость изменена",
      errorBlockedDelete: "Нельзя удалить: есть привязанные провайдеры",
      errorGeneric: "Не удалось выполнить действие. Попробуйте ещё раз.",
    },
  },
  users: {
    header: {
      captionRoot: "Пользователи",
      countsTotal: "всего",
    },
    tiles: {
      all: "Все",
      client: "Клиент",
      master: "Мастер",
      studio: "Студия",
      admin: "Админ",
    },
    filters: {
      roleAll: "Все роли",
      planAll: "Все тарифы",
      searchPlaceholder: "Имя, email, телефон",
    },
    columns: {
      user: "Пользователь",
      contact: "Контакт",
      role: "Роль",
      plan: "Тариф",
      city: "Город",
      created: "Создан",
      actions: "Действия",
    },
    roleBadge: {
      client: "Клиент",
      master: "Мастер",
      studio: "Студия",
      studioAdmin: "Студия (админ)",
      admin: "Админ",
      superadmin: "Суперадмин",
    },
    plan: {
      tierFree: "Free",
      tierPro: "PRO",
      tierPremium: "Premium",
      scopeMaster: "Master",
      scopeStudio: "Studio",
      empty: "—",
      trial: "trial",
      pastDue: "PAST DUE",
      change: "Сменить тариф",
    },
    rowActions: {
      more: "Меню",
      viewSubscription: "Открыть подписку",
      changeTariff: "Сменить тариф",
    },
    planChange: {
      title: "Смена тарифа",
      userLabel: "Пользователь",
      currentLabel: "Текущий тариф",
      scopeLabel: "Контекст",
      tierLabel: "Новый тариф",
      periodLabel: "Период",
      periodMonths: {
        "1": "1 месяц",
        "3": "3 месяца",
        "6": "6 месяцев",
        "12": "12 месяцев",
      },
      reasonLabel: "Причина (для аудита)",
      reasonPlaceholder: "Например: компенсация за технический сбой",
      reasonHint: "Сохраняется в журнал. Видна только администраторам.",
      cancel: "Отмена",
      apply: "Применить тариф",
      sameTierWarning: "Этот тариф уже активен. Изменится только период.",
      unavailable: "Этот пользователь не имеет подписочного scope (не мастер и не студия).",
      planNotFound: "Тариф не найден",
      descriptions: {
        freeMaster: "Бесплатно · базовые функции мастера",
        proMaster: "Расширенные функции, аналитика",
        premiumMaster: "Все функции, без ограничений",
        freeStudio: "Бесплатно · базовый профиль студии",
        proStudio: "Команда мастеров, расширенные функции",
        premiumStudio: "Безлимитная команда, полная аналитика",
      },
    },
    empty: {
      title: "Никого не нашли",
      hint: "Попробуйте изменить фильтры или поиск",
    },
    pagination: {
      loadMore: "Загрузить ещё",
      loading: "Загружаем…",
    },
    toasts: {
      planChanged: "Тариф изменён",
      errorGeneric: "Не удалось выполнить действие. Попробуйте ещё раз.",
    },
  },
  billing: {
    header: {
      caption: "Финансы и тарифы",
    },
    kpi: {
      mrr: "MRR",
      mrrSubtitle: "к прошлому мес",
      activeSubs: "Активные подписки",
      activeSubsDelta: "за месяц",
      pending: "Платежи в обработке",
      pendingSubtitle: "сумма",
      failed7d: "Отказы за 7 дней",
      failed7dSuffix: "от попыток",
      noData: "—",
    },
    tabs: {
      navAria: "Разделы биллинга",
      plans: "Тарифы",
      subs: "Активные подписки",
      payments: "Платежи и история",
      comingSoonTooltip: "Доступно в следующем релизе",
    },
    plans: {
      featuredBadge: "POPULAR",
      pricePerMonth: "/ мес",
      priceFree: "Бесплатно",
      activeCountSuffix: "активных",
      editButton: "Редактировать",
      sectionMaster: "Для мастеров",
      sectionStudio: "Для студий",
      inactiveBadge: "Неактивен",
    },
    editDialog: {
      title: "Редактирование тарифа",
      tabs: {
        main: "Основное",
        features: "Возможности",
      },
      sections: {
        identity: "Идентификация",
        main: "Основное",
        prices: "Цены",
        inheritance: "Наследование",
      },
      fields: {
        codeLabel: "Код",
        tierLabel: "Уровень",
        scopeLabel: "Для кого",
        nameLabel: "Название",
        isActiveLabel: "Активен",
        isActiveHint: "Если выключить — план перестанет показываться пользователям, но существующие подписки сохранятся",
        sortOrderLabel: "Порядок",
        sortOrderHint: "Меньше — выше в списке",
        priceLabel: "{months} мес.",
        priceCurrency: "₽",
        // BILLING-PRICE-ACTIVE-UI-01 (R2-05-J): per-period isActive toggle.
        priceActiveLabel: "Активна",
        priceActiveHint:
          "Выключите, чтобы деактивировать цену без удаления строки. Чтобы совсем убрать период — обнулите цену.",
        priceEffectiveLabel: "Итоговая:",
        priceEffectiveNone: "нет цены",
        inheritsFromLabel: "Наследует от тарифа",
        inheritsFromNone: "Не наследует",
        inheritsFromHint: "Дочерний тариф получает все возможности родителя; здесь — только overrides поверх них.",
      },
      readonlyNote: "Код, уровень и scope нельзя менять через UI — это инвариантные идентификаторы плана.",
      cancel: "Отмена",
      save: "Сохранить",
      errorPriceInvalid: "Все цены должны быть целыми неотрицательными числами в рублях.",
      errorNameRequired: "Название не должно быть пустым.",
      errorPriceLastActive:
        "Нельзя деактивировать цену для периода {months} мес.: тариф останется без работающей цены на этот срок. Оставьте активной месячную цену (её берут за основу остальные сроки) или обнулите цену, чтобы убрать период.",
      disableConfirmTitle: "Приостановить тариф?",
      disableConfirmBody:
        "Тариф закроется для новых подписок. Активные подписчики сохранят доступ и получат уведомление об изменении — отозвать его нельзя. Затронуто подписчиков: {count}. Продолжить?",
      disableConfirmAction: "Приостановить",
    },
    features: {
      searchPlaceholder: "Поиск возможности…",
      shownCount: "Показано: {count}",
      nothingFound: "Ничего не найдено.",
      inheritedFrom: "Унаследовано из {planCode}",
      inheritedFromBase: "Унаследовано из базы",
      cannotDisableInherited: "Нельзя отключить, т.к. включено в базовом тарифе.",
      overriddenForPlan: "Переопределено для этого тарифа.",
      limitInheritedLocked: "Лимит унаследован, изменить нельзя.",
      limitOnlyRelaxParent: "Лимит можно только ослаблять относительно родителя.",
      limitStricter: "Значение строже родительского лимита.",
      unlimited: "Безлимит",
      unlimitedHint: "Без ограничений",
    },
    scope: {
      master: "Мастер",
      studio: "Студия",
    },
    tier: {
      free: "Free",
      pro: "PRO",
      premium: "Premium",
    },
    toasts: {
      planSaved: "Тариф сохранён",
      errorGeneric: "Не удалось сохранить. Попробуйте ещё раз.",
      subscriptionCancelled: "Подписка отменена",
      paymentRefunded: "Платёж возвращён",
      refundError: "Не удалось вернуть платёж. Попробуйте позже.",
      cancelError: "Не удалось отменить подписку. Попробуйте ещё раз.",
    },
    subs: {
      columns: {
        user: "Подписчик",
        plan: "Тариф",
        since: "Начало",
        next: "След. списание",
        amount: "Сумма",
        method: "Способ",
        autoRenew: "Автопродление",
        actions: "Действия",
      },
      autoRenewOn: "включено",
      autoRenewOff: "выключено",
      cancelButton: "Отменить подписку",
      statusBadge: {
        active: "Активна",
        pastDue: "Просрочена",
        cancelled: "Отменена",
        expired: "Истекла",
        pending: "Ожидание",
      },
      empty: {
        title: "Нет активных подписок",
        hint: "Подписки появятся, когда мастера или студии оплатят план.",
      },
      loadMore: "Загрузить ещё",
      loading: "Загружаем…",
    },
    payments: {
      pendingHeader: "Ожидают подтверждения",
      historyHeader: "История",
      columns: {
        id: "ID",
        date: "Дата",
        user: "Пользователь",
        amount: "Сумма",
        status: "Статус",
        method: "Способ",
        actions: "Действия",
      },
      status: {
        pending: "Ожидание",
        succeeded: "Успешно",
        failed: "Ошибка",
        canceled: "Отменён",
        refunded: "Возвращён",
      },
      refundButton: "Вернуть",
      empty: {
        title: "Нет платежей",
        hint: "История платежей появится после первой оплаты.",
      },
      pendingEmpty: "Нет ожидающих подтверждения платежей.",
      loadMore: "Загрузить ещё",
    },
    cancelDialog: {
      title: "Отменить подписку",
      body: "Подписка {user} ({plan}) будет отменена. Доступ сохранится до {until}. Это действие нельзя отменить.",
      bodyNoUntil: "Подписка {user} ({plan}) будет отменена.",
      reasonLabel: "Причина (для аудита)",
      reasonPlaceholder: "Например: запрос пользователя по email",
      cancel: "Отмена",
      confirm: "Отменить подписку",
    },
    refundDialog: {
      title: "Вернуть платёж",
      body: "Вернуть {amount}? Средства будут зачислены на оригинальный способ оплаты в течение 3-7 дней.",
      reasonLabel: "Причина (для аудита)",
      reasonPlaceholder: "Например: ошибка при оплате",
      cancel: "Отмена",
      confirm: "Вернуть",
    },
    methodFallback: "—",
  },
  reviews: {
    header: {
      caption: "Модерация",
      pendingSuffix: "жалоб ожидают",
    },
    kpi: {
      pendingReports: "Жалоб в очереди",
      pendingUrgentSuffix: "срочные",
      reviewsToday: "Отзывов за день",
      reviewsTodayDelta: "к среднему",
      averageRating: "Средняя оценка",
      averageRatingSubtitle: "по платформе",
      deletedLastWeek: "Удалено за неделю",
      deletedLastWeekContext: "из {total}",
      noData: "—",
    },
    tabs: {
      flagged: "Жалобы",
      low: "Низкие оценки",
      all: "Все",
    },
    filters: {
      tabsAria: "Какие отзывы показать",
      searchPlaceholder: "Поиск по тексту, автору, мастеру",
    },
    card: {
      onTargetPrefix: "На",
      reportedBadge: "Зарепортено",
      urgentBadge: "Срочно",
      reportLabel: "Причина жалобы",
      reportCommentLabel: "Комментарий",
      noReports: "Без жалоб",
      authorDeleted: "Удалённый аккаунт",
      targetMaster: "мастера",
      targetStudio: "студию",
      replyBadge: "Есть ответ мастера",
    },
    reportReasons: {
      SPAM: "Спам",
      FAKE: "Подкуплено",
      OFFENSIVE: "Оскорбления",
      INAPPROPRIATE: "Неприемлемо",
      OTHER: "Другое",
    },
    actions: {
      approve: "Одобрить",
      delete: "Удалить",
    },
    approveDialog: {
      title: "Одобрить отзыв",
      body: "Жалобы будут сняты, отзыв вернётся к публичному показу. Действие нельзя отменить.",
      cancel: "Отмена",
      confirm: "Одобрить",
    },
    deleteDialog: {
      title: "Удалить отзыв",
      body: "Отзыв от {author} будет удалён. Действие нельзя отменить.",
      warning:
        "Отзыв скрывается с публичных страниц и перестаёт учитываться в рейтинге мастера или студии.",
      reasonLabel: "Причина (для аудита)",
      reasonPlaceholder: "Например: грубое нарушение правил платформы",
      cancel: "Отмена",
      confirm: "Удалить",
    },
    empty: {
      flaggedTitle: "Нет жалоб",
      flaggedHint: "Все отзывы прошли модерацию.",
      lowTitle: "Нет низких оценок",
      lowHint: "Мастера держат высокие оценки.",
      allTitle: "Нет отзывов",
      allHint: "Отзывы появятся после первых записей.",
    },
    pagination: {
      loadMore: "Загрузить ещё",
    },
    toasts: {
      approved: "Отзыв одобрен",
      deleted: "Отзыв удалён",
      errorGeneric: "Не удалось выполнить действие. Попробуйте ещё раз.",
    },
  },
  settings: {
    header: {
      caption: "Настройки системы",
      title: "Глобальные параметры платформы",
    },
    sections: {
      logo: {
        title: "Логотип сайта",
        desc: "Используется в navbar рядом с МастерРядом",
        hint: "PNG · 256×256 · до 2 МБ",
      },
      loginHero: {
        title: "Фото для страницы входа",
        desc: "Большое изображение в левой части страницы входа",
      },
      flags: {
        title: "Системные флаги",
        desc: "Глобальные переключатели функций платформы",
        saveButton: "Сохранить флаги",
        savingLabel: "Сохраняем…",
        savedLabel: "Сохранено",
        errorLabel: "Не удалось сохранить. Попробуйте ещё раз.",
        dirtyHint: "Есть несохранённые изменения",
        flags: {
          onlinePaymentsEnabled: {
            label: "Онлайн-оплата включена",
            desc: "Можно ли оплачивать запись картой",
          },
          visualSearchEnabled: {
            label: "Визуальный поиск включён",
            desc: "Поиск по фото работ — индексация и выдача",
          },
          legalDraftMode: {
            label: "Юр. документы в режиме черновика",
            desc: "Баннер «Черновик» на страницах Условий и Конфиденциальности",
          },
          telegramEnabled: {
            label: "Telegram включён",
            desc: "Вход, привязка и уведомления через Telegram. Переключатель работает только если Telegram сконфигурирован в окружении (задан username бота). Если в окружении не настроен — остаётся выключенным.",
          },
        },
      },
      // VK-COMMUNITY-NOTIFY-01: ключ доступа сообщества — без env-переменной,
      // сообщество берётся из ссылки NEXT_PUBLIC_VK_COMMUNITY_URL.
      vkCommunity: {
        title: "Сообщество ВКонтакте",
        desc: "Уведомления во ВКонтакте уходят личными сообщениями от имени сообщества из ссылки в футере. Для этого нужен ключ доступа сообщества.",
        communityLabel: "Сообщество",
        urlMissing: "Ссылка на сообщество не задана — задайте NEXT_PUBLIC_VK_COMMUNITY_URL.",
        urlUnrecognized: "Ссылка на сообщество не похожа на адрес сообщества ВКонтакте.",
        statusConnected: "Ключ сохранён",
        statusNotConnected: "Ключ не задан",
        statusBroken: "Ключ не работает",
        sendsAs: (name: string) => `Уведомления уходят от имени «${name}»`,
        mismatch: "Сохранённый ключ выдан другому сообществу. Введите ключ сообщества из ссылки.",
        unreadable: "Сохранённый ключ не читается — скорее всего, сменился AUTH_JWT_SECRET. Введите ключ заново.",
        stepsTitle: "Как получить ключ",
        steps: [
          "Откройте vk.com на компьютере — в приложении ВКонтакте этого раздела нет. Нужны права администратора сообщества.",
          "Сообщество → Управление → Сообщения: включите сообщения сообщества.",
          "Там же «Настройки для бота»: включите возможности ботов и кнопку «Начать».",
          "Управление → Дополнительно → Работа с API → Ключи доступа → Создать ключ. Отметьте право «Сообщения сообщества».",
          "Скопируйте ключ и вставьте его ниже.",
        ],
        tokenLabel: "Ключ доступа сообщества",
        tokenPlaceholder: "vk1.a.…",
        tokenHint: "При сохранении ключ проверяется во ВКонтакте и хранится зашифрованным. Показать его снова нельзя — только заменить.",
        saveButton: "Сохранить ключ",
        removeButton: "Удалить ключ",
        savingLabel: "Проверяем ключ…",
        removingLabel: "Удаляем ключ…",
        savedLabel: "Ключ сохранён",
        removedLabel: "Ключ удалён",
        errorLabel: "Не удалось сохранить ключ. Попробуйте ещё раз.",
        removeErrorLabel: "Не удалось удалить ключ. Попробуйте ещё раз.",
      },
      seo: {
        title: "SEO-настройки",
        desc: "Заголовок и описание для поисковых систем",
        titleLabel: "SEO-заголовок",
        titlePlaceholder: "МастерРядом — мастера красоты онлайн",
        descriptionLabel: "SEO-описание",
        descriptionPlaceholder: "Маркетплейс мастеров красоты. Запись онлайн, отзывы, прозрачные цены.",
        saveButton: "Сохранить",
        savingLabel: "Сохраняем…",
        savedLabel: "Сохранено",
        errorLabel: "Не удалось сохранить. Попробуйте ещё раз.",
      },
      queue: {
        title: "Очередь задач",
        desc: "Статус и управление фоновой очередью задач",
        refreshButton: "Обновить",
        refreshingLabel: "Обновляем…",
        tiles: {
          pending: "В очереди",
          processing: "Обрабатывается",
          dead: "Мёртвых задач",
        },
        deadJobsTitle: "Мёртвые задачи",
        deadJobsEmpty: "Мёртвых задач нет.",
        retry: "Перезапустить",
        retrying: "Перезапуск…",
        delete: "Удалить",
        retryFailed: "Не удалось перезапустить. Попробуйте ещё раз.",
        deleteFailed: "Не удалось удалить. Попробуйте ещё раз.",
        loadFailed: "Не удалось загрузить очередь. Попробуйте ещё раз.",
      },
      visualSearch: {
        title: "Визуальный поиск",
        desc: "Статистика индексации и запуск переиндексации",
        runIndexButton: "Запустить индексацию",
        runningIndexLabel: "Запускаем индексацию…",
        startedToast: "Индексация запущена",
        tiles: {
          total: "Всего фото",
          indexed: "Проиндексировано",
          notIndexed: "Не проиндексировано",
        },
        disabledHint: "Флаг «Визуальный поиск» выключен. Включите его выше, чтобы индексация работала.",
        loadFailed: "Не удалось загрузить статистику. Попробуйте ещё раз.",
        runFailed: "Не удалось запустить индексацию. Попробуйте ещё раз.",
        empty: "Нечего индексировать — все портфолио уже обработаны.",
      },
      mediaCleanup: {
        title: "Медиа-очистка",
        desc: "Устаревшие и «битые» медиафайлы",
        runCleanupButton: "Запустить очистку",
        runningCleanupLabel: "Очищаем…",
        doneToast: "Очистка завершена",
        tiles: {
          pending: "Записи pending",
          broken: "Битые ссылки",
        },
        empty: "Ничего убирать не нужно — медиа-каталог чистый.",
        loadFailed: "Не удалось загрузить статистику. Попробуйте ещё раз.",
        runFailed: "Не удалось запустить очистку. Попробуйте ещё раз.",
      },
    },
    toasts: {
      seoSaved: "SEO-настройки сохранены",
      flagsSaved: "Флаги сохранены",
      errorGeneric: "Не удалось сохранить. Попробуйте ещё раз.",
    },
  },
} as const;
