export const bookingWidget = {
  backToStudio: "К странице студии",
  hero: {
    studioLabel: "Студия",
    bookingToMaster: "Записываетесь к",
    mastersCount: "{count} мастеров",
    teamPick: "Команда",
    teamPickHint: "выбрать мастера",
    ratingLabel: "{rating} · {reviews} отзывов",
  },
  steps: {
    stepLabel: "Шаг {n}",
    ariaLabel: "Шаги записи",
    service: "Услуга",
    master: "Мастер",
    when: "Когда",
    you: "Вы",
  },
  serviceStep: {
    titleStudio: "Какую услугу выбираем?",
    subtitleStudio: "{count} услуг от команды",
    titleMaster: "Что хотите сделать у {master}?",
    subtitleMaster: "Только то, что делает мастер",
    searchPlaceholder: "Найти услугу — «маникюр», «балаяж»…",
    searchEmpty: "Ничего не нашлось. Попробуйте по-другому.",
    catAll: "Всё",
    categoryOther: "Другие услуги",
    pick: "Выбрать",
    noServices: "Услуги пока не добавлены",
    noServicesMaster: "У мастера пока нет услуг в этой студии",
    priceOnRequest: "Цена по запросу",
    duration: "{min} мин",
    durationHours: "{h} ч",
    durationHoursMin: "{h} ч {m} мин",
  },
  masterStep: {
    title: "Кто из мастеров?",
    subtitle: "Все делают «{service}»",
    anyMaster: "Любой свободный",
    anyMasterSub: "по ближайшему окошку",
    pickThis: "Выбрать",
    noMasters: "По выбранной услуге пока нет доступных мастеров.",
    back: "Назад к услуге",
  },
  whenStep: {
    title: "Когда вам удобно?",
    subtitleMaster: "Свободное время {master}",
    subtitleAny: "Ближайшие окошки команды",
    morning: "Утро",
    day: "День",
    evening: "Вечер",
    noSlots: "На эту дату свободных окошек нет.",
    back: "Назад",
    today: "Сегодня",
    tomorrow: "Завтра",
    daysOfWeek: ["вс", "пн", "вт", "ср", "чт", "пт", "сб"],
    months: ["янв", "фев", "мар", "апр", "мая", "июня", "июля", "авг", "сен", "окт", "ноя", "дек"],
    // FIX-BATCH-C Defect 1 (QA-107/FIX-22): slot times are shown in the SALON's
    // timezone; this note + «(город, GMT+N)» label clarifies that for a cross-tz client.
    salonTimeNote: "Время салона",
  },
  youStep: {
    title: "Последний шаг",
    subtitleGuest: "Оставьте контакты — мы напомним о записи",
    subtitleAuth: "Проверьте детали и подтвердите",
    nameLabel: "Как к вам обращаться?",
    // FIX-NAME-HINT: см. `common.ownNameHint` — подсказка под полем.
    namePlaceholder: "Фамилия и имя",
    phoneLabel: "Телефон",
    phonePlaceholder: "+7 999 000 00 00",
    silentLabel: "Хочу помолчать",
    silentHint: "Мастер поздоровается, уточнит детали и будет работать молча.",
    commentLabel: "Комментарий",
    commentPlaceholder: "Что-то важное — расскажите",
    back: "Назад",
    loginHint: "Уже есть аккаунт?",
    loginCta: "Войти",
  },
  summary: {
    title: "Ваша запись",
    badgeService: "Выберите услугу",
    badgeMaster: "Выберите мастера",
    badgeWhen: "Выберите дату и время",
    badgeYou: "Заполните контакты",
    badgeReady: "Готово к записи",
    rowService: "Услуга",
    rowMaster: "Мастер",
    rowWhen: "Когда",
    empty: "не выбрана",
    emptyM: "не выбран",
    emptyW: "не выбрано",
    anyMaster: "любой свободный",
    total: "Итого к оплате",
    submit: "Записаться",
    submitDisabled: "Заполните все шаги",
    submitting: "Создаём запись…",
    freeCancelTemplate: "Бесплатная отмена за {hours} ч",
    freeCancelHint: "Мы напомним о записи",
    // FIX-BATCH-C Defect 1: salon-tz note in the summary (mirrors whenStep).
    salonTimeNote: "Время салона",
  },
  errors: {
    // FIX-25 (QA-106): SLOT_CONFLICT covers both "taken" and off-schedule
    // (outside working hours / day-off) — the old «только что заняли» falsely
    // implied someone took it. Plain "not available, pick another" reads
    // correctly for both.
    slotTaken: "Это время уже занято. Выберите другое свободное окошко.",
    tooSoon: "Записаться нужно минимум за {hours} ч. Выберите время позже.",
    tooFar: "Записаться можно максимум на {days} дней вперёд.",
    newClientsClosed: "Мастер временно не принимает новых клиентов.",
    forbidden: "Записаться к самому себе нельзя.",
    generic: "Не удалось создать запись. Попробуйте ещё раз.",
    networkGeneric: "Не удалось связаться с сервером. Попробуйте ещё раз.",
  },
  success: {
    title: "Вы записаны",
    detailsTemplate: "{service} · {master} · {when}",
    hint: "Мы пришлём напоминание перед визитом.",
    backToStudio: "Вернуться к странице студии",
  },
  progressLabel: "{done} из {total}",
} as const;
