import { pluralize } from "@/lib/utils/pluralize";

export const cabinet = {
  // VISIBILITY-CATALOG-STATUS: есть ли кабинет в каталоге и чего не хватает.
  catalogPresence: {
    listedMaster: "Вы в каталоге — клиенты находят вас в поиске.",
    listedStudio: "Студия в каталоге — клиенты находят её в поиске.",
    notListedPrefix: "Пока не в каталоге:",
    gapsMaster: {
      hidden: "включите видимость",
      address: "укажите адрес с городом",
      schedule: "настройте рабочие дни",
    },
    gapsStudio: {
      hidden: "включите видимость",
      address: "укажите адрес с городом",
      schedule: "нужен хотя бы один мастер с рабочими днями",
    },
    statusListed: "В каталоге",
    statusHidden: "Скрыт из каталога",
    statusIncomplete: "Не в каталоге",
  },
  trial: {
    badgePrefix: "PREMIUM",
    bannerTitleTomorrow: "Пробный период заканчивается завтра",
    bannerTitleToday: "Пробный период заканчивается сегодня",
    bannerTitleMultiDays: "Пробный период заканчивается через {countDays}",
    bannerDescription: "Оформите подписку, чтобы сохранить расширенные возможности",
    bannerCta: "Перейти к тарифам",
    bannerDismiss: "Закрыть",
  },
  master: {
    schedule: {
      pageTitle: "Расписание",
      pageSubtitle: "Настройте свой график",
      baseWeek: "График недели",
      templateLabel: "Шаблон недели",
      templateCustom: "Свой график",
      dayNames: [
        "Понедельник",
        "Вторник",
        "Среда",
        "Четверг",
        "Пятница",
        "Суббота",
        "Воскресенье",
      ],
      dayShortNames: [
        "Пн",
        "Вт",
        "Ср",
        "Чт",
        "Пт",
        "Сб",
        "Вс",
      ],
      workday: "Рабочий день",
      dayOff: "Выходной",
      flexible: "Гибкое время",
      fixed: "Фиксированное время",
      fixedHint: "Клиенты смогут записаться только в эти часы",
      addBreak: "+ Добавить перерыв",
      addSlot: "+ Добавить окошко",
      copyToDays: "Скопировать на другие дни…",
      copyModalTitle: "Скопировать на дни",
      applyException: "Сохранить день",
      resetToBase: "Вернуть по графику недели",
      makeHoliday: "Сделать выходным",
      makeWorkday: "Сделать рабочим",
      exceptionApplied: "День настроен отдельно",
      futureExceptions: "Особые дни впереди",
      noExceptions: "Особых дней пока нет",
      legendFlexible: "Гибкий",
      legendFixed: "Фиксированный",
      legendException: "Особый день",
      calendar: "Календарь",
      loading: "Загрузка…",
      saved: "Сохранено",
      save: "Сохранить",
      saving: "Сохраняем…",
      cancel: "Отмена",
      add: "Добавить",
      shiftPrefix: "Смена",
      customLabel: "Свой",
      templateLabelShort: "Шаблон",
      byDateTemplateLabel: "Шаблон по дате",
      errors: {
        load: "Не удалось загрузить расписание. Попробуйте ещё раз.",
        loadOverrides: "Не удалось загрузить особые дни. Попробуйте ещё раз.",
        saveWeek: "Не удалось сохранить график. Попробуйте ещё раз.",
        saveException: "Не удалось сохранить особый день. Попробуйте ещё раз.",
        deleteException: "Не удалось удалить особый день. Попробуйте ещё раз.",
        loadDayBookings: "Не удалось загрузить записи дня. Попробуйте ещё раз.",
        submitRequest: "Не удалось отправить график на согласование. Попробуйте ещё раз.",
        templateNameRequired: "Укажите название шаблона.",
        timeRangeRequired: "Укажите время начала и окончания.",
        invalidSlotTime: "Проверьте время окошка — например, 10:30.",
      },
      info: {
        savedWeek: "График сохранён.",
        requestSubmitted: "Изменения отправлены на согласование.",
        noChanges: "Изменений нет.",
        resetDone: "Изменения сброшены.",
      },
      studioMaster: {
        pendingRequest: "Изменения по графику ожидают согласования студии.",
        submitForApproval: "Изменения по графику отправляются на согласование студии и не применяются сразу.",
        lastCommentPrefix: "Последний комментарий студии:",
      },
      builder: {
        loading: "Загружаем график…",
        pendingReadonly: "Ваш новый график на проверке у администратора. Редактирование временно недоступно.",
        requestRejected: "Запрос отклонён.",
        commentLabel: "Комментарий",
        submitHintStudio: "Изменения отправляются на согласование администратора студии.",
        submitHintSolo: "Сохраните изменения, чтобы обновить график.",
        settingsTitle: "Настройки",
        settingsSubtitle: "Шаблоны, неделя и особые дни.",
        tabs: {
          templates: "Шаблоны",
          week: "Неделя",
          overrides: "Особые дни",
        },
        breaksPrefix: "Перерывы",
        editTemplate: "Редактировать",
        editTemplateTitle: "Редактирование шаблона",
        createTemplateTitle: "Новый шаблон",
        templateNamePlaceholder: "Название шаблона",
        breaksLimit: "Перерывы (до 3)",
        addBreak: "+ Перерыв",
        addTemplate: "Добавить шаблон",
        templateLimitReached: "Больше 7 шаблонов не получится — удалите ненужный.",
        noTemplateOption: "Нет шаблона",
        noOverrides: "Особых дней пока нет.",
        calendarTitle: "Календарь",
        calendarSubtitle: "Неделя и особые дни.",
        dayActionsTitle: "Действия с днём",
        basedOnPlan: "По графику недели:",
        overrideLabel: "Особый день",
        editTimeTitle: "Изменить время",
        breaksTitle: "Перерывы",
        saveTime: "Сохранить время",
        applyFromTemplate: "Подставить из шаблона",
        resetChanges: "Сбросить изменения",
        submitForApproval: "Отправить на согласование",
        saveSchedule: "Сохранить график",
        sending: "Отправляем…",
        deleteWindowAria: "Удалить окно",
        deleteBreakAria: "Удалить перерыв",
        deleteOverrideAria: "Удалить особый день",
      },
      baseStatusWorkflexible: (start: string, end: string) => `Рабочий (${start}–${end})`,
      baseStatusWorkFixed: "Рабочий (фиксированное время)",
      baseStatusHoliday: "Выходной",
      changeThisDay: "Настроить этот день",
      editDayAria: "Изменить график",
      backToDayAria: "К дню",
      dayBookingsTitle: "Записи на день",
      addBookingCta: "+ Добавить запись",
      dayFreeState: "Записей нет. День свободен.",
      offDayConflictTitle: (count: number) =>
        `На этот день уже есть ${count} ${pluralize(count, "запись", "записи", "записей")}. Если сделать его выходным, записи нужно будет перенести или отменить.`,
      offDayConflictCannotAutoCancel: "— нельзя отменить автоматически",
      offDayConflictConfirm: "Отменить записи и сделать выходным",
      offDayConflictKeep: "Оставить как есть",
      bookingStatus: {
        pending: "Ожидает подтверждения",
        confirmed: "Подтверждено",
        changeRequested: "Запрошен перенос",
        inProgress: "В процессе",
        finished: "Завершено",
        cancelled: "Отменено",
      },
    },
  },
} as const;
