import { pluralize } from "@/lib/utils/pluralize";

export const catalog = {
  capsule: {
    servicePlaceholder: "Маникюр, массаж, стрижка…",
    districtPlaceholder: "Район",
    datePlaceholder: "Дата",
    find: "Найти",
  },
  timeSearch: {
    morning: "Утро",
    day: "День",
    evening: "Вечер",
    custom: "Свой диапазон",
    from: "С",
    to: "По",
    freeInTime: "Свободно в выбранное время",
    emptyTitle: "Свободных окошек нет",
    emptyDesc: "Попробуйте другой диапазон времени или дату.",
    loadFailed: "Не удалось подобрать окошки. Попробуйте ещё раз.",
  },
  chips: {
    price: "Цена",
    availableToday: "Свободно сегодня",
    rating45plus: "⭐ 4.5+",
      hot: "Горящее",
    studios: "Студии",
    privateMasters: "Частные мастера",
    priceMinPlaceholder: "Мин",
    priceMaxPlaceholder: "Макс",
    apply: "Показать",
    reset: "Сбросить",
  },
  sidebar: {
    title: "Фильтры",
    categories: "Категория",
    district: "Район",
    districtPlaceholder: "Введите район или улицу",
    districtClear: "Очистить район",
    districtSuggestFailed: "Не удалось загрузить подсказки. Попробуйте ещё раз.",
    rating: "Рейтинг",
    ratingAny: "Любой",
    hot: "Горящие окошки",
    availableToday: "Свободно сегодня",
    entityType: "Кто принимает",
    entityAll: "Все",
    entityMaster: "Мастер",
    entityStudio: "Студия",
    reset: "Сбросить всё",
    apply: "Показать",
    filtersButton: "Фильтры",
    activeFiltersCount: (n: number) => `${n}`,
  },
  resultsCount: "Нашлось",
  viewList: "Список",
  viewMap: "На карте",
  priceFrom: "от",
  priceAllIncluded: "всё включено",
  priceOnRequest: "Цена по запросу",
  noSlots: "Окошек нет",
  nextSlotLabel: "Ближайшее окошко",
  todaySlotsLabel: "Окошки сегодня",
  reviewsLabel: "отзывов",
  newLabel: "Новый",
  mapPlaceholderTitle: "Карта скоро появится",
  mapPlaceholderDesc: "Мы её готовим — пока смотрите список.",
  mapPointsTitle: "Точки на карте",
  carouselPrev: "Предыдущее фото",
  carouselNext: "Следующее фото",
  highlightBadge: "PREMIUM",
  loadMore: "Показать ещё",
  loading: "Загружаем каталог…",
  loadFailed: "Не удалось загрузить каталог. Попробуйте ещё раз.",
  emptyTitle: "По этому запросу никого не нашли",
  emptyDesc: "Измените фильтры или поищите в другом районе.",
  retry: "Повторить",
  book: "Записаться",
  map: {
    loading: "Загружаем карту…",
    loadFailed: "Не удалось загрузить карту. Попробуйте ещё раз.",
    retry: "Повторить",
    updatingResults: "Обновляем результаты…",
    emptyArea: "Здесь пока никого нет. Передвиньте карту или измените фильтры.",
    geoAccessDenied: "Разрешите доступ к геолокации, чтобы показывать мастеров рядом с вами.",
    geoError: "Не удалось определить местоположение. Попробуйте ещё раз.",
    searchArea: "Искать в этой области",
    myLocation: "Показать, где я",
    ratingHint: (title: string, rating: number) => `${title} • Рейтинг ${rating.toFixed(1)}`,
    carouselAria: "Мастера на карте",
    missingTail: (count: number) =>
      `Ещё ${count} ${pluralize(count, "мастер", "мастера", "мастеров")} без адреса на карте`,
    showInList: "Смотреть списком",
  },
} as const;
