export const clientCabinet = {
  // Отклики клиента на модель-офферы (29.09 доработки · 11).
  modelApplications: {
    loadFailed: "Не удалось загрузить заявки. Попробуйте ещё раз.",
    confirmFailed: "Не удалось подтвердить время. Попробуйте ещё раз.",
  },
  shell: {
    title: "Кабинет клиента",
    profileSubtitle: "Личные данные и настройки.",
    bookingsSubtitle: "Ваши предстоящие и прошлые записи.",
  },
  settings: {
    title: "Настройки",
    subtitle: "Ваш профиль и настройки.",
  },
  common: {
    profile: "Профиль",
    myBookings: "Мои записи",
    save: "Сохранить",
    phone: "Телефон",
  },
  telegram: {
    sectionTitle: "Подключенные аккаунты",
    sectionSubtitle: "Выберите, куда присылать уведомления.",
    title: "Уведомления в Telegram",
    connected: "Подключено",
    notConnected: "Не подключено",
    enabled: "Уведомления включены",
    disabled: "Уведомления выключены",
    hint: "Если бот перестал писать — откройте чат с ботом и нажмите Start.",
    connectButton: "Подключить",
    connectModalTitle: "Подключение Telegram",
    connectModalDescription:
      "Нажмите «Открыть Telegram», затем запустите бота кнопкой Start, чтобы связать уведомления.",
    connectModalExpiresAt: "Ссылка действует до {datetime}.",
    connectModalOpen: "Открыть Telegram",
    connectModalCheck: "Проверить подключение",
    connectModalClose: "Закрыть",
    loadFailed: "Не удалось проверить подключение Telegram. Попробуйте ещё раз.",
    linkFailed: "Не удалось получить ссылку Telegram. Попробуйте ещё раз.",
    settingsFailed: "Не удалось обновить настройки. Попробуйте ещё раз.",
  },
  booking: {
    pending: "Ожидает",
    confirmed: "Подтверждено",
    cancelled: "Отменено",
    // NO-SHOW-UI: неявка — не отмена, у клиента свой бейдж.
    noShow: "Неявка",
    today: "Сегодня",
    inProgress: "В процессе",
    finished: "Завершено",
    changeRequested: "Ожидает подтверждения",
    // RESCHEDULE-CLIENT-APPROVAL: мастер предложил перенос — ход за клиентом.
    needsYourAnswer: "Нужен ваш ответ",
    waitsMaster: "Ожидает подтверждения мастера",
    goToMaster: "К мастеру",
    goToStudio: "К студии",
    masterLabel: "Мастер",
    studioLabel: "Студия",
    chatToggle: "Чат",
    deleteReviewFailed: "Не удалось удалить отзыв. Попробуйте ещё раз.",
    confirmFailed: "Не удалось подтвердить запись. Попробуйте ещё раз.",
    chooseDate: "Выберите дату",
    chooseTime: "Выберите время",
    noSlots: "Свободных окошек нет",
    loadSlotsFailed: "Не удалось загрузить окошки. Попробуйте ещё раз.",
    submitFailed: "Не удалось создать запись. Попробуйте ещё раз.",
    chooseCorrectSlot: "Выберите свободное окошко",
    morning: "Утро",
    day: "День",
    evening: "Вечер",
    moveBooking: "Перенести запись",
    moveBookingHint: "Выберите новую дату и окошко.",
    moveConfirm: "Подтвердить перенос",
    moving: "Переносим…",
  },
  bookingsPanel: {
    loading: "Загружаем записи",
    empty: "Записей пока нет — самое время найти мастера.",
    emptyFiltered: "Нет записей по выбранному фильтру.",
    failedToLoad: "Не удалось загрузить записи. Попробуйте ещё раз.",
    failedToCancel: "Не удалось отменить запись. Попробуйте ещё раз.",
    reschedule: "Перенести",
    cancelBooking: "Отменить запись",
    leaveReview: "Оставить отзыв",
    reviewSubmitted: "Отзыв оставлен",
    filterAll: "Все",
    filterToday: "Сегодня",
    filterUpcoming: "Предстоящие",
    filterFinished: "Завершённые",
    filterCancelled: "Отменённые",
  },
  profile: {
    // Итог подключения Telegram (`?telegram=…` после возврата), 29.09 · 10.
    telegramConnected: "Telegram подключён.",
    telegramConflict: "Этот Telegram-аккаунт уже привязан к другому аккаунту.",
    telegramUnconfigured: "Подключение Telegram временно недоступно. Попробуйте позже.",
    telegramConnectFailed: "Не удалось подключить Telegram. Попробуйте ещё раз.",
    unlinkFailed: "Не удалось отвязать аккаунт. Попробуйте ещё раз.",
    subtitle: "Личные данные и контактная информация",
    saveFailed: "Не удалось сохранить. Попробуйте ещё раз.",
    networkError: "Сеть недоступна или сервер не отвечает",
    saved: "Сохранено",
    createMasterFailed: "Не удалось создать профиль мастера. Попробуйте ещё раз.",
    masterCreated: "Профиль мастера создан",
    createStudioFailed: "Не удалось создать студию. Попробуйте ещё раз.",
    studioCreated: "Студия создана",
    description: "О себе, услугах и портфолио",
    professionalRolesTitle: "Мои профессиональные роли",
    rolesAddedCanAddMore:
      "Вы уже добавили профессиональные роли. Можно добавить ещё.",
    stillClientAddRole:
      "Вы пока клиент. Добавьте роль мастера или студии.",
    alreadyMaster: "Вы уже мастер",
    becomeMaster: "Стать мастером",
    creatingMaster: "Создаём профиль мастера…",
    alreadyStudioOwner: "Вы уже владелец студии",
    createStudio: "Создать студию",
    creatingStudio: "Создаём студию…",
    lastName: "Фамилия",
    lastNamePlaceholder: "Иванов",
    firstName: "Имя",
    firstNamePlaceholder: "Иван",
    middleName: "Отчество",
    middleNamePlaceholder: "Иванович",
    name: "Имя",
    namePlaceholder: "Как вас зовут?",
    displayName: "Имя",
    displayNamePlaceholder: "Как вас зовут?",
    email: "Почта",
    birthDate: "Дата рождения",
    address: "Адрес",
    addressPlaceholder: "Город, улица, дом…",
    mapHint:
      "Адрес покажем в вашем профиле и в каталоге.",
    rolesLabel: "Роли:",
    saving: "Сохраняем…",
    profileSectionTitle: "Личные данные",
    profileSectionSubtitle: "Основная информация, которая отображается в вашем профиле.",
    integrationsTitle: "Подключенные аккаунты",
    integrationsSubtitle: "Выберите, куда присылать уведомления.",
    securityTitle: "Безопасность",
    securitySubtitle: "Вход и безопасность аккаунта.",
    securityHint: "Проверьте, куда приходят уведомления и с какого номера вы входите.",
    phonePlaceholder: "+7 (___) ___-__-__",
    emailPlaceholder: "mail@example.com",
  },
  nav: {
    sectionLabel: "Кабинет",
    sectionEyebrow: "Мой кабинет",
    home: "Главная",
    bookings: "Мои записи",
    messages: "Сообщения",
    profile: "Профиль",
    settings: "Настройки",
    roles: "Роли",
    modelApplications: "Заявки моделью",
    favorites: "Избранное",
    reviews: "Мои отзывы",
    notifications: "Уведомления",
    faq: "Поддержка и частые вопросы",
    more: "Ещё",
    groupActivity: "Активность",
    groupAccount: "Аккаунт",
    backToFeed: "В ленту",
    bookNow: "Записаться",
  },
  favorites: {
    removeFailed: "Не удалось убрать из избранного. Попробуйте ещё раз.",
    openProfileAria: "Открыть профиль",
    aboutStudioAria: "О студии",
    removeFromFavoritesAria: "Убрать из избранного",
    tabMasters: "Мастера",
    tabStudios: "Студии",
    tabsAria: "Мастера или студии",
    sortRecent: "Сначала недавние",
    sortRating: "По рейтингу",
    sortAria: "Порядок",
    sortVisits: "По числу визитов",
    countLabel: (n: number) => `${n} в избранном`,
    eyebrow: "Личное",
    title: "Избранные мастера",
    descriptionEmpty: "Здесь будут мастера, которых вы сохраните.",
    descriptionTemplate: "Сохранено: {count}",
    empty: {
      title: "Список пока пустой",
      description:
        "Сохраняйте мастеров в каталоге — они появятся здесь, чтобы вы могли быстро найти их в будущем.",
      cta: "В каталог",
    },
    // TODO (follow-up commit): enrich saved-list cards with `nextSlot` and
    // `todaySlotsCount` so they match the catalog's UX. Today we render a
    // minimal mapping (no slot indicator, no portfolio carousel).
  },
  dashboard: {
    greeting: (name: string) => `Здравствуйте, ${name}`,
    greetingDefault: "Рады вас видеть",
    findMaster: "Найти мастера",
    nextBookingTitle: "Ближайшая запись",
    noUpcomingTitle: "Нет предстоящих записей",
    noUpcomingCta: "Записаться к мастеру",
    rebookTitle: "Записаться снова",
    recentTitle: "Недавние записи",
    allBookings: "Все записи",
    bookingToday: (time: string) => `Сегодня в ${time}`,
    bookingTomorrow: (time: string) => `Завтра в ${time}`,
    bookingInDays: (n: number) =>
      `Через ${n} ${n === 1 ? "день" : n < 5 ? "дня" : "дней"}`,
    bookingInHours: (n: number) =>
      `Через ${n} ${n === 1 ? "час" : n < 5 ? "часа" : "часов"}`,
    loading: "Загружаем ваш кабинет…",
    loadFailed: "Не удалось загрузить данные. Попробуйте ещё раз.",
    reschedule: "Перенести",
    cancel: "Отменить",
  },
  bookingsPage: {
    title: "Мои записи",
    subtitle: "История и предстоящие визиты",
    kpiAll: "Всего записей",
    kpiUpcoming: "Ближайшая",
    kpiFinished: "Состоялось",
    kpiSpent3m: "Потрачено за 3 мес.",
    filterAria: "Статус записей",
    filterAll: "Все",
    filterUpcoming: "Предстоящие",
    filterFinished: "Состоявшиеся",
    filterCancelled: "Отменённые",
    searchPlaceholder: "Поиск по мастеру или услуге…",
    actionChat: "Чат",
    actionReschedule: "Перенести",
    actionIcs: "В календарь",
    actionRoute: "Маршрут",
    actionCancel: "Отменить",
    actionReview: "Оставить отзыв",
    actionRebook: "Повторить",
    actionContact: "Связаться",
    // Причина отмены, указанная мастером или студией.
    cancelReasonLabel: "Причина отмены:",
    monthHeading: "{month}",
    salonTimeNote: "Время салона",
    empty: "Записей пока нет — самое время найти мастера.",
    emptyCta: "Открыть каталог",
    cancelConfirmTitle: "Отменить запись?",
    cancelConfirmBody: "Мастер получит уведомление. Действие необратимо.",
    cancelConfirmAction: "Отменить запись",
    // PACKAGE-CANCEL-UI-01: пакет отменяется только целиком.
    cancelPackageConfirmTitle: "Отменить весь пакет?",
    cancelPackageConfirmBody:
      "Эта услуга входит в пакет — отменить её можно только вместе с остальными услугами пакета. Мастер получит уведомление.",
    cancelPackageConfirmAction: "Отменить пакет",
    // CANCEL-DURING-RESCHEDULE: своя строка — только для отказа без тела;
    // серверные отказы отмены действенные («не позднее чем за 60 минут»,
    // «срок отмены прошёл») и показываются дословно (FIX-C8).
    cancelFailed: "Не удалось отменить запись. Попробуйте ещё раз.",
    // RESCHEDULE-CLIENT-APPROVAL: двустороннее согласование переноса
    // (инв. #32) на стороне клиента — раньше у клиента не было ни текста
    // предложения, ни кнопок, и запись висела «в ожидании» без выхода.
    rescheduleProposedByMaster: "Мастер предлагает перенести на {when}",
    rescheduleProposedByYou: "Вы предложили {when} — ждём ответа мастера",
    actionAcceptReschedule: "Подтвердить перенос",
    actionKeepTime: "Оставить прежнее время",
    rescheduleAnswerFailed: "Не удалось ответить на перенос. Попробуйте ещё раз.",
    icsFilename: (id: string) => `booking-${id}.ics`,
    // FIX-B18: исходы `GET /api/bookings/[id]/ics`. Роут возвращает браузер
    // сюда с `?ics=<исход>` вместо JSON-конверта в окне; ключи — союз
    // `IcsExportFailure`, поэтому новый исход без строки валит typecheck.
    // `auth_required` строки не имеет намеренно: он уводит на /login.
    icsErrorNotFound: "Запись не найдена — возможно, она уже удалена.",
    icsErrorForbidden: "У вас нет доступа к этой записи.",
    icsErrorNoTime: "У записи не указано время — выгрузить в календарь нечего.",
    icsErrorFailed: "Не удалось выгрузить запись в календарь. Попробуйте ещё раз.",
  },
  reviews: {
    title: "Мои отзывы",
    subtitle: "Ваши оценки мастерам и студиям",
    kpiTotal: "Всего отзывов",
    kpiAverage: "Средняя оценка",
    kpiResponded: "Ответили мастера",
    kpiPending: "Ждут отзыва",
    filterAria: "Какие отзывы показать",
    filterAll: "Все",
    filterWithReply: "С ответом",
    filterWithoutReply: "Без ответа",
    filterFiveStar: "5 звёзд",
    ratingLabel: "Оценка",
    textLabel: "Текст отзыва",
    empty: "Вы ещё не оставили отзывов.",
    emptyCta: "Найти мастера",
    pendingTitle: "Ждут вашего отзыва",
    pendingDescription: "Поделитесь впечатлениями — это поможет другим клиентам.",
    pendingCta: "Оставить отзыв",
    pendingMore: (n: number) => `Ещё ${n}`,
    editAction: "Редактировать",
    deleteAction: "Удалить",
    editWindowHint: "Можно изменить в течение 48 часов после публикации",
    masterReplyLabel: "Ответ мастера",
    deleteConfirmTitle: "Удалить отзыв?",
    deleteConfirmBody: "Отзыв будет удалён без возможности восстановления.",
    deleteConfirmAction: "Удалить",
    loadFailed: "Не удалось загрузить отзывы. Попробуйте ещё раз.",
    deleteFailed: "Не удалось удалить отзыв. Попробуйте ещё раз.",
  },
  notifications: {
    title: "Уведомления",
    subtitle: "Записи, напоминания, отзывы и новости платформы",
    filterAria: "Тип уведомлений",
    filterAll: "Все",
    filterBookings: "Записи",
    filterReminders: "Напоминания",
    filterReviews: "Отзывы",
    filterPromo: "Акции",
    filterSystem: "Система",
    onlyUnread: "Только непрочитанные",
    markAllRead: "Отметить всё прочитанным",
    markRead: "Отметить как прочитанное",
    markUnread: "Отметить как непрочитанное",
    empty: "Уведомлений нет.",
    actionOpen: "Открыть",
    actionLeaveReview: "Оставить отзыв",
    actionView: "Посмотреть",
    loadFailed: "Не удалось загрузить уведомления. Попробуйте ещё раз.",
    markFailed: "Не удалось отметить уведомление. Попробуйте ещё раз.",
    markAllFailed: "Не удалось отметить уведомления. Попробуйте ещё раз.",
    clearRead: "Очистить прочитанные",
    clearReadFailed: "Не удалось очистить прочитанные. Попробуйте ещё раз.",
    // 29.09 доработки · 16 (решение 16.2): подписан на мастеров, но акции не разрешил.
    marketingBanner: {
      title: "Разрешите акции мастеров",
      body: "Скидки в горящих окошках мастеров, на которых вы подписаны, приходят только с вашего согласия на акции. «Окошко освободилось» придёт и без него.",
      allow: "Разрешить",
      dismiss: "Не сейчас",
      allowed: "Акции мастеров разрешены",
      allowFailed: "Не удалось разрешить акции. Попробуйте ещё раз.",
    },
  },
  faq: {
    title: "Поддержка и частые вопросы",
    subtitle: "Ответы на популярные вопросы и контакты команды",
    searchPlaceholder: "Опишите проблему или вопрос…",
    heroEyebrow: "Чем помочь?",
    heroTitle: "Найдите ответ за пару секунд",
    heroDescription: "Мы регулярно добавляем новые ответы. Если ответа нет — напишите нам.",
    categoryAria: "Раздел вопросов",
    categoryAll: "Все",
    categoryBookings: "Записи",
    categoryPayment: "Оплата",
    categoryReviews: "Отзывы",
    categoryAccount: "Аккаунт",
    emptySearch: "Ничего не нашли. Попробуйте другой запрос или напишите нам.",
    supportLinkTitle: "Не нашли ответа?",
    supportLinkDescription:
      "Откройте обращение в поддержку — отвечаем в течение часа в рабочее время.",
    supportLinkCta: "Перейти к поддержке",
    contactsTitle: "Контакты",
    contactsDescription: "Если вопрос срочный — пишите напрямую.",
    contactEmail: "Почта",
    // EMAIL-SUPPORT-ADDRESS-CONSOLIDATE-A: canonical support address.
    // Mirrors precedent in UI_TEXT.support.alternativeContact (storing both
    // display + mailto pre-built). DOMAIN-CUTOVER-01: домен ASCII
    // (masterryadom.ru, почта на Яндекс 360 — MAIL-MIGRATION-01), прежняя
    // EAI-оговорка про кириллический адрес неактуальна.
    contactEmailAddress: "support@masterryadom.ru",
    contactEmailHref: "mailto:support@masterryadom.ru",
    contactPhone: "Телефон",
    contactTelegram: "Telegram",
    docsTitle: "Документы",
    docsTerms: "Правила платформы",
    docsPrivacy: "Политика конфиденциальности",
    docsCancellation: "Условия отмены",
    docsConsent: "Согласие на обработку",
  },
  profilePage: {
    title: "Профиль",
    subtitle: "Личные данные, контакты и безопасность",
    headerEyebrow: "Профиль клиента",
    stats: {
      memberSince: (year: string) => `С нами с ${year}`,
      visits: (n: number) => `${n} ${n === 1 ? "визит" : n < 5 ? "визита" : "визитов"}`,
      favorites: (n: number) => `${n} в избранном`,
    },
    sections: {
      personal: "Личные данные",
      contacts: "Контакты",
      linkedAccounts: "Привязанные аккаунты",
      danger: "Удалить аккаунт",
    },
    sectionHints: {
      personal: "Эти данные видят только мастера, у которых вы были на приёме.",
      contacts: "Канал, по которому мастер с вами свяжется.",
      linkedAccounts: "Для быстрого входа и связи с мастером.",
    },
    telegramModal: {
      unavailableTitle: "Подключение Telegram недоступно",
      connectTitle: "Подключить Telegram",
    },
    fields: {
      firstName: "Имя",
      firstNamePlaceholder: "Как вас зовут?",
      lastName: "Фамилия",
      lastNamePlaceholder: "Фамилия",
      city: "Город",
      cityPlaceholder: "Москва",
      birthDate: "Дата рождения",
      hideAgeYear: "Скрыть год",
      hideAgeYearHint: "Год рождения не будет виден другим",
      phone: "Телефон",
      phoneVerified: "Подтверждён",
      // PHONE-CLAIM-01: поле стало редактируемым (заявка на номер).
      phonePlaceholder: "+7 (___) ___-__-__",
      phoneHint: "Для записи к мастеру и напоминаний.",
      phoneIncomplete: "Введите номер полностью: +7 (900) 000-00-00.",
      email: "Электронная почта",
      emailVerify: "Подтвердить",
      emailVerified: "Подтверждена",
      emailPlaceholder: "mail@example.com",
      avatar: "Аватар",
      avatarUpload: "Загрузить фото",
      avatarRemove: "Удалить фото",
    },
    linkedAccounts: {
      telegramConnected: (date: string) => `Подключён ${date}`,
      telegramNotConnected: "Telegram не привязан",
      telegramConnect: "Подключить Telegram",
      telegramDisconnect: "Отключить",
      vkConnected: (date: string) => `Подключён ${date}`,
      vkNotConnected: "VK не привязан",
      vkConnect: "Подключить VK",
      vkDisconnect: "Отключить",
      // FIX-LINK-STATE-CONSISTENCY-01: the linked-but-notifications-off state.
      // Shown instead of «Не подключено» (which wrongly offered «Подключить»
      // for an already-linked account). `deliveryOff` is the suffix after a
      // «@username · »; `linkedDeliveryOff` the standalone form (no username).
      deliveryOff: "уведомления выключены",
      linkedDeliveryOff: "Подключено · уведомления выключены",
    },
    completion: {
      rail: "Профиль заполнен на",
      ofTotal: (n: number, total: number) => `${n} из ${total}`,
      checklistTitle: "Что осталось",
      items: {
        firstName: "Имя",
        lastName: "Фамилия",
        phone: "Телефон",
        email: "Email подтверждён",
        birthDate: "Дата рождения",
        avatar: "Аватар",
        telegram: "Telegram привязан",
        vk: "VK привязан",
      },
      tipTitle: "Совет",
      tipDescription: "Чем подробнее профиль — тем выше шанс, что мастера запомнят вас и предложат удобное окошко.",
    },
    emailVerify: {
      modalTitle: "Подтвердить email",
      modalDescription: "Введите адрес — мы отправим 6-значный код.",
      emailLabel: "Email",
      sendCode: "Отправить код",
      codeLabel: "Код из письма",
      codeHint: "Письмо приходит за 1–2 минуты.",
      resendIn: (sec: number) => `Отправить снова через ${sec} с`,
      resend: "Отправить снова",
      confirm: "Подтвердить",
      success: "Email подтверждён",
      // FIX-C8: `invalidCode` удалён — модалка больше не подменяет серверный
      // `CODE_NOT_FOUND` своей строкой, а второго потребителя у ключа не было
      // (у `/login` собственный `auth.loginPage.invalidCode`).
      // FIX-POLISH-01 (walkthrough #7): «…Попробуйте ещё раз.» per the error
      // convention — this is what the modal shows when the send genuinely
      // fails (the route now returns EMAIL_SEND_FAILED instead of a false 200).
      sendFailed: "Не удалось отправить код. Попробуйте ещё раз.",
      verifyFailed: "Не удалось подтвердить email. Попробуйте ещё раз.",
    },
    danger: {
      cardTitle: "Удалить аккаунт",
      cardDescription: "Все записи и отзывы будут анонимизированы. Действие необратимо.",
      cardCta: "Удалить аккаунт",
      modalStep1Title: "Удалить аккаунт?",
      modalStep1Body: "Все ваши записи и отзывы будут анонимизированы. Это действие необратимо.",
      modalStep1Continue: "Продолжить",
      modalStep2Title: "Куда отправить код?",
      modalStep2Body: "Выберите способ подтверждения. Код придёт мгновенно.",
      channelSms: "SMS",
      channelEmail: "Email",
      channelTelegram: "Telegram",
      channelVk: "VK",
      sendCode: "Отправить код",
      modalStep3Title: "Введите код подтверждения",
      modalStep3Body: "Мы отправили 6-значный код. Введите его для подтверждения удаления.",
      confirm: "Удалить аккаунт",
      cancel: "Отмена",
      success: "Аккаунт удалён",
      sendFailed: "Не удалось отправить код. Попробуйте ещё раз.",
      confirmFailed: "Не удалось удалить аккаунт. Попробуйте ещё раз.",
    },
    saveStatus: {
      idle: "",
      saving: "Сохраняем…",
      saved: "Сохранено",
      error: "Не удалось сохранить. Попробуйте ещё раз.",
    },
  },
} as const;
