export const feed = {
  aiSearchPlaceholder: "✨ Придумайте образ: \"Свадебный макияж для зелёных глаз…\"",
  title: "Витрина вдохновения",
  subtitle: "Найдите идею и запишитесь на результат",
  searchPlaceholder: "Поиск, например «Свадебный макияж»",
  categoryNails: "💅 Ногти",
  categoryHair: "💇‍♀️ Волосы",
  categoryBrowsLashes: "👁️ Брови/Ресницы",
  categoryMakeup: "💄 Мейк",
  categoryBody: "💆‍♀️ Тело",
  tagTrends: "Тренды 2026",
  tagNude: "Нюд",
  tagGradient: "Градиент",
  tagNearby: "Рядом со мной",
  categories: {
    nails: "💅 Ногти",
    hair: "💇‍♀️ Волосы",
    browsLashes: "👁️ Брови/Ресницы",
    makeup: "💄 Мейк",
    body: "💆‍♀️ Тело",
  },
  tags: {
    trends: "Тренды 2026",
    nude: "Нюд",
    gradient: "Градиент",
    nearby: "Рядом со мной",
  },
  bookNow: "Записаться",
  bookThisService: "Записаться на эту услугу",
  addToFavorites: "Добавить в избранное",
  removeFromFavorites: "Убрать из избранного",
  similarWorks: "Похожие работы",
  nearestSlots: "Ближайшие окошки",
  total: "Итого",
  whatOnPhoto: "Что на фото",
  showMore: "Показать ещё",
  emptyFeed: "Портфолио пока пустое",
  emptyTitle: "Пока нет работ",
  emptyDesc: "Добавьте первые работы в портфолио, чтобы клиенты вас замечали.",
  retry: "Повторить",
  loading: "Загружаем ленту…",
  loadFailed: "Не удалось загрузить ленту. Попробуйте ещё раз.",
  detailsFailed: "Не удалось загрузить детали работы. Попробуйте ещё раз.",
  noSlots: "Свободных окошек пока нет",
  byMaster: "Мастер",
  byStudio: "Студия",
  durationHourShort: "ч",
  durationMinuteShort: "м",
} as const;
