export const home = {
  accountDeleted: "Ваш аккаунт удалён",
  hero: {
    title: "Запишитесь к мастеру",
    titleHighlight: "онлайн",
    subtitle:
      "Выбирайте мастера по работам, читайте отзывы и записывайтесь онлайн — без звонков и ожидания",
    ctaFind: "Найти мастера",
    ctaBecome: "Стать мастером",
    statMastersLabel: "мастеров",
    statServicesLabel: "услуг",
    statBookingsLabel: "записей",
    becomeMasterTitle: "Вы мастер или студия?",
    becomeMasterSubtitle:
      "Онлайн-запись, клиентская база и аналитика — бесплатно на старте.",
    becomeMasterCta: "Начать бесплатно",
  },
  filters: {
    reset: "Сбросить фильтры",
    all: "Все",
    categoriesTitle: "Что ищем?",
    tagsTitle: "Какой стиль?",
  },
  visualSearch: {
    button: "Найти по фото",
    modalTitle: "Найти по фото",
    modalSubtitle: "Покажите фото — найдём похожие работы",
    previewAlt: "Предпросмотр",
    resultPhotoAltTemplate: "Похожая работа — {provider} № {n}",
    dropzoneTitle: "Покажите фото — найдём похожие работы",
    dropzoneRelease: "Отпустите файл",
    dropzoneSubtitle: "или выберите файл",
    chooseFile: "Выбрать фото",
    changeFile: "Сменить фото",
    fileRequirements: "JPEG, PNG или WebP до 5 МБ",
    analyzing: "Ищем похожие работы…",
    searchingCategory: "Ищем похожие работы: {category}",
    resultsTitle: "Найденные мастера",
    noResultsTitle: "Мастера не найдены",
    noResultsSubtitle: "Попробуйте загрузить другое фото",
    actions: {
      close: "Закрыть",
      searchAgain: "Выбрать другое фото",
      startSearch: "Найти похожие работы",
      book: "Записаться",
      profileUnavailable: "Профиль недоступен",
    },
    selectedFile: "Файл: {name}",
    messages: {
      unrecognized: "Не поняли, что на фото. Попробуйте другое.",
      lowConfidence:
        "Фото получилось нечётким. Попробуйте снимок крупнее и при хорошем свете.",
      notEnoughIndexed: "Пока мало работ в этой категории — попробуйте позже.",
      disabled: "Поиск по фото временно недоступен.",
      fileRequired: "Выберите файл изображения.",
      invalidFile: "Подойдёт фото JPEG, PNG или WebP до 5 МБ.",
      rateLimited: "Слишком часто. Попробуйте через минуту.",
      // SEC-04 п.7: суточный бюджет инстанса исчерпан — деградация честная
      // (429 + Retry-After до конца UTC-суток), не 500.
      budgetExhausted: "Поиск по фото на сегодня закончился. Попробуйте завтра.",
      searchFailed: "Не удалось выполнить поиск. Попробуйте позже.",
      // VISUAL-SEARCH-TRANSIENT-01: отказал провайдер, а не «на фото ничего нет».
      unavailable: "Не удалось разобрать фото — сервис сейчас не отвечает. Попробуйте ещё раз.",
    },
  },
  loading: "Загружаем ленту…",
  loadFailed: "Не удалось загрузить ленту. Попробуйте ещё раз.",
  empty: "Пока нет работ",
  detailsFailed: "Не удалось загрузить работу. Попробуйте ещё раз.",
  bookService: "Записаться на услугу",
  goToMaster: "К мастеру",
  card: {
    book: "Записаться",
    priceFrom: "от",
    viewProfile: "Профиль",
    ratingLabel: "рейтинг",
  },
  preview: {
    masterLabel: "Мастер",
    onPhotoLabel: "На фото",
  },
  stories: {
    title: "Работы мастеров",
    bookNow: "Записаться",
    photoCount: (current: number, total: number) => `${current} / ${total}`,
  },
  rebook: {
    title: "Записаться снова",
    bookAgain: "Записаться",
    lastVisit: "Последний визит",
    nextSlot: "Ближайшее окошко",
    noSlots: "Свободных окошек нет",
    loadFailed: "Не удалось загрузить мастеров. Попробуйте ещё раз.",
  },
  greeting: {
    hello: "Привет",
    findMaster: "Найти мастера",
    yourFeed: "Лента для вас",
  },
  howItWorks: {
    title: "Как это работает",
    subtitle: "Три шага до записи",
    step1Title: "Найдите мастера",
    step1Desc: "Смотрите портфолио, читайте отзывы и выбирайте по стилю",
    step2Title: "Выберите время",
    step2Desc: "Выбирайте любое удобное окошко прямо в приложении",
    step3Title: "Готово",
    step3Desc: "Получите подтверждение и напоминание о визите",
  },
  categories: {
    title: "Популярные категории",
    subtitle: "Найдите мастера под вашу задачу",
    showAll: "Смотреть всех",
  },
  hotSlotsPreview: {
    title: "Горящие окошки",
    subtitle: "Скидки до конца дня — свободные окошки прямо сейчас",
    book: "Записаться",
    showAll: "Все окошки",
    discountPercent: (v: number) => `-${v}%`,
    discountFixed: (v: number) => `-${v} ₽`,
    loadFailed: "Не удалось загрузить окошки. Попробуйте ещё раз.",
    empty: "Сейчас нет горящих окошек",
  },
  trust: {
    title: "Почему МастерРядом",
    masters: "мастеров",
    bookings: "записей",
    rating: "средний рейтинг",
    categories: "категорий",
    usp1Title: "Только проверенные мастера",
    usp1Desc: "Портфолио, отзывы и рейтинг — до записи",
    usp2Title: "Онлайн без звонков",
    usp2Desc: "Запись, подтверждение и напоминания автоматически",
    usp3Title: "Удобный перенос",
    usp3Desc: "Измените или отмените запись в пару кликов",
  },
} as const;
