export const master = {
  topbar: {
    brand: "МастерРядом",
    nav: {
      home: "Главная",
      bookings: "Записи",
      schedule: "Расписание",
      clients: "Клиенты",
      reviews: "Отзывы",
      analytics: "Аналитика",
      billing: "Тариф",
      models: "Модели",
      profile: "Профиль",
      more: "Ещё",
      myPage: "Моя страница",
    },
  },
  sidebar: {
    myPage: "Моя страница →",
    ratingLabel: "Рейтинг",
    noRating: "Нет оценок",
    lockedHint: "Доступно с тарифа PRO",
    settings: "Настройки",
    settingsProfile: "Профиль",
    settingsFeatures: "Возможности",
    settingsPublic: "Публичная страница",
    settingsBilling: "Тариф",
  },
  clients: {
    title: "Клиенты",
    subtitle: "База клиентов по вашим записям",
    loading: "Загружаем клиентов…",
    loadFailed: "Не удалось загрузить клиентов. Попробуйте ещё раз.",
    daysAgo: (n: number) => {
      const mod10 = n % 10;
      const mod100 = n % 100;
      const suffix =
        mod10 === 1 && mod100 !== 11 ? "день" : mod10 >= 2 && mod10 <= 4 && (mod100 < 12 || mod100 > 14) ? "дня" : "дней";
      return `${n} ${suffix} назад`;
    },
    today: "Сегодня",
  },
  bookingsPage: {
    title: "Записи",
    subtitle: "Ваши записи",
    loading: "Загружаем записи…",
    loadFailed: "Не удалось загрузить записи. Попробуйте ещё раз.",
    searchPlaceholder: "Имя клиента или услуга",
    filterAll: "Все",
    filterToday: "Сегодня",
    filterUpcoming: "Предстоящие",
    filterFinished: "Завершённые",
    filterCancelled: "Отменённые",
    emptyToday: "Сегодня записей нет",
    emptyTodayHint: "Отдыхайте или создайте горящее окошко",
    emptyTodayCta: "Горящее окошко",
    empty: "Записей нет",
    emptyHint: "Записи появятся после первых клиентов",
    confirm: "Подтвердить",
    reject: "Отклонить",
    confirming: "Подтверждение…",
    rejecting: "Отклонение…",
    noClient: "Клиент",
    moreDrawerTitle: "Ещё",
    menuClients: "Клиенты",
    menuReviews: "Отзывы",
    menuAnalytics: "Аналитика",
    menuSettings: "Настройки",
    menuMyPage: "Моя страница →",
    menuModels: "Модели",
    menuBilling: "Тариф",
  },
  advisor: {
    title: "Советы для роста",
    refresh: "Обновить",
    refreshing: "Обновляем…",
    staleSuccess: "Всё отлично",
    aiInsightTitle: "Совет от ИИ",
    errors: {
      load: "Не удалось загрузить советы. Попробуйте ещё раз.",
      refresh: "Не удалось обновить советы. Попробуйте ещё раз.",
    },
  },
  notifications: {
    title: "Центр уведомлений",
    subtitle: "Приглашения и новости по вашему кабинету",
    timelineTitle: "Что происходило",
    timelineSoon: "Новые уведомления появятся здесь.",
    filterAll: "Все",
    filterBookings: "Записи",
    filterSystem: "От платформы",
    bookingCreatedLabel: "Новая запись",
    bookingCancelledLabel: "Отмена записи",
    bookingRescheduledLabel: "Перенос записи",
    systemLabel: "Сообщение от платформы",
    newBadge: "Новое",
    publishHotWindow: "Опубликовать как «Горящее окошко»",
    hotWindowUnavailable: "Горящее окошко пока опубликовать нельзя",
    markAllRead: "Отметить всё прочитанным",
    actionFailed: "Не удалось выполнить действие. Попробуйте ещё раз.",
    networkError: "Сеть недоступна или сервер не отвечает",
    accepting: "Принимаем…",
    declining: "Отклоняем…",
    accept: "Принять",
    decline: "Отклонить",
    viewStudioProfile: "Посмотреть профиль студии",
  },
  invites: {
    pinnedTitle: "Новые приглашения",
    emptyTitle: "Пока нет приглашений",
    emptyDesc: "Заполните профиль — студии смогут найти вас и пригласить",
    fillProfile: "Заполнить профиль",
    phoneRequired: "Укажите номер телефона в профиле, чтобы получать приглашения.",
  },
  platform: {
    title: "Новости платформы",
    soon: "Новости платформы появятся здесь.",
  },
  dashboard: {
    silentModeEnabled: "Режим тишины включён",
    bookingQuestionsTitle: "Вопросы клиента",
    referencePhotoAlt: "Фото-референс",
    answerPrefix: "•",
    errors: {
      loadDay: "Не удалось загрузить данные дня. Попробуйте ещё раз.",
      loadSlots: "Не удалось загрузить свободные окошки. Попробуйте ещё раз.",
      commentRequired: "Комментарий обязателен",
      updateStatus: "Не удалось изменить запись. Попробуйте ещё раз.",
      createBooking: "Не удалось создать запись. Попробуйте ещё раз.",
      createImage: "Не удалось создать изображение. Попробуйте ещё раз.",
      saveStories: "Не удалось сохранить сторис. Попробуйте ещё раз.",
      bookingDurationUnknown: "Не удалось определить длительность записи. Попробуйте ещё раз.",
      invalidStartDateTime: "Проверьте дату и время начала",
      sendRescheduleRequest: "Не удалось отправить запрос на перенос. Попробуйте ещё раз.",
    },
    prompts: {
      rejectReason: "Причина отклонения",
      rescheduleStart: "Новая дата и время начала",
      clientComment: "Комментарий для клиента",
    },
    labels: {
      noSlots: "Свободных окошек нет",
      dayTitle: "Мой день",
      newBookings: "Новые",
      addBooking: "Добавить запись",
      addBookingDisabled: "Записывать клиентов может администратор студии",
      manualBookingButton: "Записать клиента вручную",
      todayOff: "Сегодня выходной",
      change: "Изменить",
      workingHoursToday: "Рабочее время сегодня: {start}–{end} • пауза {buffer} {minutes}",
      workingHoursNotSet: "Рабочее время не настроено",
      setup: "Настроить",
      silenceBadge: "🤫 Тишина",
      chat: "Чат",
      emptyBookingsTitle: "Пока нет записей",
      emptyBookingsDesc: "На сегодня записей нет. Можно добавить запись вручную или проверить расписание.",
      balanceTitle: "Доход за месяц",
      balanceToggleAria: "Скрыть или показать баланс",
      hideBalance: "Скрыть",
      showBalance: "Показать",
      nextSlotsTitle: "Ближайшие свободные окошки",
      refresh: "Обновить",
      refreshSlotsAria: "Обновить окошки",
      publishStories: "Опубликовать в сторис",
      slotsLoading: "Загружаем окошки…",
      notificationsTitle: "Уведомления (новые отзывы)",
      noReviews: "Пока отзывов нет.",
      slotsOnDate: "Окошки на {date}",
      savedCardsTitle: "Сохранённые карточки",
    },
    freeSlots: {
      title: "Свободные окошки сегодня",
      empty: "Сегодня всё занято 🎉",
      allFit: "{duration} мин",
      partialFit: "до {duration} мин",
      roundingExact: "Точное время",
      rounding30min: "30 мин",
      rounding1hour: "1 час",
    },
    stories: {
      brand: "МастерРядом",
      slotsTitle: "Свободные окошки · {date}",
      cardTitle: "Карточка {index}/{total}",
      saveToMedia: "Сохранить в галерею",
      download: "Скачать картинку",
      share: "Поделиться",
      previewTitle: "Создать сторис",
      cardAlt: "Карточка для сторис",
      allServices: "Все услуги",
      bgGradient: "Градиент",
      bgLight: "Светлый",
      bgDark: "Тёмный",
      slotsOnCanvas: "Свободные окошки",
      moreSlots: "и ещё {n} окошек",
      noSlots: "Нет свободных окошек",
      today: "Сегодня",
      generating: "Готовим карточку…",
    },
    dateNav: {
      today: "Сегодня",
      prevDay: "Предыдущий день",
      nextDay: "Следующий день",
      refresh: "Обновить",
    },
    manualBooking: {
      title: "Записать клиента",
      chooseService: "Выберите услугу",
      clientNamePlaceholder: "Имя клиента",
      phonePlaceholder: "Телефон",
      commentPlaceholder: "Комментарий",
      create: "Создать",
    },
    status: {
      pending: "Ожидает подтверждения",
      changeRequested: "Ждём ответа по переносу",
      inProgress: "В процессе",
      finished: "Завершено",
      confirmed: "Подтверждено",
      rejected: "Отклонено",
    },
    actions: {
      confirm: "Подтвердить",
      reject: "Отклонить",
      confirmMove: "Подтвердить перенос",
      rejectMove: "Отклонить перенос",
      requestMove: "Запросить перенос",
    },
  },
  modelOffers: {
    status: {
      active: "Открыто",
      closed: "Закрыт",
      archived: "Архив",
    },
    noCategoryWarning: "Сначала добавьте категории к своим услугам",
    goToServices: "Перейти к услугам →",
    messages: {
      uncategorizedServicesWarning:
        "Сначала добавьте категорию к вашим услугам в разделе",
      servicesSectionLink: "Профиль → Услуги",
      uncategorizedCategoryName: "Без категории",
      loadingOffers: "Загружаем предложения…",
      emptyTitle: "Пока нет предложений",
      emptySubtitle: "Создайте первое объявление, чтобы найти модель на удобное время.",
      categoryFirstHint: "Сначала выберите категорию.",
      extraBusyHint: "время на съёмку и фото",
      offerVisibleHint: "После публикации объявление появится в каталоге моделей.",
      servicesNotSelected: "Услуги не выбраны",
      requirementsNotProvided: "Требования не указаны",
    },
    header: {
      title: "Ищу модель для работы",
      subtitle: "Разместите объявление и выберите подходящий отклик.",
      hideForm: "Скрыть форму",
      showForm: "Разместить объявление",
    },
    create: {
      title: "Ищу модель для работы",
      subtitle: "Расскажите, что нужно модели, — и предложение увидят в каталоге.",
    },
    labels: {
      category: "Категория",
      service: "Услуга",
      date: "Дата",
      startTime: "Время начала",
      endTime: "Время окончания",
      extraBusy: "Запас времени на съёмку, мин",
      price: "Цена",
      requirements: "Требования",
    },
    placeholders: {
      category: "Выберите категорию",
      service: "Выберите услугу",
      price: "Бесплатно",
      requirement: "Например: без тату",
    },
    actions: {
      publish: "Разместить объявление",
      publishing: "Размещаем…",
      retry: "Повторить",
    },
    validation: {
      maxRequirements: "Не больше 5 требований.",
      categoryRequired: "Выберите категорию",
      serviceRequired: "Выберите услугу",
      dateRequired: "Укажите дату",
      timeRangeRequired: "Укажите время начала и окончания",
      timeRangeInvalid: "Время начала должно быть раньше времени окончания",
      invalidPrice: "Проверьте цену",
      invalidExtraBusy: "Укажите от 0 до 240 минут",
      tooManyRequirements: "Можно добавить не более 5 требований",
    },
    errors: {
      loadOffers: "Не удалось загрузить предложения. Попробуйте ещё раз.",
      createOffer: "Не удалось создать предложение. Попробуйте ещё раз.",
    },
    applications: {
      title: "Отклики",
      pendingShort: "Новые: {count}",
      collapse: "Свернуть",
      expand: "Развернуть",
      loading: "Загружаем отклики…",
      retry: "Повторить",
      empty: "Пока нет откликов",
      status: {
        pending: "На рассмотрении",
        accepted: "Принята",
        rejected: "Отклонена",
        confirmed: "Подтверждена",
      },
      modal: {
        title: "Предложить время",
        timeLabel: "Время встречи",
        range: "Свободно с {start} до {end}",
        timeRequired: "Укажите время",
        cancel: "Отмена",
        submit: "Предложить",
        submitting: "Сохраняем…",
      },
      card: {
        responseAt: "Отклик: {datetime}",
        consentYes: "Согласие на съёмку",
        consentNo: "Без согласия на съёмку",
        proposed: "Предложено: {time}",
        confirmed: "Подтверждено: {datetime}",
        noteTitle: "Пожелания модели",
        noteEmpty: "Без комментария",
        proposeButton: "Предложить время",
        rejectButton: "Отклонить",
        rejectingButton: "Отклоняем…",
      },
      errors: {
        load: "Не удалось загрузить отклики. Попробуйте ещё раз.",
        reject: "Не удалось отклонить отклик. Попробуйте ещё раз.",
        propose: "Не удалось предложить время. Попробуйте ещё раз.",
      },
      rejectConfirm: "Отклонить отклик?",
    },
  },
  profile: {
    headerTitle: "Профиль",
    headerSubtitle: "О себе, услугах и портфолио.",
    tabs: {
      main: "Основное",
      services: "Услуги и прайс",
      portfolio: "Портфолио",
      settings: "Настройки",
    },
    errors: {
      saveAddress: "Не удалось сохранить адрес. Попробуйте ещё раз.",
      loadProfile: "Не удалось загрузить профиль. Попробуйте ещё раз.",
      loadBookingConfig: "Не удалось загрузить настройки записи. Попробуйте ещё раз.",
      deleteCabinet: "Не удалось удалить кабинет мастера. Попробуйте ещё раз.",
      updateSettings: "Не удалось обновить настройки. Попробуйте ещё раз.",
      updateReminders: "Не удалось обновить напоминания. Попробуйте ещё раз.",
      invalidCancellationHours: "Укажите от 0 до 168 часов.",
      updateCancellationDeadline: "Не удалось обновить срок отмены. Попробуйте ещё раз.",
      saveServices: "Не удалось сохранить услуги. Попробуйте ещё раз.",
      displayNameRequired: "Укажите имя",
      addServiceTitleRequired: "Укажите название",
      addServicePriceRequired: "Укажите цену",
      addServiceDurationRequired: "Выберите длительность",
      priceTooLow: "Введите цену больше 0.",
      proposeCategory: "Не удалось создать категорию. Попробуйте ещё раз.",
      loadAvatar: "Не удалось загрузить аватар. Попробуйте ещё раз.",
      deleteAvatar: "Не удалось удалить аватар. Попробуйте ещё раз.",
      portfolioLimitReached: "В портфолио больше нет места. Удалите фото или перейдите на тариф выше.",
      uploadPhoto: "Не удалось загрузить фото. Попробуйте ещё раз.",
      savePhotoDescription: "Не удалось сохранить описание фото. Попробуйте ещё раз.",
      removePhoto: "Не удалось удалить фото из портфолио. Попробуйте ещё раз.",
      replacePhoto: "Не удалось заменить фото. Попробуйте ещё раз.",
      leaveStudio: "Не удалось покинуть студию. Попробуйте ещё раз.",
      saveFailed: "Не удалось сохранить. Попробуйте ещё раз.",
    },
    autosave: {
      saving: "Сохраняем…",
      savedAuto: "Сохранено автоматически",
    },
    onlinePayments: {
      proRequired: "Онлайн-оплата доступна на PRO и выше.",
      disabledByAdmin: "Онлайн-оплата временно отключена",
    },
    preview: {
      nameFallback: "Имя мастера",
      taglineFallback: "Добавьте хештег профиля",
      addressFallback: "Адрес пока не указан",
      bioFallback: "Добавьте описание, чтобы клиенты лучше узнали о вас.",
      addressLabel: "Адрес",
      reviewsLabel: "отзывов",
      published: "Профиль опубликован",
      unpublished: "Не опубликован",
      openAsClient: "Посмотреть как клиент",
      title: "Предпросмотр витрины",
    },
    loading: "Загружаем профиль…",
    invite: {
      title: "Приглашение в студию",
      description: "Примите или отклоните приглашение, чтобы начать работать в студии.",
    },
    sections: {
      profileShowcaseTitle: "Профиль и витрина",
      profileShowcaseDesc: "То, что видят клиенты в поиске и на витрине.",
      settingsTitle: "Настройки",
      settingsDesc: "Автоподтверждение записей и уведомления в мессенджерах.",
      servicesTitle: "Услуги и прайс",
      servicesDesc: "Управляйте стоимостью, длительностью и доступностью услуг.",
      portfolioTitle: "Портфолио",
      portfolioDesc: "Добавляйте работы и связывайте их с услугами.",
    },
    publication: {
      title: "Публикация профиля",
      desc: "Без публикации профиль не отображается в поиске и витрине.",
      publishAction: "Опубликовать профиль",
      missingFieldsPrefix: "Для публикации необходимо заполнить:",
      cannotPublish: "Заполните обязательные поля для публикации",
      fieldAvatar: "Фото профиля",
      fieldName: "Имя",
      fieldHashtag: "Хештег",
      fieldAddress: "Адрес",
      fieldBio: "Описание",
      profileComplete: "Профиль готов к публикации",
    },
    addressRequired: {
      title: "Заполните адрес — иначе профиль не опубликовать",
      description:
        "Мы определим город по адресу и покажем вас клиентам в этом городе. Без адреса каталог не сможет вас найти.",
      cta: "Перейти к адресу",
    },
    // error-hint-ok: своё действие — проверить адрес
    geocoderFailed: "Не удалось определить город по адресу. Проверьте корректность.",
    automation: {
      title: "Автоматизация",
      desc: "Настройки подтверждения записей.",
      autoConfirmTitle: "Автоподтверждение записи",
      autoConfirmDesc: "Новые записи будут подтверждаться сами — без вашего участия.",
    },
    reminders: {
      title: "Напоминания",
      desc: "Отправлять клиенту и мастеру напоминания о записи.",
      label: "Напоминания о записи",
      hint: "Можно отключить, если не нужны уведомления за 24 часа и 2 часа.",
    },
    cancellation: {
      title: "Политика отмены",
      desc:
        "Клиент может отменить запись не позднее указанного срока. Оставьте поле пустым — отменять можно в любой момент; 0 — отмена запрещена.",
      label: "Срок отмены (часы)",
      placeholder: "Например, 24",
      currentValue: "Сейчас:",
      hoursShort: "ч.",
    },
    hotSlots: {
      title: "Горящие окошки",
      desc: "Подсветите свободные окошки и получите больше записей.",
    },
    deleteCabinet: {
      title: "Удаление кабинета мастера",
      descMain:
        "Удаление кабинета мастера необратимо. Все услуги, расписание и портфолио будут удалены.",
      descLegal:
        "История завершённых записей сохраняется в обезличенном виде согласно требованиям законодательства.",
      action: "Удалить",
    },
    services: {
      newServiceTitle: "Новая услуга",
      hide: "Скрыть",
      globalCategoryLabel: "Категория из общего каталога",
      selectCategory: "Выберите категорию",
      selectCategoryHint: "Выберите категорию, чтобы услуга отображалась на сайте.",
      categoryPendingSuffix: " (на модерации)",
      categoryPersonalSuffix: " (только у меня)",
      pendingCategoryNotice: (names: string) =>
        `Категория «${names}» ожидает проверки администратором. После одобрения она появится в общем каталоге.`,
      serviceTitleLabel: "Название услуги",
      serviceTitlePlaceholder: "Название",
      serviceTitleExample: "Например: Маникюр с гель-лаком",
      priceLabel: "Цена",
      durationLabel: "Длительность",
      durationUnit: "мин",
      addService: "Добавить услугу",
      selectStudioService: "Выберите услугу из каталога студии",
      noCategoryOption: "Нет категории",
      noCategoryHint: "Нет категории. Добавьте категорию, чтобы услуга находилась в поиске и подходила для предложений моделям.",
      addOwnCategoryCta: "+ Своя категория",
      proposeCategoryTitle: "Предложить категорию",
      proposeCategoryPlaceholder: "Название категории",
      proposeCategoryHint: "Категория будет сразу доступна только в вашем кабинете.",
      proposeCategorySuccess:
        "Категория отправлена на модерацию. Пока она доступна только вам.",
      proposeCategorySubmit: "Отправить",
      add: "Добавить",
      columnTitle: "Название услуги",
      columnPrice: "Цена",
      columnDuration: "Длительность",
      columnEnabled: "Показывать",
      priceManagedHint: "Цену задаёт студия — вы меняете только длительность.",
      onlinePaymentsLabel: "Онлайн-оплата",
      addServiceCta: "+ Добавить услугу",
      emptyTitle: "Услуг пока нет",
      emptyDesc: "Добавьте услуги чтобы клиенты могли записаться",
      descriptionLabel: "Описание",
      descriptionPlaceholder: "Расскажите о процедуре, особенностях, результате",
      suggestDescription: "Подсказать описание",
      suggestDescriptionLoading: "Подбираем слова…",
      suggestDescriptionFailed: "Не удалось сгенерировать описание. Попробуйте ещё раз.",
    },
    bookingConfig: {
      title: "Настройки записи",
      open: "Настройки записи",
      loading: "Загружаем настройки записи…",
      referencePhotoRequiredLabel: "Нужен фото-референс для записи.",
      questionsTitle: "Вопросы для клиента",
      addQuestion: "+ Добавить вопрос",
      empty: "Вопросов пока нет.",
      questionLabel: "Вопрос",
      questionPlaceholder: "Введите вопрос",
      moveUp: "↑",
      moveDown: "↓",
      remove: "Удалить",
      required: "Обязательный",
    },
    portfolio: {
      limitReached: "Больше фото добавить нельзя.",
      plans: "Тарифы",
      dropTitle: "Перетащите фото сюда",
      dropSubtitle: "или нажмите, чтобы выбрать фото",
      pickTitle: "Выбрать фото",
      uploadingSuffix: "— загружаем…",
      draftLabel: "Фото загружается",
      draftAlt: "Черновик фото",
      addDescription: "Добавить описание",
      photoUnavailable: "Фото недоступно",
      photoAlt: "Фото из портфолио",
      replace: "Заменить",
      remove: "Удалить",
      linkedServices: "Привязано к услугам",
      notInSearchBadge: "Не в поиске",
      notInSearchHint: "Добавьте категорию чтобы фото появилось в поиске",
    },
    portfolioMeta: {
      modalTitle: "Предпросмотр витрины",
      photoDescriptionTitle: "Описание фото",
      captionPlaceholder: "Подпись (необязательно)",
      serviceHint: "Какая это услуга? (необязательно)",
      categoryModalTitle: "Категория фото",
      noCategoryOption: "Без категории",
      categoryHint: "Добавьте категорию чтобы фото появилось в поиске",
      categoryMissingHint: "Если категорию не выбрать, фото сохранится, но может не попасть в поиск сразу.",
      addCategoryToServicesHint: "Добавьте категорию к услугам, чтобы фото попало в поиск.",
      goToServices: "Перейти к услугам",
    },
    status: {
      savedChanges: "✓ Изменения сохранены",
    },
    autoPublishStories: {
      title: "Автопубликация сторис",
      description:
        "Новые фото из портфолио автоматически появляются в сторис на главной (на 24 часа)",
      saving: "Сохраняем…",
      saved: "Сохранено",
      error: "Не удалось сохранить. Попробуйте ещё раз.",
      retry: "Повторить",
      ariaLabel: "Автопубликация сторис",
    },
    leaveStudio: {
      bannerTitle: "Вы работаете в составе студии",
      bannerDescription:
        "Если нужно прекратить членство, вы можете самостоятельно выйти из студии. После выхода доступ к студийным разделам и настройкам студии будет отключён.",
      bannerAction: "Выйти из студии",
      modalTitle: "Покинуть студию?",
      modalDescription:
        "После выхода вы станете независимым мастером. Будущие записи в студии перед выходом нужно перенести на другого мастера или отменить.",
      transferServicesLabel: "Перенести услуги студии в мой прайс",
      transferServicesHint: "Цены и длительность будут скопированы с вашими настройками",
      leaveAction: "Покинуть студию",
      leaving: "Выходим…",
      // 29.09 доработки · 04: карточка в «Настройках аккаунта».
      teamTemplate: "Команда «{name}»",
      blockingNotice: (count: number) =>
        `Будущих записей в студии: ${count}. Попросите администратора студии перенести их на другого мастера или отменить — после этого можно выйти.`,
      openBookings: "Открыть записи",
    },
    form: {
      nameLabel: "Имя",
      namePlaceholder: "Например: Анна Смирнова",
      hashtagLabel: "Хештег профиля",
      hashtagPlaceholder: "например: маникюр, Москва",
      hashtagHint: "Показывается как бейдж на карточке в каталоге",
      addressLabel: "Адрес",
      addressPlaceholder: "Начните вводить адрес…",
      bioLabel: "Описание",
      bioPlaceholder: "Расскажите клиентам о себе — опыт, подход, специализация",
      selectAddressAria: "Выбрать адрес",
      replaceAvatarAction: "Заменить фото",
      removeAvatarAction: "Удалить фото",
      replaceAvatarAria: "Заменить аватар",
      removeAvatarAria: "Удалить аватар",
    },
  },
} as const;
