export const media = {
  avatar: {
    noAvatar: "Нет фото",
    alt: "Фото профиля",
    upload: "Загрузить фото",
    replace: "Изменить фото",
    remove: "Удалить фото",
    setFocalPoint: "Задать точку фокуса",
    editFocalPoint: "Изменить точку фокуса",
    setCrop: "Обрезать",
    editCrop: "Изменить обрезку",
    loadFailed: "Не удалось загрузить фото. Попробуйте ещё раз.",
    uploadFailed: "Не удалось загрузить фото. Попробуйте ещё раз.",
    deleteFailed: "Не удалось удалить фото. Попробуйте ещё раз.",
  },
  focalPoint: {
    title: "Главное на фото",
    hint: "Нажмите на главный объект фото — лицо или ключевой элемент.",
    save: "Сохранить",
    skip: "Пропустить",
    saveFailed: "Не удалось сохранить точку фокуса. Попробуйте ещё раз.",
  },
  crop: {
    titleAvatar: "Обрезать фото",
    titleBanner: "Обрезать баннер",
    titlePhoto: "Обрезать фото",
    hint: "Двигайте фото под рамкой или используйте ползунок масштаба.",
    zoomLabel: "Масштаб",
    zoomOut: "Уменьшить",
    zoomIn: "Увеличить",
    previewLabel: "Предпросмотр",
    save: "Применить",
    saving: "Сохраняем…",
    skip: "Пропустить",
    saveFailed: "Не удалось сохранить обрезку. Попробуйте ещё раз.",
    setCrop: "Обрезать",
    editCrop: "Изменить обрезку",
  },
  portfolio: {
    addPhoto: "Добавить фото",
    limitReached: "Больше фото добавить нельзя",
    loadFailed: "Не удалось загрузить портфолио. Попробуйте ещё раз.",
    uploadFailed: "Не удалось загрузить фото. Попробуйте ещё раз.",
    deleteFailed: "Не удалось удалить фото. Попробуйте ещё раз.",
    replacePhotoAria: "Заменить фото",
    removePhotoAria: "Удалить фото",
    confirmRemove: "Удалить это фото из портфолио?",
    closePreviewAria: "Закрыть предпросмотр",
    previewDialogAria: "Просмотр фото",
    // UI-33: единственный потомок кнопки открытия — картинка, поэтому без
    // этих двух ключей у кнопки не было доступного имени вовсе.
    openPreviewAriaTemplate: "Открыть фото № {n}",
    photoAltTemplate: "Работа из портфолио № {n}",
    previewAlt: "Фото во весь экран",
    // CATALOG-MAIN-PHOTO: главное фото карточки каталога (портфолио студии).
    coverBadge: "Главное фото",
    coverHint: "Главное фото открывает карточку в каталоге. Если не выбрать, им станет самое новое.",
    makeCover: "Сделать главным",
    makeCoverFailed: "Не удалось сделать фото главным. Попробуйте ещё раз.",
    // STUDIO-PORTFOLIO-FEED: подпись фото студии «мастер · услуга» — видна
    // на фото в ленте и в историях на главной.
    captionAdd: "Подписать работу",
    captionEditAria: "Изменить подпись работы",
    captionDialogTitle: "Кто и что делал",
    captionDialogHint: "Подпись видна на фото в ленте и в историях на главной.",
    captionMasterLabel: "Мастер",
    captionServiceLabel: "Услуга",
    captionMasterNone: "Не указан",
    captionServiceNone: "Не указана",
    captionSave: "Сохранить",
    captionCancel: "Отмена",
    captionSaveFailed: "Не удалось сохранить подпись. Попробуйте ещё раз.",
    captionLoadFailed: "Не удалось загрузить подписи работ. Попробуйте ещё раз.",
  },
} as const;
