export const nav = {
  catalog: "Каталог",
  myBookings: "Мои записи",
  profile: "Профиль",
  professionalRoles: "Мои кабинеты",
  settings: "Настройки",
  adminPanel: "🛡️ Админ-панель",
  masterWorkspace: "Мастер",
  studioWorkspace: "Студия",
  notifications: "Уведомления",
  userMenuAria: "Открыть меню профиля",
  mobileMenuTitle: "Навигация",
  openMasterWorkspace: "Открыть кабинет мастера",
  openStudioWorkspace: "Открыть кабинет студии",
  siteLogoAlt: "Логотип сайта",
  forModels: "Для моделей",
  home: "Главная",
  bookings: "Записи",
  clients: "Клиенты",
  schedule: "Расписание",
  calendar: "Календарь",
  services: "Услуги",
  adminShort: "Админ",
  loginAction: "Войти",
  becomeMaster: "Стать мастером",
  pricing: "Тарифы",
  closeMenu: "Закрыть меню",
  openMenu: "Открыть меню",
  masterWorkspaceFallback: "М",
  studioWorkspaceFallback: "С",
  roleClient: "Клиент",
  roleMaster: "Мастер",
  roleStudio: "Студия",
  switchRole: "Сменить кабинет",
  activeRole: "Текущий кабинет",
  roleSwitcherTitle: "Кабинет",
  becomeMasterCta: "Стать мастером",
  /**
   * NAV-BECOME-MASTER-01 — подпись пятой вкладки нижней навигации PWA.
   * NAV-ALIGN-01: короткая на любой ширине — полная делала вкладку вдвое шире
   * соседних; полное имя («Стать мастером») уходит в aria-label.
   */
  becomeMasterTabShort: "Мастерам",
  /** NAV-ATTENTION-01 — подпись точки на вкладке для скринридера. */
  needsAttention: "есть то, что ждёт вашего действия",
  createStudioCta: "Создать студию",
  cabinetSwitcher: {
    label: "Сменить кабинет",
    client: "Кабинет клиента",
    master: "Кабинет мастера",
    studio: "Кабинет студии",
  },
  login: "Вход",
  logout: "Выход",
  logoutPending: "Выход…",
} as const;
