export const publicStudio = {
  heroBook: "Записаться онлайн",
  // FIX-STUDIO-02 (known-open 1): honest label for the floating affordance
  // that scrolls to services (was mislabelled «Записаться онлайн»).
  toServices: "К услугам",
  // FIX-STUDIO-02 (owner parity): shown in place of the booking CTAs when the
  // viewer owns this studio (self-booking is server-rejected). Mirrors the
  // master-side owner notice.
  ownerViewTitle: "Это ваш профиль",
  ownerViewHint: "Так вашу страницу видят клиенты. Запись к самому себе недоступна.",
  ownerViewManageCta: "Управлять студией",
  teamTitle: "Мастера студии",
  teamSubtitle: "Выберите мастера и посмотрите его работы",
  servicesTitle: "Услуги",
  servicesSubtitle: "Выберите услугу и добавьте её в запись",
  book: "Записаться",
  openBookingFlow: "Открыть запись",
  galleryFallback: "Фотографии студии",
  noMasters: "Пока нет доступных мастеров",
  gradeTop: "Топ",
  gradePro: "Профи",
  gradeNew: "Новый",
  noPortfolio: "Портфолио появится скоро",
  // UI-33: миниатюры в оверлее карточки мастера — единственное, что
  // показывает его работы; оверлей спрятан трансформом, но в дереве
  // доступности присутствует всегда.
  masterWorkAltTemplate: "Работа мастера {name} № {n}",
  openMaster: "Открыть профиль",
  blockLoadFailed: "Не удалось загрузить этот раздел. Попробуйте ещё раз.",
  profileLoadFailed: "Не удалось загрузить профиль студии. Попробуйте ещё раз.",
  bookingLoadFailed: "Не удалось открыть форму записи. Попробуйте ещё раз.",
  studioDataLoadFailed: "Не удалось загрузить данные студии. Попробуйте ещё раз.",
  servicesLoadFailed: "Не удалось загрузить услуги. Попробуйте ещё раз.",
  reviewsLoadFailed: "Не удалось загрузить отзывы. Попробуйте ещё раз.",
  typeStudio: "Студия",
  availableToday: "Свободно сегодня",
  noCategories: "Без категорий",
  studioOnlyProfileError: "Эта страница — только для студий",
  from: "от",
  selectSlotFirst: "Выберите удобное время",
  bookingError: "Не удалось создать запись. Попробуйте ещё раз.",
  mastersLoadFailed: "Не удалось загрузить мастеров. Попробуйте ещё раз.",
  slotsLoadFailed: "Не удалось загрузить окошки. Попробуйте ещё раз.",
  // error-hint-ok: своё действие — выбрать другой день
  dateInvalid: "Не удалось открыть этот день. Выберите другой.",
  guestNameRequired: "Укажите имя.",
  guestPhoneRequired: "Укажите телефон.",
  addService: "＋",
  servicePriceOnRequest: "Цена по запросу",
  // FIX-BATCH-B: category grouping ported from the booking wizard (R2-04-C).
  // `categoryAll` = the "all" filter chip; `categoryOther` = uncategorized bucket label.
  categoryAll: "Все",
  categoryOther: "Другие услуги",
  noServices: "Услуги пока не добавлены",
  goToBooking: "К записи",
  sectionPhotos: "Фотографии студии",
  sectionPhotosSubtitle: "Интерьер, команда и атмосфера",
  photoAltTemplate: "Фотография студии № {n}",
  sectionReviews: "Отзывы",
  sectionReviewsSubtitle: "Последние отзывы клиентов",
  reviewLeave: "Оставить отзыв",
  reviewEmpty: "Пока нет отзывов",
  reviewsCountLabel: "отзывов",
  reviewsLoadMore: "Показать ещё",
  reviewsLoadMoreLoading: "Загружаем…",
  // PACKAGE-BOOKING-MVP-2 — studio package section + multi-master booking flow.
  packages: {
    heading: "Пакеты",
    subtitle: "Несколько услуг в один визит со скидкой комплекта",
    includesLabel: "ВКЛЮЧАЕТ",
    finalPriceLabel: "ИТОГО",
    durationTemplate: "⏱ {minutes} мин",
    youSaveTemplate: "Экономия {amount}",
    bookCta: "Записаться на пакет",
  },
  packageBooking: {
    buildHint:
      "Выберите мастера и время для каждой услуги. Услуги идут одна за другой — в один визит, одна оплата со скидкой комплекта.",
    componentLabel: "Услуга {index} из {total}",
    pickMaster: "Выберите мастера",
    noMasters: "Для этой услуги пока нет доступных мастеров.",
    waitingPrevious: "Доступно после выбора предыдущих услуг",
    change: "Изменить",
    slotsLoading: "Загружаем свободные окна…",
    // error-hint-ok: своё действие — выбрать другой день
    slotsError: "Не удалось показать окошки. Попробуйте другой день.",
    noSlots: "На этот день свободных окошек нет.",
    // error-hint-ok: своё действие — выбрать другое время
    proposeError: "Не удалось собрать пакет на это время. Выберите другое.",
    proposing: "Рассчитываем…",
    networkError: "Не удалось связаться с сервером. Попробуйте ещё раз.",
    bookError: "Не удалось записать пакет. Попробуйте ещё раз.",
    toReview: "Продолжить",
    back: "Назад",
    total: "Итого со скидкой",
    continue: "Продолжить",
    nameLabel: "Имя",
    // FIX-NAME-HINT: «Как к вам обращаться» звало назвать одно имя, а
    // подсказка под полем (`common.ownNameHint`) просит фамилию и имя.
    namePlaceholder: "Фамилия и имя",
    phoneLabel: "Телефон",
    phonePlaceholder: "+7 999 123-45-67",
    commentLabel: "Комментарий (необязательно)",
    commentPlaceholder: "Пожелания к записи",
    bookingAs: "Записываем как {name}",
    nameRequired: "Укажите имя.",
    phoneInvalid: "Проверьте номер телефона.",
    submit: "Записать пакет",
    submitting: "Записываем…",
    successTitle: "Вы записаны на пакет",
    successBody: "Услуги идут одна за другой. Студия подтвердит запись.",
    close: "Закрыть",
    priceNote: "Итоговая цена зависит от выбранных мастеров.",
  },
} as const;
