export const publicProfile = {
  page: {
    loading: "Загружаем профиль мастера…",
    redirecting: "Открываем страницу студии…",
    loadFailedTitle: "Не удалось открыть профиль. Попробуйте ещё раз.",
    blockLoadFailed: "Не удалось загрузить блок. Попробуйте ещё раз.",
    profileLoadFailed: "Не удалось загрузить профиль. Попробуйте ещё раз.",
    bookingLoadFailed: "Не удалось загрузить запись. Попробуйте ещё раз.",
    servicesLoadFailed: "Не удалось загрузить услуги. Попробуйте ещё раз.",
    reviewsLoadFailed: "Не удалось загрузить отзывы. Попробуйте ещё раз.",
    notFound: "Профиль не найден",
    masterNotFound: "Мастер не найден",
    masterNotFoundDesc: "Профиль мастера не опубликован или находится на доработке.",
    masterUnpublishedDesc: "Профиль мастера временно скрыт. Возможно, он вернётся совсем скоро.",
    studioNotFound: "Студия не найдена",
    studioNotFoundDesc: "Профиль студии не опубликован или находится на доработке.",
    studioUnpublishedDesc: "Профиль студии временно скрыт. Возможно, он вернётся совсем скоро.",
    goToCatalog: "Перейти в каталог",
    categoriesTitle: "Категории",
    studioBookingTitle: "Запись через студию",
    studioBookingDescription: "Этот мастер принимает записи через студийный календарь.",
    studioBookingCta: "Открыть запись в студии",
    // STUDIO-MASTER-OWN-BOOKINGS-01: у мастера студии со своими услугами.
    studioBookingAlso: "Услуги студии — запись через студию",
    ownerViewTitle: "Это ваш профиль",
    ownerViewHint: "Так вашу страницу видят клиенты. Запись к самому себе недоступна.",
    ownerViewEditCta: "Редактировать профиль",
    bookNow: "Записаться",
    sectionServices: "Услуги",
    sectionPortfolio: "Портфолио",
    sectionReviews: "Отзывы",
  },
  hero: {
    share: "Поделиться",
    address: "Адрес",
    shareSuccess: "Ссылка скопирована",
    shareFailed: "Не удалось поделиться. Попробуйте ещё раз.",
    premiumBadge: "PREMIUM",
    noReviewsYet: "Пока без отзывов",
    availableTodayTemplate: "Сегодня свободно с {time}",
    availableLaterTemplate: "Ближайшее окошко — {date}",
    availableNone: "Свободных окошек пока нет",
    experienceTemplate: "На МастерРядом {value}",
    experienceMonthsTemplate: "{count} мес.",
    experienceYearsTemplate: "{count} {unit}",
    yearUnitOne: "год",
    yearUnitFew: "года",
    yearUnitMany: "лет",
    breadcrumbCatalog: "Каталог",
    // QA-115 (FIX-06): studio affiliation shown when the master belongs to a studio.
    studioAffiliationTemplate: "Часть студии «{name}»",
  },
  tabs: {
    services: "Услуги",
    portfolio: "Портфолио",
    reviews: "Отзывы",
    about: "О мастере",
  },
  about: {
    heading: "О мастере",
    descriptionFallback: "Мастер пока не добавил описание профиля.",
  },
  map: {
    heading: "Где находится",
    eyebrow: "Адрес",
    directions: "Маршрут",
    noAddress: "Адрес не указан",
  },
  bundles: {
    eyebrow: "Комплекты",
    heading: "Услуги в комплекте",
    includesLabel: "В комплект входит",
    durationTemplate: "{minutes} мин",
    finalPriceLabel: "Цена комплекта",
    youSaveTemplate: "Экономия {amount}",
    bookingComingSoon: "Запись на пакеты — скоро",
    bookingComingSoonDesc: "Сейчас доступна запись на отдельные услуги из комплекта.",
  },
  packageBooking: {
    cta: "Записаться на пакет",
    buildHint:
      "Выберите дату и время для каждой услуги. Услуги идут одна за другой — одна оплата со скидкой комплекта.",
    componentLabel: "Услуга {index} из {total}",
    waitingPrevious: "Доступно после выбора предыдущих услуг",
    change: "Изменить",
    noSlotsAfterPrevious: "После предыдущей услуги в этот день окошек не осталось. Выберите другой день.",
    startNote: "Все услуги пакета — у одного мастера, одна оплата со скидкой комплекта.",
    // error-hint-ok: своё действие — проверить выбранное время
    proposeError: "Не удалось собрать пакет. Проверьте выбранное время.",
    proposing: "Рассчитываем…",
    toReview: "Продолжить",
    networkError: "Не удалось связаться с сервером. Попробуйте ещё раз.",
    bookError: "Не удалось записать пакет. Попробуйте ещё раз.",
    back: "Назад",
    total: "Итого со скидкой",
    continue: "Продолжить",
    nameLabel: "Имя",
    // FIX-NAME-HINT: «Как к вам обращаться» звало назвать одно имя, а
    // подсказка под полем (`common.ownNameHint`) просит фамилию и имя.
    namePlaceholder: "Фамилия и имя",
    phoneLabel: "Телефон",
    phonePlaceholder: "+7 999 123-45-67",
    commentLabel: "Комментарий (необязательно)",
    commentPlaceholder: "Пожелания к записи",
    bookingAs: "Записываем как {name}",
    nameRequired: "Укажите имя.",
    phoneInvalid: "Проверьте номер телефона.",
    submit: "Записаться на пакет",
    submitting: "Записываем…",
    successTitle: "Вы записаны на пакет",
    successBody: "Все услуги пакета записаны последовательно. Мастер подтвердит запись.",
    close: "Закрыть",
  },
  services: {
    // FIX-D1 (F7): у секции не было пустого состояния вовсе — заголовок
    // висел без карточек, и страница читалась как сломанная. Формулировка и
    // оформление — как у соседней «Портфолио», разводить их не за что.
    empty: "Пока нет услуг",
    title: "Услуги",
    add: "Добавить",
    remove: "Удалить",
    priceOnRequest: "Цена по запросу",
    categoryOther: "Другие услуги",
  },
  portfolio: {
    title: "Портфолио",
    empty: "Пока нет работ",
    viewError: "Не удалось загрузить работу. Попробуйте ещё раз.",
    untitledWork: "Работа мастера",
    indexedBadge: "✓ В поиске",
    close: "Закрыть",
    loading: "Загружаем работу…",
    bookThisService: "Записаться на услугу",
  },
  reviews: {
    title: "Отзывы",
    // REVIEWS-LOADMORE-01: `all` («Все отзывы») removed with the dialog it
    // opened — that dialog hard-capped limit=50 and silently truncated any
    // provider with more reviews while claiming to show «все». Reviews now
    // page inline via `loadMore`. No other caller referenced `all`.
    loadMore: "Показать больше отзывов",
    loadMoreLoading: "Загружаем…",
    leaveReview: "Оставить отзыв",
    noReviews: "Отзывов пока нет — станьте первым",
    loadFailed: "Не удалось загрузить отзывы. Попробуйте ещё раз.",
    masterReply: "Ответ мастера",
    // STUDIO-REVIEW-MASTER-RATING: отзыв о визите в студию на странице мастера.
    studioReply: "Ответ студии",
    studioVisit: "визит в студию",
    summaryButton: "Показать резюме",
    summaryTitle: "Что говорят клиенты",
    summaryLoading: "Анализируем отзывы…",
    summaryFewReviews: "Пока недостаточно отзывов для резюме",
    summaryFailed: "Резюме временно недоступно. Попробуйте через минуту.",
  },
  booking: {
    title: "Запись",
    // FIX-BATCH-C Defect 2: distinct empty states.
    // `emptyTitle`/`emptyDesc` = genuine no-services-at-all (empty catalog).
    // `selectServiceTitle`/`selectServiceDesc` = has services but the client
    // hasn't picked one yet (empty cart) — must NOT claim the master has no services.
    emptyTitle: "Онлайн-запись пока недоступна",
    emptyDesc: "Мастер ещё не добавил услуги для записи. Загляните позже или свяжитесь с ним напрямую.",
    selectServiceTitle: "Выберите услугу, чтобы записаться",
    selectServiceDesc: "Отметьте услугу в списке — и мы подберём свободное время.",
    chooseTime: "Выбрать время",
    backToCart: "Назад к корзине",
    continueToConfirm: "Продолжить",
    confirm: "Записаться",
    comment: "Комментарий",
    commentPlaceholder: "Например: буду на 5 минут раньше",
    bookingOnPhone: "Запись на номер",
    authRequiredTitle: "Войдите, чтобы завершить запись",
    authRequiredHint: "Нужен только номер телефона — без паролей.",
    phoneLabel: "Телефон",
    phonePlaceholder: "+79001234567",
    loginAndContinue: "Войти и продолжить",
    success: "Запись создана — ждём вас",
    submitFailed: "Не удалось создать запись. Попробуйте ещё раз.",
    // LOGIC-10: ответ «этот же запрос ещё выполняется» — не отказ и не
    // занятое время. Раньше на его месте показывался экран «время занято»,
    // хотя бронь, скорее всего, уже создана.
    submitInFlight: "Мы уже создаём вашу запись. Подождите несколько секунд и обновите страницу.",
    bookingConfigLoading: "Загружаем вопросы мастера…",
    bookingConfigTitle: "Вопросы для клиента",
    referencePhotoLabel: "Фото-референс",
    referencePhotoPick: "Выбрать фото",
    referencePhotoUploading: "Загружаем фото…",
    referencePhotoAlt: "Фото-референс",
    bookingAnswerPlaceholder: "Ваш ответ",
    bookingConfigLoadFailed: "Не удалось загрузить вопросы мастера. Попробуйте ещё раз.",
    referencePhotoRequired: "Нужен фото-референс для записи.",
    requiredQuestions: "Ответьте на обязательные вопросы.",
    silentModeAria: "Хочу помолчать",
    silentModeTitle: "Хочу помолчать 🤫",
    silentModeDesc: "Мастер поздоровается, уточнит детали и дальше будет работать без разговоров.",
    clientFallbackName: "Клиент",
    total: "Итого",
    duration: "Время",
  },
  slots: {
    loadingSlots: "Загружаем окошки…",
    noSlots: "На ближайшие дни свободных мест нет — попробуйте другую дату.",
    refresh: "Обновить",
    showMoreWeek: "Показать ещё неделю",
    allBusy: "Всё занято",
    nextWeek: "Следующая неделя",
    prevWeek: "Предыдущая неделя",
    chooseDay: "Когда удобно?",
    chooseSlot: "Выберите время",
    emptyForDay: "Свободных окошек на этот день нет",
    noSlotsForDay: "На выбранный день свободных окошек нет.",
    loadFailed: "Не удалось загрузить свободные окошки. Попробуйте ещё раз.",
    slotTaken: "Это время уже заняли — выберите другое.",
    hotBadge: "Горящее окошко",
    subscribeHot: "Уведомить о горящих окошках",
    unsubscribeHot: "Вы подписаны",
    subscribeLoading: "Сохраняем…",
    // FIX-C8: дефолт кнопки подписки — только для отказа БЕЗ тела (обрыв
    // сети, 5xx). Действенные отказы («Достигнут лимит подписок.») приходят
    // со своей курируемой строкой и показываются как есть.
    subscribeFailed: "Не удалось изменить подписку. Попробуйте ещё раз.",
    // 29.09 доработки · 16 (Ю1, вариант В): скидочные «горящие окошки» —
    // реклама, приходят только с согласием на акции; «окошко освободилось» —
    // по подписке.
    marketingOptIn: "Получать акции мастеров — скидки в горящих окошках",
    marketingOptInFailed: "Не удалось сохранить согласие на акции. Попробуйте ещё раз.",
    periodMorning: "Утро",
    periodDay: "День",
    periodEvening: "Вечер",
  },
  bookingFlow: {
    // 29.09 доработки · 10: отмена с экрана успеха раньше молча не удавалась.
    cancelFailed: "Не удалось отменить запись. Попробуйте ещё раз.",
    stepDate: "Дата",
    stepTime: "Время",
    stepContacts: "Контакты",
    stepConfirm: "Подтверждение",
    next: "Далее",
    back: "Назад",
    bookCta: "Записаться",
    calendarLoading: "Загружаем дни…",
    calendarLoadMore: "Ещё недели",
    calendarNoAvailable: "Нет доступных дней",
    daysOfWeek: ["Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Вс"] as string[],
    months: [
      "Январь",
      "Февраль",
      "Март",
      "Апрель",
      "Май",
      "Июнь",
      "Июль",
      "Август",
      "Сентябрь",
      "Октябрь",
      "Ноябрь",
      "Декабрь",
    ] as string[],
    monthsGenitive: [
      "января",
      "февраля",
      "марта",
      "апреля",
      "мая",
      "июня",
      "июля",
      "августа",
      "сентября",
      "октября",
      "ноября",
      "декабря",
    ] as string[],
    slotsLoading: "Загружаем окошки…",
    noSlotsForDay: "На этот день нет свободных окошек",
    slotsLoadFailed: "Не удалось загрузить свободные окошки. Попробуйте ещё раз.",
    summarySelectDateTime: "Выберите дату и время",
    summaryService: "Услуга",
    summaryDateTime: "Дата и время",
    confirmTitle: "Проверьте данные",
    confirmService: "Услуга",
    confirmDateTime: "Дата и время",
    confirmPhone: "Телефон",
    confirmComment: "Комментарий",
    confirmNoComment: "Без комментария",
    confirmSilentMode: "Режим тишины включён",
    successTitle: "Запись создана",
    successSubtitle: "Ждём вас — увидимся скоро.",
    successMyBookings: "Мои записи",
    successBackToMaster: "Вернуться к мастеру",
  },
  bookingWidget: {
    headerEyebrow: "Запись · от",
    dateLabel: "Дата",
    timeLabel: "Время",
    prevWeek: "Предыдущая неделя",
    nextWeek: "Следующая неделя",
    daysLoadFailed: "Не удалось загрузить дни. Попробуйте ещё раз.",
    // QA-122 (FIX-10): clear, accurate empty state for a 0-slot day. The old
    // "мастер занят" implied the master is busy; for an exhausted today the
    // window has simply passed. `emptyDayToday` is shown when the selected day
    // is today (provider tz) and no bookable slots remain.
    emptyDay: "Свободных окошек в этот день нет",
    emptyDayToday: "На сегодня свободных окошек не осталось",
    summaryTotal: "Итого",
    summaryDateTimePending: "Выберите дату и время",
    continueCta: "Продолжить",
    submitCta: "Записаться",
    // AUTH-GATE-01: was «Подтверждение придёт SMS». That claim was never
    // true — `sendOtpSms` is the ONLY SMS call site in the codebase (login
    // OTP), so a booking has never triggered an SMS, for guests or for
    // registered clients. Replaced with what the flow actually does: the
    // success phase renders the full booking card immediately.
    footnoteSelectionConfirm: "Детали записи покажем сразу после оформления",
    footnoteSelectionPay: "Оплата на месте",
    // RKN-FIX-02: the old copy («Нажимая, вы соглашаетесь с условиями») was
    // конклюдентное consent — void since 01.09.2025. Consent is now a real
    // act (checkboxes above the CTA); what remains is an informational line
    // for people who are already signed in, and it claims nothing legal.
    footnoteFormPay: "Оплата на месте — картой или наличными",
    formContactsEyebrow: "Ваши контакты",
    formBackToSelection: "Изменить время",
    phoneLabel: "Телефон",
    phonePlaceholder: "+7 (___) ___-__-__",
    nameLabel: "Имя",
    namePlaceholder: "Фамилия и имя",
    commentLabel: "Комментарий — необязательно",
    commentPlaceholder: "Любые пожелания",
    errorPhoneInvalid: "Проверьте номер телефона.",
    errorNameRequired: "Укажите имя.",
    errorNetwork: "Не удалось связаться с сервером. Попробуйте ещё раз.",
    successEyebrow: "Вы записаны",
    successHeadlineTemplate: "{name} ждёт вас",
    // Запись ждёт подтверждения мастера (PENDING / NEW): «ждёт вас» было бы неправдой.
    successPendingEyebrow: "Запись отправлена",
    successPendingHeadlineTemplate: "{name} подтвердит запись",
    successPendingHeadlineFallback: "Мастер подтвердит запись",
    successPendingNote: (hours: number) =>
      `Если мастер не подтвердит её за ${hours} ч, запись отменится. Ответ придёт в уведомлениях.`,
    // На номер ничего не отправляется (SMS только для кода входа) — это номер, на который записали.
    successPhoneLabel: "Записали на номер",
    successGoToCabinet: "В личный кабинет",
    successCancelAuth: "Отменить запись",
    successCancelGuest: "Отменить — войдите в аккаунт",
    conflictHeading: "Окошко уже занято",
    conflictBody:
      "Кто-то записался первым на это время. Выберите другое — обычно есть много вариантов.",
    conflictRetry: "Выбрать другое время",
    weekdaysShort: ["Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Вс"] as string[],
    monthsGenitive: [
      "января",
      "февраля",
      "марта",
      "апреля",
      "мая",
      "июня",
      "июля",
      "августа",
      "сентября",
      "октября",
      "ноября",
      "декабря",
    ] as string[],
  },
} as const;
