import { pluralize } from "@/lib/utils/pluralize";

export const studioCabinet = {
  layout: {
    studioFallbackName: "Студия",
    publicUsernameHint: "Придумайте короткий адрес страницы — по нему клиенты вас найдут",
  },
  teamTabs: {
    all: "Все мастера",
    workingToday: "Работают сегодня",
  },
  teamPage: {
    title: "Команда студии",
    subtitle: "Управляйте мастерами и расписанием смен.",
    statusFree: "Свободен",
    statusBusy: "Занят",
    shiftTemplate: "Смена {start}–{end}",
    bookingsInfoTemplate: "Записей: {count} • Ближайшее окошко в {time}",
    emptyActiveShifts: "Сегодня нет активных смен.",
  },
  teamAdd: {
    title: "Добавить мастера",
    subtitle: "Приглашайте мастеров по номеру телефона.",
    info: "Перейдите в раздел «Команда» для управления мастерами.",
    back: "Вернуться в Команду",
  },
  teamCard: {
    viewSchedule: "Посмотреть расписание",
  },
  settings: {
    sidebarTitle: "Настройки",
    profile: "Профиль студии",
    services: "Услуги и прайс",
    portfolio: "Портфолио",
    general: "Настройки записей",
    features: "Возможности",
    publicPage: "Публичная страница",
    billing: "Тариф",
  },
  // SCHEDULE-PATTERNS-01 (этап 4): «График команды» — мастера студии × дни.
  scheduleTeam: {
    breadcrumb: "Студия · Расписание",
    title: "График команды",
    subtitle: "Кто и когда работает. Нажмите на день мастера, чтобы изменить его, или выберите кисть.",
    masterColumn: "Мастер",
    endingSoon: (date: string) => `Настроено до ${date}`,
    coverageLabel: "Работают",
    noCoverageAria: "никто не работает",
    prevAria: "Предыдущая неделя",
    nextAria: "Следующая неделя",
    todayCta: "Сегодня",
    setScheduleCta: "Задать график",
    rhythmCta: "График по очереди",
    settingsLink: "Настройки мастера",
    emptyTitle: "Нет активных мастеров",
    emptyHint: "Когда мастера примут приглашение, здесь появится их график.",
    loadError: "Не удалось загрузить график команды. Попробуйте ещё раз.",
    saveError: "Не удалось сохранить день. Попробуйте ещё раз.",
    retry: "Повторить",
    noSchedule: "График не настроен",
    rhythm: {
      title: "График по очереди",
      hint: "Один график нескольким мастерам. «По очереди» сдвигает их так, чтобы рабочие дни чередовались.",
      mastersLabel: "Мастера",
      presetLabel: "График",
      firstDayLabel: "Первый рабочий день",
      staggerLabel: "По очереди",
      staggerHint: "Второй мастер начинает, когда у первого выходные, и так далее.",
      autoExtendLabel: "Продлевать автоматически",
      endLabel: "До какого дня",
      apply: "Применить",
      applying: "Применяем…",
      noMasters: "Выберите хотя бы одного мастера.",
      failed: (name: string) => `Не удалось применить график мастеру ${name}. Попробуйте ещё раз.`,
      coveragePreview: "Покрытие по дням",
    },
  },
  nav: {
    home: "Главная",
    calendar: "Календарь",
    scheduleRequests: "Заявки на расписание",
    team: "Команда",
    clients: "Клиенты",
    reviews: "Отзывы",
    services: "Услуги",
    analytics: "Аналитика",
    billing: "Тарифы",
    settingsAria: "Настройки",
    myPage: "Страница студии",
    lockedHint: "Доступно с тарифа PRO",
    ariaLabel: "Навигация студии",
    groups: {
      studio: "Студия",
      team: "Команда",
      clients: "Клиенты",
      business: "Бизнес",
      studioMeta: "Настройки студии",
      studioMetaExternal: "Внешние",
    },
    items: {
      dashboard: "Главная",
      schedule: "Расписание",
      // STUDIO-SCHEDULE-SETTINGS-A: schedule-settings sidebar label.
      scheduleSettings: "Настройки расписания",
      // SCHEDULE-PATTERNS-01 (этап 4): доска смен команды.
      teamSchedule: "График команды",
      scheduleRequests: "Заявки",
      bookings: "Записи",
      masters: "Мастера",
      services: "Услуги",
      clients: "Клиенты",
      reviews: "Отзывы",
      notifications: "Уведомления",
      analytics: "Аналитика",
      // STUDIO-CLEANUP-FIX-A #9: `publicPage` sidebar label kept
      // for backwards-compat (other consumers may reference it) but
      // its sidebar entry was removed — the page was a misleading
      // `redirect("/cabinet/studio/settings")`. `publicPageExternal`
      // remains in active use for the «Open studio page» link.
      publicPage: "Публичная страница",
      publicPageExternal: "Открыть страницу студии",
      settings: "Настройки",
    },
  },
  appCaption: "КАБИНЕТ СТУДИИ",
  userChip: {
    currentContext: "{studio}",
  },
  bottomNav: {
    more: "Ещё",
    moreTitle: "Дополнительно",
    close: "Закрыть",
    // NAV-STUDIO-SETTINGS-TAB — вкладка раздела «Профиль» настроек студии.
    profile: "Профиль",
  },
  dashboard: {
    title: "Главная",
    subtitle: "Ключевые показатели студии на сегодня.",
    emptyHint: "Данные появятся после первых записей",
    quickActions: {
      title: "Быстрые действия",
      inviteMaster: "Пригласить мастера",
      addService: "Добавить услугу",
      viewFinance: "Посмотреть финансы",
      shareStudio: "Страница студии",
    },
    cards: {
      bookingsToday: "Записи сегодня",
      mastersOnShift: "Мастера в смене",
      newClients: "Новые клиенты",
      reviews: "Отзывы",
    },
    bookingsAmountPrefix: "На {amount}",
    mastersWorking: "Работают сегодня",
    newClientsWindow: "За последние 24 ч",
    reviewsWindow: "За последние 7 дней",
    reviewsValue: "{count} новых",
    mastersCountTemplate: "{working} из {total}",
    plural: {
      booking: {
        one: "запись",
        few: "записи",
        many: "записей",
      },
      client: {
        one: "клиент",
        few: "клиента",
        many: "клиентов",
      },
    },
  },
  calendar: {
    title: "Календарь",
    subtitle: "Записи и закрытое время студии в одном месте.",
    day: "День",
    week: "Неделя",
    month: "Месяц",
    searchPlaceholder: "Поиск клиента, телефона или услуги",
    allMasters: "Все мастера",
    allCategories: "Все категории",
    allServices: "Все услуги",
    allStatuses: "Все записи",
    loading: "Загружаем календарь…",
    noMasters: "Нет мастеров",
    noMastersHint: "Сначала добавьте мастеров в команду.",
    goToTeam: "К команде",
    blocksLabel: "Закрытое время",
    noItemsForDay: "На этот день ничего нет.",
    dayDetails: "Детали дня",
    timeNotSet: "Время не указано",
    loadFailed: "Не удалось загрузить календарь. Попробуйте ещё раз.",
    masterScheduleTitle: "График мастеров студии",
    masterScheduleDescription: "Выберите мастера и настройте его личный график.",
    masterPublished: "Профиль опубликован",
    masterHidden: "Профиль скрыт",
    draftNote: "У каждого мастера свой черновик — он не пропадёт, пока вы не сохраните его график.",
    scheduleOf: "Расписание мастера:",
    editing: "Редактируете:",
    weekdays: {
      mon: "Пн",
      tue: "Вт",
      wed: "Ср",
      thu: "Чт",
      fri: "Пт",
      sat: "Сб",
      sun: "Вс",
    },
  },
  clientsPage: {
    title: "Клиенты",
    subtitle: "База клиентов студии",
  },
  profile: {
    loading: "Загружаем профиль студии…",
    sectionTitle: "Профиль студии",
    portfolioTitle: "Портфолио",
    profileSaved: "Профиль сохранён",
    bannerSaved: "Баннер сохранён",
    bannerUploaded: "Баннер загружен",
    loadFailed: "Не удалось загрузить профиль студии. Попробуйте ещё раз.",
    saveFailed: "Не удалось сохранить профиль студии. Попробуйте ещё раз.",
    saveBannerFailed: "Не удалось сохранить баннер. Попробуйте ещё раз.",
    uploadBannerFailed: "Не удалось загрузить баннер. Попробуйте ещё раз.",
    nameLabel: "Название",
    descriptionLabel: "Описание",
    addressLabel: "Адрес",
    phoneLabel: "Телефон",
    emailLabel: "Email",
    telegramLabel: "Telegram",
    instagramLabel: "Instagram",
    vkLabel: "VK",
    namePlaceholder: "Название студии",
    taglinePlaceholder: "Слоган",
    addressPlaceholder: "Начните вводить адрес…",
    districtPlaceholder: "Район",
    contactNamePlaceholder: "Контактное лицо",
    contactPhonePlaceholder: "Контактный телефон",
    contactEmailPlaceholder: "Контактный email",
    phonePlaceholder: "+7 900 000 00 00",
    emailPlaceholder: "studio@email.com",
    telegramPlaceholder: "@username",
    instagramPlaceholder: "https://instagram.com/username",
    vkPlaceholder: "vk.ru/studio",
    categoriesPlaceholder: "Категории (через запятую)",
    descriptionPlaceholder: "Расскажите о студии — атмосфера, специализация, команда",
    published: "Опубликовано",
    saveProfile: "Сохранить профиль",
    saving: "Сохраняем…",
    selectAddressAria: "Выбрать адрес {address}",
    avatarTitle: "Аватар",
    avatarHint: "Главное фото студии для каталога и профиля.",
    bannerTitle: "Баннер",
    bannerHint: "Широкая обложка для публичной страницы.",
    noBanner: "Баннер не выбран",
    bannerPlaceholder: "Обложка студии",
    uploadBanner: "Загрузить баннер",
    clearBanner: "Убрать баннер",
    changeBanner: "Изменить обложку",
    focalPoint: "Точка фокуса",
    studioBannerAlt: "Баннер студии",
    useAsBannerAria: "Использовать как баннер",
  },
  routes: {
    servicesTitle: "Услуги",
    servicesSubtitle: "Прайс, категории и назначение мастеров.",
    teamTitle: "Команда",
    teamSubtitle: "Добавляйте мастеров и смотрите, кто сейчас работает.",
    clientsTitle: "Клиенты",
    clientsSubtitle: "Список клиентов из записей студии.",
  },
  services: {
    loading: "Загружаем услуги…",
    summary: "Разделы: {categories} / Услуги: {services}",
    createSection: "Создать раздел",
    addService: "Добавить услугу",
    noServicesTitle: "Услуг пока нет",
    noServicesDescription: "Добавьте услугу — клиенты смогут сразу записываться.",
    selectMaster: "Выберите мастера",
    assignMaster: "Назначить",
    durationMin: "мин",
    currency: "₽",
    visibleInSearch: "Виден в поиске",
    visibleInSearchHint: "Услуга будет видна в каталоге и поиске.",
    createSectionTitle: "Новый раздел",
    sectionTitlePlaceholder: "Название раздела",
    createServiceTitle: "Новая услуга",
    selectCategory: "Категория",
    selectCategoryHint: "Услуга будет видна в этой категории в каталоге",
    noCategoryOption: "Без категории",
    proposeCategoryLink: "Предложить свою категорию",
    proposeCategoryTitle: "Предложить категорию",
    proposeCategoryHint: "Категория будет отправлена на модерацию.",
    proposeCategoryNamePlaceholder: "Название категории",
    proposeCategorySend: "Отправить",
    proposeCategorySent: "Категория отправлена на модерацию.",
    proposeCategoryFailed: "Не удалось отправить категорию на модерацию. Попробуйте ещё раз.",
    sectionLabel: "Раздел в студии",
    sectionHint: "Так услуги сгруппированы в вашем кабинете",
    defaultSectionName: "Основные",
    autoSectionFailed: "Не удалось создать раздел. Попробуйте ещё раз.",
    assignMastersToggle: "Назначить мастеров сразу",
    noMastersHint: "Сначала добавьте мастеров студии.",
    selectAll: "Выбрать всех",
    clearSelection: "Очистить",
    assignPartialError: "Услуга создана, но не всех мастеров удалось назначить ({failed} из {total}). Проверьте список.",
    updateCategoryFailed: "Не удалось обновить категорию услуги. Попробуйте ещё раз.",
    masterFallbackName: "Мастер",
    notAssigned: "Не назначено ни одному мастеру",
    assignedOne: "Назначено 1 мастеру",
    assignedMany: "Назначено {count} мастерам",
    noCategoryBadge: "Без категории",
    savingCategory: "Сохраняем…",
    saveCategory: "Сохранить категорию",
    activeOn: "Включена",
    activeOff: "Выключена",
    serviceTitlePlaceholder: "Например: Маникюр с гель-лаком",
    pricePlaceholder: "1500",
    durationPlaceholder: "60",
    cancel: "Отмена",
    save: "Сохранить",
    creating: "Сохраняем…",
    loadFailed: "Не удалось загрузить услуги. Попробуйте ещё раз.",
    assignFailed: "Не удалось назначить мастера. Попробуйте ещё раз.",
    createSectionFailed: "Не удалось создать раздел. Попробуйте ещё раз.",
    createServiceFailed: "Не удалось создать услугу. Попробуйте ещё раз.",
  },
  team: {
    loading: "Загружаем команду…",
    mastersCount: "Мастеров: {count}",
    noLimit: "Без ограничений",
    limitReachedMessage: "На вашем тарифе больше мастеров не добавить. Перейдите на тариф выше.",
    viewPlans: "Смотреть тарифы",
    addMaster: "Добавить мастера",
    noMastersTitle: "Мастеров пока нет",
    noMastersDescription: "Пригласите первого мастера — и сразу начнёте принимать записи.",
    pending: "Ожидает подтверждения",
    active: "Работает",
    addMasterTitle: "Новый мастер",
    masterNamePlaceholder: "Имя мастера",
    phonePlaceholder: "+7 999 123-45-67",
    titlePlaceholder: "Должность",
    cancel: "Отмена",
    save: "Сохранить",
    creating: "Сохраняем…",
    requiredError: "Заполните имя, телефон и должность. Телефон — в формате +7 999 123-45-67.",
    loadFailed: "Не удалось загрузить мастеров. Попробуйте ещё раз.",
    createFailed: "Не удалось добавить мастера. Попробуйте ещё раз.",
    roleSeparator: " • ",
  },
  reviews: {
    subtitle: "Новые и неотвеченные отзывы клиентов студии.",
    loadFailed: "Не удалось загрузить отзывы. Попробуйте ещё раз.",
    total: "Всего",
    new: "Новые",
    unanswered: "Неотвеченные",
    all: "Все",
    loading: "Загружаем отзывы…",
    emptyFilter: "По выбранному фильтру отзывов пока нет.",
    noText: "Без текста",
  },
  clients: {
    loading: "Загружаем клиентов…",
    empty: "Клиентов пока нет — они появятся сами после первых записей.",
    loadFailed: "Не удалось загрузить клиентов. Попробуйте ещё раз.",
    moneySuffix: "₽",
    upgradeTitle: "Доступно на тарифе PRO",
    upgradeDescription: "Заметки, метки, фото работ и история визитов доступны с тарифа PRO.",
    upgradeCta: "Перейти к тарифам",
    columns: {
      client: "Клиент",
      phone: "Телефон",
      lastBooking: "Последняя запись",
      service: "Услуга",
      visits: "Посещения",
      amount: "Сумма",
    },
  },
  dashboardV2: {
    banner: {
      title: (studioName: string, count: number) =>
        `«${studioName}»: сегодня ${count} ${pluralize(count, "запись", "записи", "записей")}`,
      subtitleTemplate: "{onShift} мастеров на смене, средняя загрузка {load}%.",
      onShiftLabel: "Сейчас на смене",
      outOfTemplate: "из {total}",
    },
    kpis: {
      revenue: {
        label: "Выручка за 30 дней",
        subtitle: "к прошлому месяцу",
      },
      bookings: {
        label: "Записей за 30 дней",
        averageCheckTemplate: "средний чек {amount}",
      },
      occupancy: {
        label: "Загружаем студию",
        subtitle: "{count} мастеров на смене",
      },
      rating: {
        label: "Средний рейтинг",
        subtitle: "{count} отзывов",
      },
    },
    topMasters: {
      title: "ТОП-мастера",
      subtitle: "По выручке за 30 дней",
      seeAll: "Все мастера",
      bookingsTemplate: "{count} записей",
      empty: "За последний месяц записей не было.",
    },
    attention: {
      title: "Требуют внимания",
      subtitleTemplate: "{count} задач · {urgent} срочных",
      empty: "Очередь пуста",
      emptyBody: "Всё под контролем.",
      urgentLabel: "Срочно",
      items: {
        pendingMastersTitle: "Заявок мастеров: {count}",
        pendingMastersAction: "Открыть",
        bookingsAwaitingTitle: "Записей ждут подтверждения: {count}",
        bookingsAwaitingAction: "Записи",
        reviewsUnansweredTitle: "Отзывов без ответа: {count}",
        reviewsUnansweredAction: "Ответить",
        scheduleRequestsTitle: "Заявок на расписание: {count}",
        scheduleRequestsAction: "Решить",
      },
    },
    topOccupancy: {
      title: "Топ загруженности",
      subtitle: "Сегодня",
      slotsTemplate: "{booked} из {total} записей",
      empty: "Сегодня свободный день.",
    },
    popularServices: {
      title: "Популярные услуги",
      subtitle: "За 30 дней",
      countTemplate: "{count} раз · {percent}% всех записей",
      empty: "Нет данных за выбранный период.",
    },
    revenueChart: {
      periodAria: "Период выручки",
      title: "Выручка по мастерам",
      totalLabel: "за период",
      bookingsTemplate: "{count} записей",
      periodSelector: {
        "7d": "7д",
        "30d": "30д",
        "90d": "90д",
        "365d": "Год",
      },
      empty: "Нет данных за выбранный период.",
      error: "Не удалось загрузить данные. Попробуйте ещё раз.",
    },
  },
  // STUDIO-SCHEDULE-SETTINGS-A Phase A — page text. Phase B will
  // add `breaks` / `exceptions` / `visibility` subtrees alongside.
  scheduleSettings: {
    breadcrumb: "Настройки расписания",
    title: "Настройки расписания",
    studioSubtitle:
      "График, календарь на 3 месяца, часы и правила записи — отдельно для каждого мастера студии.",
    noMastersTitle: "Нет активных мастеров",
    noMastersHint:
      "Чтобы настроить расписание, добавьте в студию хотя бы одного мастера и допустите его к записи.",
    tabs: {
      calendar: "Календарь",
      hours: "Часы",
      rules: "Правила",
      breaks: "Перерывы",
      visibility: "Видимость",
    },
    masterPicker: {
      label: "Мастер",
      hint: "Всё, что ниже, — про выбранного мастера.",
    },
    hours: {
      workdayAriaTemplate: "Рабочий день: {day}",
      fromLabel: "с",
      toLabel: "до",
      dayOffLabel: "выходной",
      saveLabel: "Сохранить",
      savingLabel: "Сохраняем…",
      savedHint: "Расписание сохранено.",
    },
    rules: {
      minHoursTitle: "Минимум за",
      minHoursHint:
        "За сколько часов до визита клиент должен записаться.",
      maxDaysTitle: "Максимум за",
      maxDaysHint: "На сколько дней вперёд открыта запись.",
      autoConfirmTitle: "Автоподтверждение",
      autoConfirmHint:
        "Запись подтверждается автоматически без участия мастера.",
      freeCancelTitle: "Бесплатная отмена за",
      freeCancelHint:
        "За сколько часов до визита клиент может отменить бесплатно.",
      freeCancelToggleAria: "Включить бесплатную отмену",
      saveLabel: "Сохранить",
      savingLabel: "Сохраняем…",
      savedHint: "Правила сохранены.",
    },
    errors: {
      save: "Не удалось сохранить. Попробуйте ещё раз.",
      // STUDIO-SCHEDULE-SETTINGS-A Phase B — exception validation.
      exceptionDatePast: "Дата особого дня не может быть в прошлом.",
      exceptionEndBeforeStart:
        "Время окончания должно быть позже времени начала.",
      exceptionDuplicateDate:
        "Особый день на эту дату уже добавлен. Измените существующее.",
    },
    // STUDIO-SCHEDULE-SETTINGS-A Phase B — Breaks tab. Mirrors the
    // master cabinet's «just buffer» version (the recurring-breaks
    // editor was rolled back — single source of truth is the
    // schedule editor itself).
    breaks: {
      bufferTitle: "Пауза между записями",
      bufferHint:
        "Сколько минут после каждой записи не принимать следующую — на уборку и подготовку.",
      minutesSuffix: "мин",
      recurringBreaksHint:
        "Регулярные перерывы (например, обед) задаются прямо в расписании на вкладке «Часы». Здесь — только пауза между записями.",
      saveLabel: "Сохранить",
      savingLabel: "Сохраняем…",
      savedHint: "Настройка сохранена.",
    },
    // STUDIO-SCHEDULE-SETTINGS-A Phase B — Visibility tab.
    visibility: {
      // STUDIO-PAUSE-SPLIT-01: личную страницу мастера скрывает только он
      // сам; студия ставит мастера на паузу в разделе «Мастера».
      personalVisibilityNote:
        "Личную страницу мастера в каталоге включает и скрывает сам мастер. Чтобы мастер временно не принимал записи в студии, поставьте его на паузу в разделе «Мастера».",
      slotPrecisionTitle: "Точность времени",
      slotPrecisionHint:
        "Что видит клиент в каталоге: точное время, «сегодня свободно» или только даты.",
      slotPrecisionLabels: {
        exact: "Точное время",
        today_free: "Сегодня свободно",
        date_only: "Только дата",
      },
      visibleSlotDaysTitle: "Сколько окошек вперёд",
      visibleSlotDaysHint: "Сколько дней вперёд клиент видит свободные окошки.",
      acceptNewClientsTitle: "Принимает новых клиентов",
      acceptNewClientsHint:
        "Если выключить, новые клиенты не смогут записаться. Существующие — смогут.",
      saveLabel: "Сохранить",
      savingLabel: "Сохраняем…",
      savedHint: "Настройки видимости сохранены.",
    },
  },
  scheduleV2: {
    header: {
      viewAria: "Вид календаря",
      captionTemplate: "{weekday} · {day} {month} {year}",
      title: "Расписание студии",
      subtitleTemplate: "{bookings} записей · {masters} мастеров на смене · загрузка {occupancy}%",
      views: { day: "День", week: "Неделя" },
      prev: "Назад",
      next: "Вперёд",
      today: "Сегодня",
      refresh: "Обновить",
      refreshedAtTemplate: "обновлено {time}",
      addBooking: "Добавить запись",
      manageBreaks: "Перерывы",
      salonTimeNote: "Время студии",
    },
    breakDialog: {
      title: "Перерывы мастеров",
      subtitle: "Перерывы и закрытое время мастеров на этот день.",
      existingTitle: "Перерывы дня",
      addTitle: "Новый перерыв",
      masterLabel: "Мастер",
      startLabel: "Начало",
      endLabel: "Конец",
      noteLabel: "Подпись (необязательно)",
      notePlaceholder: "Обед",
      addButton: "Добавить",
      removeButton: "Удалить перерыв",
      cancel: "Закрыть",
      submitting: "Сохраняем…",
      empty: "На этот день перерывов нет.",
      noMasters: "Сегодня нет доступных мастеров",
    },
    kpis: {
      bookingsToday: "Записей сегодня",
      bookingsConfirmedTemplate: "{count} подтверждено",
      revenue: "Выручка дня (план)",
      revenueSubtitle: "сумма по записям",
      occupancy: "Загрузка",
      occupancyContextTemplate: "{masters} мастеров на смене",
      freeWindows: "Свободные окошки",
      freeWindowsHint: "до конца дня",
    },
    legend: {
      confirmed: "Подтверждено",
      pending: "Ожидает",
      newClient: "Новый клиент",
      break: "Перерыв",
    },
    column: {
      ratingTemplate: "★ {value}",
      unavailable: "Недоступен",
    },
    cell: {
      breakLabel: "Перерыв",
      emptyHint: "Создать запись",
      // BOOKING-STUDIO-RESCHEDULE-PARITY-01: at-a-glance marker on a cell
      // whose client asked to move it — the studio must accept/decline.
      rescheduleBadge: "Клиент просит перенос",
      // STUDIO-MASTER-OWN-BOOKINGS-01: запись с личной страницы мастера —
      // студия видит только, что время занято; управляет ею мастер.
      personalBooking: "Личная запись мастера",
      personalBookingHint: "Мастер принял эту запись сам — ею управляет он",
    },
    // TZ-DISPLAY-SALON-PARITY-01: the datetime-local inputs in the
    // create/move dialogs are edited as SALON-local wall-clock (converted
    // via salon tz), so a cross-tz admin knows they're not editing browser tz.
    salonTimeInputHint: "время студии",
    actions: {
      menuTitle: "Действия с записью",
      // STUDIO-CLEANUP-FIX-A #1г: `details` key removed alongside
      // the «Детали записи» Button it labelled (was a pure no-op).
      moveToMaster: "Перенести на другого мастера",
      moveTime: "Перенести по времени",
      cancel: "Отменить запись",
      // STUDIO-CONFIRM-01: студийные записи рождаются неподтверждёнными, а
      // подтвердить их из кабинета студии было нечем.
      confirm: "Подтвердить запись",
      awaitingConfirmation: "Запись ждёт подтверждения",
      confirmError: "Не удалось подтвердить запись. Попробуйте ещё раз.",
    },
    // BOOKING-STUDIO-RESCHEDULE-PARITY-01: accept/decline a client-proposed
    // reschedule from the calendar cell + journal row action menu (parity with
    // the master side). Reuses `/confirm` + `/decline-reschedule`.
    reschedule: {
      title: "Клиент предложил новое время",
      // FIX-STUDIO-02 (F4): show the CURRENT datetime alongside the proposed
      // one (both with dates) so a cross-day move can't be accepted blindly.
      currentLabel: "Текущее время",
      proposedLabel: "Новое время",
      accept: "Принять новое время",
      decline: "Отклонить перенос",
    },
    createDialog: {
      title: "Новая запись",
      masterLabel: "Мастер",
      masterPlaceholder: "Выберите мастера",
      serviceLabel: "Услуга",
      servicePlaceholder: "Выберите услугу",
      clientLabel: "Имя клиента",
      // FIX-NAME-HINT: пример в порядке «Фамилия Имя» — тот же порядок, о
      // котором просит подсказка `common.clientNameHint` под полем.
      clientPlaceholder: "Соколова Анна",
      phoneLabel: "Телефон клиента",
      phonePlaceholder: "+7 999 123-45-67",
      cancel: "Отмена",
      submit: "Создать запись",
      submitting: "Создаём…",
    },
    moveDialog: {
      titleToMaster: "Перенести на другого мастера",
      titleTime: "Перенести по времени",
      masterLabel: "Мастер",
      // STUDIO-RESCHEDULE-VALIDATION-A: appended in the master
      // picker option label when the master can't perform the
      // booking's service. Option is `disabled`; this suffix
      // explains why.
      masterIncompatibleSuffix: "не выполняет эту услугу",
      masterIncompatibleHint:
        "Этот мастер не выполняет выбранную услугу — выберите другого.",
      cancel: "Отмена",
      confirm: "Перенести",
      submitting: "Переносим…",
    },
    cancelDialog: {
      title: "Отменить запись",
      bodyTemplate: "Запись {client} · {service} будет отменена.",
      reasonLabel: "Причина (необязательно)",
      reasonPlaceholder: "Напишите причину для клиента",
      cancel: "Назад",
      confirm: "Отменить запись",
      submitting: "Отменяем…",
    },
    weekView: {
      masterColumn: "Мастер",
      occupancyTemplate: "{booked}/{total}",
      // Ячейка дня узкая (7 в ряд) — полное слово налезало на соседнюю. Полное — в `title`.
      dayOff: "Вых.",
      dayOffFull: "Выходной",
      empty: "В этой студии пока нет мастеров.",
    },
    empty: {
      noMasters: "Сегодня нет мастеров на смене.",
    },
    errors: {
      create: "Не удалось создать запись. Попробуйте ещё раз.",
      move: "Не удалось перенести запись. Возможно, это время уже занято.",
      cancel: "Не удалось отменить запись. Попробуйте ещё раз.",
      // BOOKING-STUDIO-RESCHEDULE-PARITY-01: accept/decline of a client-proposed
      // reschedule failed (e.g. the new time now conflicts).
      bookingReschedule:
        "Не удалось ответить на перенос. Попробуйте ещё раз.",
      masterRequired: "Выберите мастера.",
      serviceRequired: "Выберите услугу.",
      clientNameRequired: "Укажите имя клиента.",
      clientPhoneRequired: "Укажите телефон клиента.",
      clientPhoneInvalid: "Проверьте номер телефона.",
      // STUDIO-BOOKINGS-FIX-A #3б: explicit error when the header
      // «Новая запись» button is used but the studio admin didn't
      // pick a time. Pre-fix the form fell back to generic «create»
      // — confusing because there was nothing visible to fix.
      breakMasterRequired: "Выберите мастера для перерыва.",
      breakTimeRange: "Время окончания должно быть позже начала.",
      breakCreate: "Не удалось создать перерыв. Попробуйте ещё раз.",
      breakDelete: "Не удалось удалить перерыв. Попробуйте ещё раз.",
    },
  },
  servicesV2: {
    header: {
      caption: "ПРАЙС · {services} услуг в {categories} категориях",
      title: "Услуги студии",
      subtitle:
        "Общий прайс. Мастера могут добавлять свои услуги поверх общих и менять цены.",
      addService: "Добавить услугу",
      noCategoriesHint: "Сначала создайте категорию",
    },
    kpis: {
      total: "Услуг в прайсе",
      totalContext: "{count} категорий",
      popular: "Самая популярная",
      popularContext: "{count} раз / 30 дней",
      averageCheck: "Средний чек студии",
      averageCheckDelta: "за 30 дней",
      withoutMaster: "Услуги без мастера",
      withoutMasterContext: "все услуги назначены",
      withoutMasterWarn: "нужен мастер",
    },
    categories: {
      title: "Категории",
      addCategory: "Категория",
      empty: "Создайте первую категорию",
      pendingBadge: "На модерации",
      pendingHint: "Категория на модерации — видна только вам, пока мы её не одобрим",
      // STUDIO-SERVICES-SORT-A: «Скрыть пустые» toggle label +
      // actionable hint when every category is hidden by the
      // filter (admin can switch off, or add services).
      hideEmptyLabel: "Скрыть пустые",
      allEmptyHint:
        "Все категории пустые. Отключите фильтр или добавьте услуги.",
    },
    list: {
      searchPlaceholder: "Поиск услуги",
      searchPlaceholderTemplate: "Поиск в категории «{category}»",
      empty: "В этой категории пока нет услуг.",
      bookingsTemplate: "{count} записей за 30 дней",
      durationTemplate: "{min} мин",
      pausedBadge: "пауза",
      noMasterBadge: "без мастера",
    },
    detail: {
      caption: "УСЛУГА",
      empty: {
        title: "Выберите услугу",
        hint: "Выберите услугу слева, чтобы изменить цену и время.",
      },
      nameLabel: "Название",
      priceLabel: "Цена, ₽",
      durationLabel: "Длительность, мин",
      categoryLabel: "Категория",
      categoryNone: "— Без категории —",
      pendingSuffix: "на модерации",
      isActiveLabel: "Услуга активна",
      isActiveHint: "Выключенную услугу не видно в каталоге, и записаться на неё нельзя.",
      mastersLabel: "Кто делает эту услугу · {count}",
      mastersEmpty: "Назначьте хотя бы одного мастера, чтобы клиенты могли записаться.",
      assignMaster: "Назначить мастера",
      unassignMaster: "Снять мастера",
      statsTitle: "Статистика · 30 дней",
      statsBookings: "Записей",
      statsRevenue: "Выручка",
      save: "Сохранить",
      saving: "Сохраняем…",
      saved: "Изменения сохранены",
      delete: "Удалить",
    },
    addServiceDialog: {
      title: "Новая услуга",
      nameLabel: "Название",
      namePlaceholder: "Маникюр классический",
      priceLabel: "Цена, ₽",
      durationLabel: "Длительность, мин",
      categoryLabel: "Категория",
      categoryNone: "Выберите категорию",
      pendingSuffix: "на модерации",
      proposeCategory: "Новая категория",
      proposeHint:
        "Категорию проверит модератор. Услугу можно добавить в неё сразу.",
      proposePlaceholder: "Например: Ногти",
      proposeSubmit: "Создать",
      proposeSubmitting: "Создаём…",
      proposeCancel: "Отмена",
      cancel: "Отмена",
      submit: "Создать",
      submitting: "Создаём…",
    },
    addCategoryDialog: {
      title: "Новая категория",
      subtitle: "Категория поможет группировать услуги в прайсе.",
      nameLabel: "Название категории",
      namePlaceholder: "Например: Ногти",
      cancel: "Отмена",
      submit: "Добавить",
      submitting: "Добавляем…",
    },
    assignMasterDialog: {
      title: "Назначить мастера",
      subtitle: "Выберите мастера — он сможет оказывать эту услугу.",
      masterLabel: "Мастер",
      noAvailable:
        "Все мастера уже назначены. Приглашённые появятся здесь, когда примут приглашение.",
      cancel: "Отмена",
      submit: "Назначить",
      submitting: "Назначаем…",
    },
    deleteServiceDialog: {
      title: "Удалить услугу",
      bodyTemplate:
        "Услуга «{name}» будет удалена из прайса. Действие нельзя отменить.",
      cancel: "Отмена",
      confirm: "Удалить",
      submitting: "Удаляем…",
    },
    errors: {
      titleRequired: "Укажите название услуги.",
      priceInvalid: "Укажите цену — 0 или больше.",
      durationInvalid: "Укажите, сколько минут занимает услуга.",
      categoryRequired: "Выберите категорию.",
      masterRequired: "Выберите мастера.",
      categoryTitleRequired: "Укажите название категории.",
      serviceCreate: "Не удалось создать услугу. Попробуйте ещё раз.",
      categoryCreate: "Не удалось создать категорию. Попробуйте ещё раз.",
      saveFailed: "Не удалось сохранить изменения. Попробуйте ещё раз.",
      deleteFailed: "Не удалось удалить услугу. Попробуйте ещё раз.",
      assignFailed: "Не удалось назначить мастера. Попробуйте ещё раз.",
      unassignFailed: "Не удалось снять мастера. Попробуйте ещё раз.",
      packageNameRequired: "Укажите название пакета.",
      packageMinServices: "Выберите минимум 2 услуги.",
      packageSave: "Не удалось сохранить пакет. Попробуйте ещё раз.",
      packageDelete: "Не удалось удалить пакет. Попробуйте ещё раз.",
    },
    packages: {
      sectionTitle: "Пакеты услуг",
      sectionSubtitle:
        "Объединяйте 2+ услуги в выгодный пакет — клиент видит итоговую цену со скидкой.",
      addPackage: "Создать пакет",
      emptyTitle: "Пакетов пока нет",
      emptyBody:
        "Создайте первый пакет — например, «Маникюр + педикюр» — и предложите клиентам выгодную цену.",
      minServicesHint: "Сначала добавьте хотя бы 2 услуги в прайс.",
    },
    package: {
      edit: "Редактировать",
      delete: "Удалить",
      pausedBadge: "пауза",
      componentsLabel: "Состав · {count} услуг",
      componentDisabled: "выключена",
      warningDisabledComponents:
        "В пакете есть выключенные услуги — клиент не сможет на него записаться.",
      finalPriceLabel: "Цена пакета",
      savingsTemplate: "выгода {amount}",
      durationTemplate: "{min} мин",
    },
    packageDialog: {
      discountTypeAria: "Тип скидки",
      titleCreate: "Новый пакет",
      titleEdit: "Пакет услуг",
      nameLabel: "Название пакета",
      namePlaceholder: "Например: Маникюр + педикюр",
      servicesLabel: "Услуги в пакете",
      servicesEmpty:
        "Сначала добавьте услуги в прайс — без них пакет не создать.",
      minServicesHint: "Минимум 2 услуги. Клиент записывается на весь пакет сразу.",
      minShort: "мин",
      disabledTag: "выключена",
      discountLabel: "Скидка пакета",
      discountPercent: "Процент",
      discountFixed: "Сумма, ₽",
      previewTotal: "Сумма услуг",
      previewDiscount: "Скидка",
      previewFinal: "Итоговая цена",
      previewDurationTemplate: "Общая длительность ~ {min} мин",
      isEnabledLabel: "Пакет активен",
      isEnabledHint: "Выключенные пакеты не показываются в каталоге и при записи.",
      cancel: "Отмена",
      submitting: "Сохраняем…",
      submitCreate: "Создать пакет",
      submitSave: "Сохранить",
    },
    deletePackageDialog: {
      title: "Удалить пакет",
      bodyTemplate: "Пакет «{name}» будет удалён. Действие нельзя отменить.",
      cancel: "Отмена",
      confirm: "Удалить",
      submitting: "Удаляем…",
    },
  },
  bookingsV2: {
    header: {
      caption: "ВСЕ ЗАПИСИ · {count} на экране",
      title: "Журнал записей",
      subtitle: "Все записи всех мастеров. Отбирайте по мастеру, времени и состоянию записи.",
      newBooking: "Новая запись",
    },
    kpis: {
      today: "Сегодня",
      todayContext: "{completed} завершено · {upcoming} впереди",
      needsAction: "Требуют действий",
      needsActionContext: "{count} неподтверждены",
      confirmed: "Подтверждено",
      confirmedContext: "на ближайшие 7 дней",
      revenue: "Выручка дня",
      revenueDelta: "к среднему",
      noShow: "Не пришли",
      noShowContext: "за последние 7 дней",
    },
    filters: {
      rangeAria: "Период записей",
      ranges: {
        today: "Сегодня",
        tomorrow: "Завтра",
        week: "Неделя",
        all: "Все",
      },
      statusAll: "Все записи",
      masterAll: "Все мастера",
      searchPlaceholder: "Поиск клиента или услуги",
      statusLabels: {
        NEW: "Новая",
        PENDING: "Ожидает",
        CONFIRMED: "Подтверждена",
        CHANGE_REQUESTED: "Изменение",
        REJECTED: "Отклонена",
        IN_PROGRESS: "Идёт",
        PREPAID: "Оплачена",
        STARTED: "Начата",
        FINISHED: "Завершена",
        CANCELLED: "Отменена",
        NO_SHOW: "Не пришёл",
      },
    },
    table: {
      colWhen: "Когда",
      colMaster: "Мастер",
      colClient: "Клиент",
      colService: "Услуга",
      colPrice: "Цена",
      colSource: "Источник",
      colStatus: "Состояние",
      todayPrefix: "сегодня",
      tomorrowPrefix: "завтра",
      durationTemplate: "{min} мин",
    },
    client: {
      newBadge: "новый",
      vipBadge: "VIP",
    },
    source: {
      catalog: "Каталог",
      phone: "Звонок",
      app: "Приложение",
    },
    actions: {
      openChat: "Открыть чат",
      menu: "Действия",
    },
    empty: {
      title: "Нет записей",
      hint: "Записи появятся после первых клиентов.",
      filteredTitle: "Под фильтр ничего не попало",
      filteredHint: "Измените условия или сбросьте фильтры.",
      resetCta: "Сбросить фильтры",
    },
    pagination: {
      loadMore: "Показать ещё",
    },
  },
  settingsV2: {
    header: {
      caption: "НАСТРОЙКИ СТУДИИ",
      title: "Настройки",
      subtitle:
        "Карточка студии, команда, уведомления и правила. Часть разделов появится по мере развития платформы.",
    },
    nav: {
      sectionsLabel: "Разделы",
      // FIX-STUDIO-SETTINGS-MERGE: вкладка «Общее» удалена — её единственные
      // собственные поля (слоган + часовой пояс) переехали сюда, а карточка
      // адреса дублировала редактируемую в профиле.
      profile: "Профиль",
      portfolio: "Портфолио",
      ownerTeam: "Владелец и команда",
      notifications: "Уведомления и связь",
      policy: "Правила студии",
      danger: "Необратимые действия",
    },
    portfolio: {
      cardTitle: "Портфолио",
      cardDesc:
        "Добавляйте работы студии — они появятся на публичной странице, в ленте и в историях на главной. Подпишите, кто из мастеров и какую услугу делал.",
    },
    ownerTeam: {
      ownerTitle: "Владелец студии",
      ownerDesc: "Только владелец может удалить студию и менять права команды.",
      ownerMissing: "Владелец не определён. Свяжитесь с поддержкой.",
      transferHint:
        "Передать студию другому владельцу пока нельзя — добавим в одном из обновлений.",
      teamTitle: "Команда управления",
      teamDesc:
        "Администраторы видят все записи студии. Мастера управляются в разделе «Мастера».",
      adminsEmpty: "Пока нет других администраторов кроме владельца.",
      inviteHint:
        "Приглашение администраторов появится позже. Пока приглашать администраторов нельзя — добавим позже.",
      roleOwner: "Владелец",
      roleAdmin: "Администратор",
      youChip: "Вы",
    },
    notifications: {
      channelsTitle: "Каналы уведомлений",
      // FIX-EXTERNAL-GATING-01 (G-2): provider-neutral — each channel card
      // below is flag-gated, so the description must not name a specific
      // (possibly killed/disabled) provider.
      // AUTH-GATE-01: dropped the trailing «SMS пока недоступен — мы
      // подключаем шлюз.» Naming an unshipped channel is still a delivery
      // promise, and the sentence contradicted itself on a surface that is
      // supposed to describe channels that exist. The remaining wording is
      // provider-neutral (FIX-EXTERNAL-GATING-01 G-2) and stays correct
      // whichever channels are enabled.
      channelsDesc:
        "Новости студии приходят в приложение и туда, куда вы подключили.",
      channelPush: "Уведомления на телефон",
      pushEnabled: "Включены",
      pushDisabled: "Выключены",
      pushHint:
        "Включаются сами, когда приложение добавлено на экран телефона. Выбор уведомлений для команды появится позже.",
      telegramTitle: "Telegram",
      telegramDesc: "Присылать новости студии вам в Telegram.",
      vkTitle: "VK",
      vkDesc: "Присылать новости студии вам в VK.",
    },
    policy: {
      title: "Правила записи",
      // FIX-STUDIO-POLICY-EDITABLE: раздел стал редактируемым. Прежний текст
      // отправлял «в настройки расписания мастера» — а туда без мастеров не
      // попасть, и правила студии оказывались недостижимы.
      description:
        "Клиент видит их при записи. Действуют для всей студии — отдельные мастера не нужны.",
      minBookingAhead: "Минимум за",
      minBookingAheadHint: "Раньше этого окна окошко клиенту не покажем.",
      maxBookingAhead: "Максимум вперёд",
      maxBookingAheadHint: "Насколько далеко вперёд открыта запись.",
      cancellationDeadline: "Бесплатная отмена за",
      cancellationDeadlineHint: "Позже этого срока отмена считается поздней.",
      lateCancelAction: "При поздней отмене",
      acceptNewClients: "Новые клиенты",
      acceptNewClientsHint: "Выключите, если записываете только своих.",
      remindersEnabled: "Напоминания",
      remindersEnabledHint: "Письмо клиенту за сутки и за два часа до визита.",
      hoursTemplate: "{hours} ч",
      daysTemplate: "{days} дней",
      notSet: "Не задано",
      yes: "Да",
      no: "Нет",
      lateActions: {
        none: "Ничего не делать",
        reminder: "Только напоминание",
        fine: "Штраф (скоро)",
      },
      hoursUnit: "часов",
      daysUnit: "дней",
      saving: "Сохраняем…",
      minBookingAheadInvalid: "Укажите минимум записи от 0 до 168 часов.",
      maxBookingAheadInvalid: (maxDays: number) =>
        `Укажите горизонт записи от 1 до ${maxDays} дней.`,
      cancellationDeadlineInvalid:
        "Укажите срок бесплатной отмены от 0 до 168 часов или оставьте поле пустым.",
    },
    danger: {
      // FIX-STUDIO-ARCHIVE-REMOVED: «Архивировать» удалено — действие писало
      // ровно `isPublished = false`, то есть было вторым, необратимо
      // выглядящим именем для тумблера «Опубликован» в разделе «Профиль».
      deleteTitle: "Удалить студию навсегда",
      deleteDesc:
        "Мастера покинут студию, а записи и подписки будут удалены. Вернуть их нельзя.",
      deleteButton: "Удалить студию",
      deleting: "Удаляем…",
      deleteDialogTitle: "Подтвердите удаление",
      deleteDialogBody:
        "Удаление окончательное. Чтобы продолжить, введите название студии ниже.",
      deleteConfirmLabel: "Введите «{name}» для подтверждения",
      deleteCancel: "Отмена",
      deleteConfirm: "Удалить навсегда",
      activeBookingsError:
        "Сначала отмените или завершите записи, которые ещё впереди.",
    },
    save: "Сохранить",
    cancel: "Отмена",
    toasts: {
      saved: "Изменения сохранены",
      error: "Не удалось сохранить настройки. Попробуйте ещё раз.",
    },
  },
  analyticsV2: {
    viewsAria: "Раздел аналитики",
    header: {
      caption: "АНАЛИТИКА · последние {days} дней",
      title: "Бизнес-показатели",
      subtitle: "Сравните периоды, мастеров и услуги. Доступно на тарифах PRO и PREMIUM.",
    },
    periodLabel: "Период",
    periods: { d7: "7 дней", d30: "30 дней", d90: "Квартал", d365: "Год" },
    views: {
      overview: "Обзор",
      masters: "Мастера",
      services: "Услуги",
      clients: "Клиенты",
    },
    compare: "Сравнить с прошлым периодом",
    kpi: {
      revenue: "Выручка студии",
      bookings: "Записей",
      avgCheck: "Средний чек",
      occupancy: "Загрузка",
      retention: "Возврат клиентов",
      noPrev: "Нет данных за прошлый период",
    },
    overview: {
      revenueChartTitle: "Выручка по дням",
      revenueCompare: "Сравнение с предыдущим периодом",
      revenueNoCompare: "Период",
      legendNow: "Сейчас",
      legendPrev: "Прошлый период",
      revenueChartAria: "Динамика выручки",
      sourcesTitle: "Источники записи",
      sourcesDesc: "Откуда приходят клиенты",
      hoursTitle: "Загрузка по часам",
      hoursDesc: "Когда у студии пик",
      wasTemplate: "было {value}",
      noData: "Недостаточно данных",
    },
    masters: {
      colMaster: "Мастер",
      colBookings: "Записей",
      colRevenue: "Выручка",
      colAvgCheck: "Ср. чек",
      colOccupancy: "Загрузка",
      colRating: "Рейтинг",
      empty: {
        title: "Нет данных по мастерам",
        hint: "Появится после первых завершённых записей за период.",
      },
    },
    services: {
      colService: "Услуга",
      colBookings: "Записей",
      colRevenue: "Выручка",
      colShare: "Доля",
      colMasters: "Мастеров",
      empty: {
        title: "Нет данных по услугам",
        hint: "Появится после первых завершённых записей за период.",
      },
    },
    clients: {
      segmentsTitle: "Сегменты клиентов",
      segmentsDesc: "Новые / возвращающиеся / постоянные / спящие / потерянные",
      topClientsTitle: "Топ-10 клиентов по выручке",
      topClientsDesc: "Кто приносит больше всего за период",
      colClient: "Клиент",
      colVisits: "Визитов",
      colLifetime: "Выручка",
      empty: {
        title: "Нет клиентов за период",
        hint: "Как только записей станет больше, здесь появятся группы клиентов.",
      },
    },
  },
  notificationsV2: {
    header: {
      caption: "УВЕДОМЛЕНИЯ · {unread} непрочитано из {total}",
      title: "Уведомления",
      subtitle:
        "Всё по студии в одной ленте. Уведомления о записях к мастеру приходят и в его личный кабинет.",
    },
    kpis: {
      unread: "Непрочитанных",
      unreadTemplate: "{count} из {total}",
      today: "Сегодня",
      todayTemplate: "{count} уведомлений",
      needsDecision: "Ждут решения",
      needsDecisionTemplate: "{count} от владельца",
      push: "Уведомления на телефон",
      pushEnabled: "Включены",
      pushDisabled: "Выключены",
      pushHint: "Приходят автоматически",
    },
    filters: {
      aria: "Какие уведомления показать",
      all: "Все",
      unread: "Непрочитанные",
      bookings: "Записи",
      cancellations: "Отмены",
      reschedules: "Переносы",
      reviews: "Отзывы",
      messages: "Сообщения",
      team: "Команда",
      finance: "Финансы",
      system: "От платформы",
      sortNewest: "Сначала новые",
      sortOldest: "Сначала старые",
      markAllRead: "Прочитать всё",
      markAllReadFailed: "Не удалось отметить уведомления. Попробуйте ещё раз.",
    },
    infoBanner:
      "Кому из команды приходят уведомления на телефон — настраивается в {settingsLink}. Уведомления о записях к мастеру приходят и в его личный кабинет.",
    infoBannerLink: "Настройках студии",
    card: {
      relatesTo: "Касается",
      unreadAria: "Непрочитанное уведомление",
    },
    actions: {
      approve: "Подтвердить",
      reject: "Отклонить",
      rejectPrompt: "Укажите причину отклонения заявки:",
      rejectTitle: "Отклонить заявку",
      rejectLabel: "Причина",
      openRequest: "Открыть заявку",
      openBooking: "К записи",
      openReview: "К отзыву",
      openChat: "К чату",
      openClient: "К клиенту",
      open: "Открыть",
      acceptReschedule: "Принять перенос",
      declineReschedule: "Отклонить перенос",
    },
    empty: {
      title: "Нет уведомлений",
      hint: "Уведомления появятся здесь, как только что-то произойдёт.",
    },
    errors: {
      scheduleRequest: "Не удалось ответить на заявку. Попробуйте ещё раз.",
      bookingReschedule: "Не удалось ответить на перенос. Попробуйте ещё раз.",
    },
  },
  reviewsV2: {
    header: {
      caption: "ОТЗЫВЫ · {total} всего · из них {noReply} без ответа",
      title: "Отзывы клиентов",
      subtitle: "Все отзывы по всем мастерам в одном месте. Отвечайте от имени студии.",
    },
    stats: {
      avgTitle: "Средний рейтинг студии",
      avgBasis: "На основе {count} отзывов · {percent}% положительные",
      distributionTitle: "Распределение оценок",
      topServicesTitle: "Топ услуг по отзывам",
      topServicesCount: "{count} отзывов",
      topServicesEmpty: "Пока нет отзывов с привязкой к услугам",
    },
    filters: {
      aria: "Какие отзывы показать",
      all: "Все",
      noReply: "Без ответа",
      lowRating: "Низкие оценки",
      fiveStar: "5 звёзд",
      masterAll: "Все мастера",
    },
    card: {
      replyCaption: "ОТВЕТ СТУДИИ",
      reportedBadge: "На рассмотрении",
    },
    actions: {
      reply: "Ответить",
      report: "Пожаловаться",
    },
    replyForm: {
      placeholder: "Ваш ответ клиенту…",
      hint: "Ответ будет опубликован от имени студии.",
      submit: "Опубликовать ответ",
      submitting: "Публикуем…",
      cancel: "Отмена",
    },
    reportDialog: {
      title: "Пожаловаться на отзыв",
      subtitle: "Жалоба отправится администратору платформы. Можно подать только один раз.",
      reasonLabel: "Причина",
      commentLabel: "Комментарий (необязательно)",
      commentPlaceholder: "Опишите, почему отзыв нарушает правила",
      submit: "Отправить",
      submitting: "Отправляем…",
      cancel: "Отмена",
    },
    pagination: {
      loadMore: "Показать ещё",
    },
    empty: {
      title: "Нет отзывов",
      hint: "Отзывы клиентов будут появляться здесь после завершённых записей.",
    },
    toasts: {
      replyPosted: "Ответ опубликован",
      reported: "Жалоба отправлена",
      error: "Не удалось отправить ответ. Попробуйте ещё раз.",
    },
  },
  clientsV2: {
    header: {
      caption: "КЛИЕНТСКАЯ БАЗА · {total} человек · {filtered} отфильтровано",
      title: "Клиенты студии",
      subtitle: "Общая база. Каждый мастер видит только своих, владелец — всех.",
      addClient: "Клиент",
    },
    kpis: {
      total: "Всего клиентов",
      totalSub: "+{count} за месяц",
      active: "Активных за 30 дней",
      activeSub: "{percent}% от базы",
      avgLifetime: "Приносит в среднем",
      avgLifetimeSub: "по студии в среднем",
      vip: "VIP-клиенты",
      vipSub: "{percent}% выручки",
      sleeping: "Спящие · 60+ дней",
      sleepingSub: "их можно вернуть",
    },
    segments: {
      title: "Сегменты",
      all: "Все клиенты",
      vip: "VIP",
      regular: "Постоянные",
      new: "Новые",
      sleeping: "Спящие",
    },
    filters: {
      searchPlaceholder: "Имя клиента или телефон",
      masterAll: "Все мастера",
    },
    table: {
      colClient: "Клиент",
      colPhone: "Телефон",
      colVisits: "Визитов",
      colLtv: "Всего оставил",
      colLast: "Последний визит",
      colMainMaster: "Основной мастер",
      mastersCountTemplate: "у {count} мастеров",
      avgCheckTemplate: "ср. {amount}",
    },
    badges: {
      vip: "VIP",
      regular: "Постоянный",
      new: "Новый",
      sleeping: "Спящий",
      other: "—",
    },
    actions: {
      book: "Записать",
    },
    pagination: {
      loadMore: "Показать ещё",
    },
    empty: {
      title: "Нет клиентов",
      hint: "Клиенты появятся после первых записей.",
      filteredTitle: "Под фильтр никто не попал",
      filteredHint: "Измените запрос или сбросьте фильтры.",
      resetCta: "Сбросить фильтры",
    },
    errors: {
      loadFailed: "Не удалось загрузить клиентов. Попробуйте ещё раз.",
    },
  },
  mastersV2: {
    header: {
      caption: (count: number) =>
        `КОМАНДА · ${count} ${pluralize(count, "мастер", "мастера", "мастеров")}`,
      title: "Мастера студии",
      subtitle: (active: number, disabled: number, invited: number) =>
        `${active} ${pluralize(active, "активный", "активных", "активных")} · ${disabled} в паузе · ${invited} ${pluralize(invited, "новый", "новых", "новых")}`,
      inviteButton: "Пригласить мастера",
    },
    filters: {
      tabsAria: "Какие мастера показать",
      searchPlaceholder: "Поиск по имени или специализации",
      tabs: {
        all: "Все",
        active: "Активные",
        invited: "Новые",
        disabled: "Пауза",
      },
    },
    status: {
      active: "Работает",
      invited: "Новый",
      disabled: "Пауза",
    },
    listItem: {
      youChip: "вы",
      bookingsTemplate: "{count} записей",
      occupancyTemplate: "{percent}% загрузка",
    },
    list: {
      shownTemplate: "Показано: {count} из {total}",
      empty: "Никого не нашли — попробуйте сменить фильтр.",
      emptyTeam: "В команде пока никого — пригласите первого мастера.",
    },
    inviteCard: {
      title: "Пригласить ещё мастера",
      // AUTH-GATE-01: was «По телефону — мастер получит SMS со ссылкой».
      // No SMS is sent — `notifyStudioInviteReceived` delivers an in-app
      // notification and ONLY when the phone already belongs to a registered
      // user (it early-returns otherwise). Copy now states the part that is
      // always true: the master appears in the team as «Приглашён».
      subtitle: "Добавьте мастера по номеру телефона",
    },
    detail: {
      empty: {
        title: "Выберите мастера",
        hint: "Выберите мастера слева, чтобы посмотреть подробности.",
      },
      youChip: "Это вы",
      joinedTemplate: "в студии с {date}",
      clientsTemplate: "{count} клиентов",
      actions: {
        // STUDIO-CLEANUP-FIX-A #4а: `message` key removed — the
        // «Написать» button it labelled was a misleading Link to
        // the client-cabinet messages page (studio admin isn't a
        // chat participant per invariant #26). Feature deferred to
        // backlog. Other actions preserved.
        schedule: "Расписание",
        publicProfile: "Публичный профиль",
        pause: "Поставить на паузу",
        activate: "Вернуть к работе",
        // FIX-STUDIO-02 (F7): revoke a still-pending invite (INVITED status).
        revoke: "Отозвать приглашение",
        // STUDIO-EDIT-MASTER-PROFILE-01
        editProfile: "Редактировать профиль",
        // 29.09 доработки · 04
        remove: "Удалить из студии",
      },
      // 29.09 доработки · 04: будущие записи студии у мастера — удалить из
      // студии можно только после их переноса или отмены.
      blockingBookings: (count: number) =>
        `Будущих записей в студии: ${count} — перед удалением перенесите их на другого мастера или отмените.`,
      kpis: {
        revenue: "Выручка · 30д",
        bookings: "Записей · 30д",
        bookingsSubtitle: "за последние 30 дней",
        averageCheckTemplate: "ср.чек {amount}",
        occupancy: "Загрузка",
        occupancyAboveNorm: "выше нормы",
        occupancyOnNorm: "норма",
        occupancyBelowNorm: "ниже нормы",
        rating: "Рейтинг",
        reviewsTemplate: "{count} отзывов",
      },
      weekSchedule: {
        title: "Расписание · эта неделя",
        subtitle: "Мастер меняет своё расписание через заявку вам",
        seeCalendar: "В календарь →",
        slotsTemplate: "{booked}/{total}",
        // Ячейка дня узкая (7 в ряд) — полное слово налезало на соседнюю. Полное — в `title`.
        dayOff: "Вых.",
        dayOffFull: "Выходной",
      },
    },
    inviteDialog: {
      title: "Пригласить мастера",
      // AUTH-GATE-01: see inviteCard.subtitle — no SMS is sent for invites.
      // STUDIO-INVITE-EMAIL-01: по почте уходит письмо со ссылкой, и принять
      // такое приглашение можно сразу — почта подтверждается входом.
      subtitle:
        "Введите телефон или почту — мастер появится в команде с пометкой «Приглашён». На почту придёт письмо с приглашением.",
      phoneLabel: "Телефон или почта",
      phonePlaceholder: "+7 999 123-45-67 или anna@mail.ru",
      nameLabel: "Имя",
      namePlaceholder: "Анна Соколова",
      taglineLabel: "Специализация",
      taglinePlaceholder: "Маникюр, педикюр",
      cancel: "Отмена",
      submit: "Отправить приглашение",
      submitting: "Отправляем…",
    },
    // STUDIO-EDIT-MASTER-PROFILE-01 — руководитель студии правит профиль мастера.
    editProfileDialog: {
      title: "Профиль мастера",
      subtitle: "Так мастера увидят клиенты — на странице студии, на его странице и в каталоге.",
      photoLabel: "Фото",
      nameLabel: "Имя",
      taglineLabel: "Специализация",
      taglinePlaceholder: "Маникюр, педикюр",
      descriptionLabel: "О мастере",
      descriptionPlaceholder: "Опыт, техники, чем мастер хорош",
      nameRequired: "Укажите имя мастера.",
      taglineRequired: "Укажите специализацию мастера.",
      saveFailed: "Не удалось сохранить профиль мастера. Попробуйте ещё раз.",
      submit: "Сохранить",
      cancel: "Отмена",
    },
    pauseDialog: {
      title: "Поставить на паузу",
      bodyTemplate: "Мастер {name} не будет принимать новые записи. Действие можно отменить в любой момент.",
      cancel: "Отмена",
      confirm: "Поставить на паузу",
      submitting: "Сохраняем…",
    },
    activateDialog: {
      title: "Вернуть мастера к работе",
      bodyTemplate: "Мастер {name} снова сможет принимать новые записи.",
      cancel: "Отмена",
      confirm: "Вернуть к работе",
      submitting: "Сохраняем…",
    },
    // 29.09 доработки · 04: исключение мастера из студии.
    removeDialog: {
      title: "Удалить из студии",
      bodyTemplate:
        "Мастер {name} больше не будет работать в студии: студийные записи, расписание и услуги ему станут недоступны. Его личная страница и личные записи останутся.",
      transferServicesLabel: "Сохранить мастеру его услуги",
      transferServicesHint: "Услуги студии, которые он оказывал, появятся в его личном прайсе.",
      cancel: "Отмена",
      confirm: "Удалить из студии",
      openCalendar: "Открыть расписание мастера",
    },
    // FIX-STUDIO-02 (F7): confirm dialog for revoking a pending invite.
    revokeDialog: {
      title: "Отозвать приглашение",
      bodyTemplate:
        "Приглашение мастеру {name} будет отменено, а ссылка перестанет работать. Место в команде не изменится.",
      cancel: "Отмена",
      confirm: "Отозвать приглашение",
      submitting: "Отзываем…",
    },
    errors: {
      phoneInvalid: "Укажите телефон или почту мастера.",
      nameRequired: "Укажите имя мастера.",
      taglineRequired: "Укажите специализацию.",
      inviteFailed: "Не удалось отправить приглашение. Попробуйте ещё раз.",
      actionFailed: "Не удалось изменить мастера. Попробуйте ещё раз.",
      removeFailed: "Не удалось удалить мастера из студии. Попробуйте ещё раз.",
      // FIX-STUDIO-02 (F6): localized team-cap block. The enforcement
      // (`ensureStudioTeamLimit`) is unchanged — only the message. Says what
      // the limit is and how to raise it, instead of the raw «Limit reached».
      teamCapReached:
        "На вашем тарифе можно держать до {max} активных мастеров. Чтобы добавить больше, перейдите на тариф выше.",
      teamCapReachedGeneric:
        "На вашем тарифе больше активных мастеров не добавить. Чтобы добавить, перейдите на тариф выше.",
      // FIX-STUDIO-02 (F7): revoke-invite failure.
      revokeFailed: "Не удалось отозвать приглашение. Попробуйте ещё раз.",
    },
  },
  scheduleRequests: {
    title: "Заявки на расписание",
    subtitle: "Мастера студии запрашивают изменения графика — подтвердите или отклоните.",
    pendingTitle: "Ожидают решения",
    pendingCount: "Всего: {count}",
    resolvedTitle: "Недавние решения",
    emptyPendingTitle: "Заявок нет",
    emptyPendingBody: "Когда мастер запросит изменение расписания, заявка появится здесь.",
    submittedAt: "Отправлено",
    commentLabel: "Комментарий",
    status: {
      pending: "Ожидает",
      approved: "Подтверждена",
      rejected: "Отклонена",
    },
    actions: {
      approve: "Подтвердить",
      reject: "Отклонить",
    },
    preview: {
      weekTitle: "Недельный график",
      exceptionsTitle: "Особые дни",
      breaksLabel: "Перерывы",
      legacyTitle: "Изменения расписания",
      patternTitle: "Новый график",
      currentLabel: "Сейчас",
      proposedLabel: "Будет",
      daysTitle: "Дни календаря",
      dayCount: (count: number) => `Изменения дней: ${count}`,
      dayOff: "Выходной",
      byPattern: "как по графику",
      fixedTime: "фикс. время",
      arrowAria: "станет",
    },
    approveDialog: {
      title: "Подтвердить изменения?",
      body: "Расписание мастера {provider} будет обновлено сразу после подтверждения. Действие необратимо.",
      cancel: "Отмена",
      confirm: "Подтвердить",
      submitting: "Подтверждаем…",
    },
    rejectDialog: {
      title: "Отклонить заявку?",
      body: "Мастер {provider} получит уведомление с вашим комментарием.",
      commentLabel: "Причина отказа",
      commentPlaceholder: "Кратко опишите, почему заявку нельзя подтвердить",
      cancel: "Отмена",
      confirm: "Отклонить",
      submitting: "Отклоняем…",
    },
    errors: {
      approveFailed: "Не удалось подтвердить заявку. Попробуйте ещё раз.",
      rejectFailed: "Не удалось отклонить заявку. Попробуйте ещё раз.",
      commentRequired: "Укажите причину отказа.",
    },
  },
} as const;
