// Все новые UI-строки добавлять сюда.
// Не использовать захардкоженные строки в компонентах.
export const UI_TEXTS = {
  common: {
    profile: "Профиль",
    myBookings: "Мои записи",
    save: "Сохранить",
    cancel: "Отмена",
    connect: "Подключить",
    disconnect: "Отключить",
    enabled: "Включено",
    disabled: "Выключено",
    loading: "Загрузка…",
    name: "Имя",
    phone: "Телефон",
    comment: "Комментарий",
    commentOptional: "Комментарий (необязательно)",
    notNow: "Не сейчас",
    error: "Ошибка",
    refresh: "Обновить",
  },

  telegram: {
    title: "Уведомления в Telegram",
    connected: "Подключено",
    notConnected: "Не подключено",
    enabled: "Уведомления включены",
    disabled: "Уведомления выключены",
    hint: "Если бот перестал писать — откройте чат с ботом и нажмите Start.",
    connectButton: "Подключить",
  },

  booking: {
    book: "Записаться",
    chooseDate: "Выберите дату",
    chooseTime: "Выберите время",
    noSlots: "Нет доступных слотов",
    pending: "Ожидает",
    confirmed: "Подтверждено",
    cancelled: "Отменено",
    loadSlotsFailed: "Не удалось загрузить слоты",
    submitFailed: "Не удалось отправить запись",
    providerIdMissing: "providerId не задан",
    chooseMaster: "Выберите мастера",
    chooseService: "Выберите услугу",
    chooseCorrectSlot: "Выберите корректный слот",
    enterName: "Введите имя",
    enterPhone: "Введите телефон",
    authOnlyDescription: "Запись доступна только авторизованным клиентам.",
    cost: "Стоимость",
    authorized: "Вы авторизованы",
    loginToBook: "Войдите, чтобы записаться.",
    requestSent: "Заявка отправлена",
    service: "Услуга",
    commentPlaceholder: "Например: хочу естественный нюд",
    authModalTitle: "Войдите, чтобы записаться",
    authModalText:
      "Мы принимаем записи только от авторизованных клиентов — так мастерам спокойнее и меньше фейковых заявок.",
    studioHint: "Выберите услугу, затем мастера и время",
    availablePeriodPrefix: "Доступный период: с",
    availablePeriodInfix: "по",
    services: "Услуги",
    noServices: "Услуг пока нет.",
    durationUnknown: "Длительность уточняется",
    priceUnknown: "Цена уточняется",
    masters: "Мастера",
    noMasters: "Нет доступных мастеров.",
    ratingUnknown: "Рейтинг уточняется",
    slotsLabel: "Слотов:",
    slotsUnknown: "Слоты уточняются",
    durationLabel: "Длительность:",
    priceLabel: "Цена:",
    from: "от",
    slotsOnDate: "Слотов на дату:",
    chooseAnotherDateOrMaster: "Попробуйте другую дату или мастера.",
    morning: "Утро",
    day: "День",
    evening: "Вечер",
    hourShort: "ч",
    minuteShort: "мин",
    moveBooking: "Перенести запись",
    moveBookingHint: "Выберите новую дату и слот.",
    moveConfirm: "Подтвердить перенос",
    moving: "Переносим…",
  },

  bookingsList: {
    loadingTitle: "Загрузка записей…",
    loadingSubtitle: "Тянем из Supabase.",
    count: "Записей:",
    emptyTitle: "Пока записей нет",
    emptySubtitle: "Создай запись из профиля провайдера — и она появится здесь.",
    client: "Клиент:",
    provider: "Провайдер:",
    apiErrorPrefix: "API error:",
    unknownError: "Unknown error",
  },

  bookingsPanel: {
    loading: "Загружаем записи",
    empty: "Записей пока нет.",
    loadErrorPrefix: "Ошибка загрузки:",
    apiErrorPrefix: "API error:",
    unknownError: "Unknown error",
    failedToLoad: "Failed to load bookings",
    failedToCancel: "Failed to cancel",
    failedToConfirm: "Failed to confirm",
    reschedule: "Перенести",
    cancelBooking: "Отменить запись",
    cancelShort: "Отменить",
    confirm: "Подтвердить",
  },

  auth: {
    login: "Вход",
    logout: "Выход",
  },

  topbar: {
    cabinetStudio: "Кабинет студии",
    cabinetMaster: "Кабинет мастера",
    catalog: "Каталог",
    myCabinet: "Мой кабинет",
    notifications: "Уведомления",
    bookingToMasters: "Запись к мастерам",
  },

  cabinet: {
    clientTitle: "Кабинет клиента",
    clientProfileSubtitle: "Личные данные и настройки.",
    clientBookingsSubtitle: "Ваши записи к мастерам и в студии.",
  },

  login: {
    invalidPhone: "Введите телефон в международном формате, например +77001234567",
    sendCodeFailed: "Не удалось отправить код",
    invalidCode: "Неверный код",
    title: "Вход по телефону",
    subtitle: "Мы отправим код подтверждения.",
    devHint: "(Пока код выводится в консоль сервера; позже подключим SMS-агрегатор.)",
    sendCode: "Получить код",
    sending: "Отправляем...",
    codeSentTo: "Код отправлен на",
    verifying: "Проверяем...",
    changePhone: "Изменить телефон",
    returnAfterLogin: "После входа вы вернётесь на:",
    codeLabel: "Код",
    enterCode: "Введите код",
  },

  profile: {
    saveFailed: "Не удалось сохранить",
    networkError: "Сеть недоступна или сервер не отвечает",
    saved: "Сохранено",
    createMasterFailed: "Не удалось создать профиль мастера",
    masterCreated: "Профиль мастера создан",
    createStudioFailed: "Не удалось создать студию",
    studioCreated: "Студия создана",
    description:
      "Все поля пока необязательные. Заполните то, что хотите показывать/использовать.",
    professionalRolesTitle: "Мои профессиональные роли",
    rolesAddedCanAddMore: "Вы уже добавили профессиональные роли. Можно добавить еще.",
    stillClientAddRole: "Вы пока клиент. Добавьте роль мастера или студии.",
    alreadyMaster: "Вы уже мастер",
    becomeMaster: "Стать мастером",
    creatingMaster: "Создаем профиль мастера...",
    alreadyStudioOwner: "Вы уже владелец студии",
    createStudio: "Создать студию",
    creatingStudio: "Создаем студию...",
    lastName: "Фамилия",
    lastNamePlaceholder: "Иванов",
    firstName: "Имя",
    firstNamePlaceholder: "Иван",
    middleName: "Отчество",
    middleNamePlaceholder: "Иванович",
    displayName: "Отображаемое имя",
    displayNamePlaceholder: "Как вас показывать в интерфейсе",
    email: "Почта",
    birthDate: "Дата рождения",
    address: "Адрес",
    addressPlaceholder: "Город, улица, дом...",
    mapHint: "Позже добавим кнопку \"Показать на карте\" и будем сохранять координаты.",
    rolesLabel: "Роли:",
    saving: "Сохранение...",
  },
} as const;
